// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file alis/open/flows/v1/flows.proto (package alis.open.flows.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Flow, GenerateFlowTreeRequest, GenerateFlowTreeResponse, GetFlowRequest, ListFlowsRequest, ListFlowsResponse, StreamFlowsRequest } from "./flows_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { PubSubMessage } from "../../pubsub/v1/pubsub_pb.js";
import { Empty } from "../../../../google/protobuf/empty_pb.js";

/**
 * Manages Flow resources with an API service.
 *
 * When an API wants to communicate more details on the progress or steps while running,
 * this service would be used by clients to retrieve the Flow resources which will provide
 * additional details on the underlying business logic.
 *
 * @generated from service alis.open.flows.v1.FlowsService
 */
export const FlowsService = {
  typeName: "alis.open.flows.v1.FlowsService",
  methods: {
    /**
     * Get a Flow resource
     *
     * @generated from rpc alis.open.flows.v1.FlowsService.GetFlow
     */
    getFlow: {
      name: "GetFlow",
      I: GetFlowRequest,
      O: Flow,
      kind: MethodKind.Unary,
    },
    /**
     * Lists Flows.
     *
     * @generated from rpc alis.open.flows.v1.FlowsService.ListFlows
     */
    listFlows: {
      name: "ListFlows",
      I: ListFlowsRequest,
      O: ListFlowsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Streams Flows.
     *
     * @generated from rpc alis.open.flows.v1.FlowsService.StreamFlows
     */
    streamFlows: {
      name: "StreamFlows",
      I: StreamFlowsRequest,
      O: Flow,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Generate a tree of Flows and Steps.
     * This method returns a single Flow resource but with the Flow children populated.
     *
     * The response also includes the next immediate children of the leaf nodes(steps at the max depth).
     * This can be used to generate the next level of the tree on demand.
     *
     * @generated from rpc alis.open.flows.v1.FlowsService.GenerateFlowTree
     */
    generateFlowTree: {
      name: "GenerateFlowTree",
      I: GenerateFlowTreeRequest,
      O: GenerateFlowTreeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Handles an event from Pub/Sub
     *
     * @generated from rpc alis.open.flows.v1.FlowsService.HandleEvent
     */
    handleEvent: {
      name: "HandleEvent",
      I: PubSubMessage,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Handles a dead letter event from Pub/Sub
     *
     * @generated from rpc alis.open.flows.v1.FlowsService.HandleDeadLetter
     */
    handleDeadLetter: {
      name: "HandleDeadLetter",
      I: PubSubMessage,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

