// Copyright 2015 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file google/api/context.proto (package google.api, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file google/api/context.proto.
 */
export const file_google_api_context = /*@__PURE__*/
  fileDesc("Chhnb29nbGUvYXBpL2NvbnRleHQucHJvdG8SCmdvb2dsZS5hcGkiMQoHQ29udGV4dBImCgVydWxlcxgBIAMoCzIXLmdvb2dsZS5hcGkuQ29udGV4dFJ1bGUijQEKC0NvbnRleHRSdWxlEhAKCHNlbGVjdG9yGAEgASgJEhEKCXJlcXVlc3RlZBgCIAMoCRIQCghwcm92aWRlZBgDIAMoCRIiChphbGxvd2VkX3JlcXVlc3RfZXh0ZW5zaW9ucxgEIAMoCRIjChthbGxvd2VkX3Jlc3BvbnNlX2V4dGVuc2lvbnMYBSADKAlCbgoOY29tLmdvb2dsZS5hcGlCDENvbnRleHRQcm90b1ABWkVnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL2FwaS9zZXJ2aWNlY29uZmlnO3NlcnZpY2Vjb25maWeiAgRHQVBJYgZwcm90bzM");

/**
 * Describes the message google.api.Context.
 * Use `create(ContextSchema)` to create a new message.
 */
export const ContextSchema = /*@__PURE__*/
  messageDesc(file_google_api_context, 0);

/**
 * Describes the message google.api.ContextRule.
 * Use `create(ContextRuleSchema)` to create a new message.
 */
export const ContextRuleSchema = /*@__PURE__*/
  messageDesc(file_google_api_context, 1);
