// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file google/api/servicemanagement/v1/servicemanager.proto (package google.api.servicemanagement.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateServiceConfigRequest, CreateServiceRequest, CreateServiceRolloutRequest, DeleteServiceRequest, GenerateConfigReportRequest, GenerateConfigReportResponse, GetServiceConfigRequest, GetServiceRequest, GetServiceRolloutRequest, ListServiceConfigsRequest, ListServiceConfigsResponse, ListServiceRolloutsRequest, ListServiceRolloutsResponse, ListServicesRequest, ListServicesResponse, SubmitConfigSourceRequest, UndeleteServiceRequest } from "./servicemanager_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ManagedService, Rollout } from "./resources_pb.js";
import { Operation } from "../../../longrunning/operations_pb.js";
import { Service } from "../../service_pb.js";

/**
 * [Google Service Management
 * API](https://cloud.google.com/service-infrastructure/docs/overview)
 *
 * @generated from service google.api.servicemanagement.v1.ServiceManager
 */
export const ServiceManager = {
  typeName: "google.api.servicemanagement.v1.ServiceManager",
  methods: {
    /**
     * Lists managed services.
     *
     * Returns all public services. For authenticated users, also returns all
     * services the calling user has "servicemanagement.services.get" permission
     * for.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.ListServices
     */
    listServices: {
      name: "ListServices",
      I: ListServicesRequest,
      O: ListServicesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets a managed service. Authentication is required unless the service is
     * public.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.GetService
     */
    getService: {
      name: "GetService",
      I: GetServiceRequest,
      O: ManagedService,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new managed service.
     *
     * A managed service is immutable, and is subject to mandatory 30-day
     * data retention. You cannot move a service or recreate it within 30 days
     * after deletion.
     *
     * One producer project can own no more than 500 services. For security and
     * reliability purposes, a production service should be hosted in a
     * dedicated producer project.
     *
     * Operation<response: ManagedService>
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.CreateService
     */
    createService: {
      name: "CreateService",
      I: CreateServiceRequest,
      O: Operation,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a managed service. This method will change the service to the
     * `Soft-Delete` state for 30 days. Within this period, service producers may
     * call
     * [UndeleteService][google.api.servicemanagement.v1.ServiceManager.UndeleteService]
     * to restore the service. After 30 days, the service will be permanently
     * deleted.
     *
     * Operation<response: google.protobuf.Empty>
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.DeleteService
     */
    deleteService: {
      name: "DeleteService",
      I: DeleteServiceRequest,
      O: Operation,
      kind: MethodKind.Unary,
    },
    /**
     * Revives a previously deleted managed service. The method restores the
     * service using the configuration at the time the service was deleted.
     * The target service must exist and must have been deleted within the
     * last 30 days.
     *
     * Operation<response: UndeleteServiceResponse>
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.UndeleteService
     */
    undeleteService: {
      name: "UndeleteService",
      I: UndeleteServiceRequest,
      O: Operation,
      kind: MethodKind.Unary,
    },
    /**
     * Lists the history of the service configuration for a managed service,
     * from the newest to the oldest.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.ListServiceConfigs
     */
    listServiceConfigs: {
      name: "ListServiceConfigs",
      I: ListServiceConfigsRequest,
      O: ListServiceConfigsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets a service configuration (version) for a managed service.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.GetServiceConfig
     */
    getServiceConfig: {
      name: "GetServiceConfig",
      I: GetServiceConfigRequest,
      O: Service,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new service configuration (version) for a managed service.
     * This method only stores the service configuration. To roll out the service
     * configuration to backend systems please call
     * [CreateServiceRollout][google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout].
     *
     * Only the 100 most recent service configurations and ones referenced by
     * existing rollouts are kept for each service. The rest will be deleted
     * eventually.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.CreateServiceConfig
     */
    createServiceConfig: {
      name: "CreateServiceConfig",
      I: CreateServiceConfigRequest,
      O: Service,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new service configuration (version) for a managed service based
     * on
     * user-supplied configuration source files (for example: OpenAPI
     * Specification). This method stores the source configurations as well as the
     * generated service configuration. To rollout the service configuration to
     * other services,
     * please call
     * [CreateServiceRollout][google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout].
     *
     * Only the 100 most recent configuration sources and ones referenced by
     * existing service configurtions are kept for each service. The rest will be
     * deleted eventually.
     *
     * Operation<response: SubmitConfigSourceResponse>
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.SubmitConfigSource
     */
    submitConfigSource: {
      name: "SubmitConfigSource",
      I: SubmitConfigSourceRequest,
      O: Operation,
      kind: MethodKind.Unary,
    },
    /**
     * Lists the history of the service configuration rollouts for a managed
     * service, from the newest to the oldest.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.ListServiceRollouts
     */
    listServiceRollouts: {
      name: "ListServiceRollouts",
      I: ListServiceRolloutsRequest,
      O: ListServiceRolloutsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets a service configuration
     * [rollout][google.api.servicemanagement.v1.Rollout].
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.GetServiceRollout
     */
    getServiceRollout: {
      name: "GetServiceRollout",
      I: GetServiceRolloutRequest,
      O: Rollout,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new service configuration rollout. Based on rollout, the
     * Google Service Management will roll out the service configurations to
     * different backend services. For example, the logging configuration will be
     * pushed to Google Cloud Logging.
     *
     * Please note that any previous pending and running Rollouts and associated
     * Operations will be automatically cancelled so that the latest Rollout will
     * not be blocked by previous Rollouts.
     *
     * Only the 100 most recent (in any state) and the last 10 successful (if not
     * already part of the set of 100 most recent) rollouts are kept for each
     * service. The rest will be deleted eventually.
     *
     * Operation<response: Rollout>
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout
     */
    createServiceRollout: {
      name: "CreateServiceRollout",
      I: CreateServiceRolloutRequest,
      O: Operation,
      kind: MethodKind.Unary,
    },
    /**
     * Generates and returns a report (errors, warnings and changes from
     * existing configurations) associated with
     * GenerateConfigReportRequest.new_value
     *
     * If GenerateConfigReportRequest.old_value is specified,
     * GenerateConfigReportRequest will contain a single ChangeReport based on the
     * comparison between GenerateConfigReportRequest.new_value and
     * GenerateConfigReportRequest.old_value.
     * If GenerateConfigReportRequest.old_value is not specified, this method
     * will compare GenerateConfigReportRequest.new_value with the last pushed
     * service configuration.
     *
     * @generated from rpc google.api.servicemanagement.v1.ServiceManager.GenerateConfigReport
     */
    generateConfigReport: {
      name: "GenerateConfigReport",
      I: GenerateConfigReportRequest,
      O: GenerateConfigReportResponse,
      kind: MethodKind.Unary,
    },
  }
};
