// Older protoc compilers don't understand edition yet.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file lf/a2a/v1/a2a.proto (package lf.a2a.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";
import type { Timestamp } from "../../../google/protobuf/timestamp_pb";
import type { Value } from "../../../google/protobuf/struct_pb";
import type { EmptySchema } from "../../../google/protobuf/empty_pb";

/**
 * Describes the file lf/a2a/v1/a2a.proto.
 */
export declare const file_lf_a2a_v1_a2a: GenFile;

/**
 * Configuration of a send message request.
 *
 * @generated from message lf.a2a.v1.SendMessageConfiguration
 */
export declare type SendMessageConfiguration = Message$1<"lf.a2a.v1.SendMessageConfiguration"> & {
  /**
   * A list of media types the client is prepared to accept for response parts.
   * Agents SHOULD use this to tailor their output.
   *
   * @generated from field: repeated string accepted_output_modes = 1;
   */
  acceptedOutputModes: string[];

  /**
   * Configuration for the agent to send push notifications for task updates.
   * Task id should be empty when sending this configuration in a `SendMessage` request.
   *
   * @generated from field: lf.a2a.v1.TaskPushNotificationConfig task_push_notification_config = 2;
   */
  taskPushNotificationConfig?: TaskPushNotificationConfig;

  /**
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   *
   * @generated from field: optional int32 history_length = 3;
   */
  historyLength?: number;

  /**
   * If `true`, the operation returns immediately after creating the task,
   * even if processing is still in progress.
   * If `false` (default), the operation MUST wait until the task reaches a
   * terminal (`COMPLETED`, `FAILED`, `CANCELED`, `REJECTED`) or interrupted
   * (`INPUT_REQUIRED`, `AUTH_REQUIRED`) state before returning.
   *
   * @generated from field: bool return_immediately = 4;
   */
  returnImmediately: boolean;
};

/**
 * Describes the message lf.a2a.v1.SendMessageConfiguration.
 * Use `create(SendMessageConfigurationSchema)` to create a new message.
 */
export declare const SendMessageConfigurationSchema: GenMessage<SendMessageConfiguration>;

/**
 * `Task` is the core unit of action for A2A. It has a current status
 * and when results are created for the task they are stored in the
 * artifact. If there are multiple turns for a task, these are stored in
 * history.
 *
 * @generated from message lf.a2a.v1.Task
 */
export declare type Task = Message$1<"lf.a2a.v1.Task"> & {
  /**
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages).
   *
   * @generated from field: string context_id = 2;
   */
  contextId: string;

  /**
   * The current status of a `Task`, including `state` and a `message`.
   *
   * @generated from field: lf.a2a.v1.TaskStatus status = 3;
   */
  status?: TaskStatus;

  /**
   * A set of output artifacts for a `Task`.
   *
   * @generated from field: repeated lf.a2a.v1.Artifact artifacts = 4;
   */
  artifacts: Artifact[];

  /**
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   *
   * @generated from field: repeated lf.a2a.v1.Message history = 5;
   */
  history: Message[];

  /**
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   *
   * @generated from field: google.protobuf.Struct metadata = 6;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.Task.
 * Use `create(TaskSchema)` to create a new message.
 */
export declare const TaskSchema: GenMessage<Task>;

/**
 * A container for the status of a task
 *
 * @generated from message lf.a2a.v1.TaskStatus
 */
export declare type TaskStatus = Message$1<"lf.a2a.v1.TaskStatus"> & {
  /**
   * The current state of this task.
   *
   * @generated from field: lf.a2a.v1.TaskState state = 1;
   */
  state: TaskState;

  /**
   * A message associated with the status.
   *
   * @generated from field: lf.a2a.v1.Message message = 2;
   */
  message?: Message;

  /**
   * ISO 8601 Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;
};

/**
 * Describes the message lf.a2a.v1.TaskStatus.
 * Use `create(TaskStatusSchema)` to create a new message.
 */
export declare const TaskStatusSchema: GenMessage<TaskStatus>;

/**
 * `Part` represents a container for a section of communication content.
 * Parts can be purely textual, some sort of file (image, video, etc) or
 * a structured data blob (i.e. JSON).
 *
 * @generated from message lf.a2a.v1.Part
 */
export declare type Part = Message$1<"lf.a2a.v1.Part"> & {
  /**
   * @generated from oneof lf.a2a.v1.Part.content
   */
  content: {
    /**
     * The string content of the `text` part.
     *
     * @generated from field: string text = 1;
     */
    value: string;
    case: "text";
  } | {
    /**
     * The `raw` byte content of a file. In JSON serialization, this is encoded as a base64 string.
     *
     * @generated from field: bytes raw = 2;
     */
    value: Uint8Array;
    case: "raw";
  } | {
    /**
     * A `url` pointing to the file's content.
     *
     * @generated from field: string url = 3;
     */
    value: string;
    case: "url";
  } | {
    /**
     * Arbitrary structured `data` as a JSON value (object, array, string, number, boolean, or null).
     *
     * @generated from field: google.protobuf.Value data = 4;
     */
    value: Value;
    case: "data";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. metadata associated with this part.
   *
   * @generated from field: google.protobuf.Struct metadata = 5;
   */
  metadata?: JsonObject;

  /**
   * An optional `filename` for the file (e.g., "document.pdf").
   *
   * @generated from field: string filename = 6;
   */
  filename: string;

  /**
   * The `media_type` (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
   * This field is available for all part types.
   *
   * @generated from field: string media_type = 7;
   */
  mediaType: string;
};

/**
 * Describes the message lf.a2a.v1.Part.
 * Use `create(PartSchema)` to create a new message.
 */
export declare const PartSchema: GenMessage<Part>;

/**
 * `Message` is one unit of communication between client and server. It can be
 * associated with a context and/or a task. For server messages, `context_id` must
 * be provided, and `task_id` only if a task was created. For client messages, both
 * fields are optional, with the caveat that if both are provided, they have to
 * match (the `context_id` has to be the one that is set on the task). If only
 * `task_id` is provided, the server will infer `context_id` from it.
 *
 * @generated from message lf.a2a.v1.Message
 */
export declare type Message = Message$1<"lf.a2a.v1.Message"> & {
  /**
   * The unique identifier (e.g. UUID) of the message. This is created by the message creator.
   *
   * @generated from field: string message_id = 1;
   */
  messageId: string;

  /**
   * Optional. The context id of the message. If set, the message will be associated with the given context.
   *
   * @generated from field: string context_id = 2;
   */
  contextId: string;

  /**
   * Optional. The task id of the message. If set, the message will be associated with the given task.
   *
   * @generated from field: string task_id = 3;
   */
  taskId: string;

  /**
   * Identifies the sender of the message.
   *
   * @generated from field: lf.a2a.v1.Role role = 4;
   */
  role: Role;

  /**
   * Parts is the container of the message content.
   *
   * @generated from field: repeated lf.a2a.v1.Part parts = 5;
   */
  parts: Part[];

  /**
   * Optional. Any metadata to provide along with the message.
   *
   * @generated from field: google.protobuf.Struct metadata = 6;
   */
  metadata?: JsonObject;

  /**
   * The URIs of extensions that are present or contributed to this Message.
   *
   * @generated from field: repeated string extensions = 7;
   */
  extensions: string[];

  /**
   * A list of task IDs that this message references for additional context.
   *
   * @generated from field: repeated string reference_task_ids = 8;
   */
  referenceTaskIds: string[];
};

/**
 * Describes the message lf.a2a.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * Artifacts represent task outputs.
 *
 * @generated from message lf.a2a.v1.Artifact
 */
export declare type Artifact = Message$1<"lf.a2a.v1.Artifact"> & {
  /**
   * Unique identifier (e.g. UUID) for the artifact. It must be unique within a task.
   *
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;

  /**
   * A human readable name for the artifact.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Optional. A human readable description of the artifact.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * The content of the artifact. Must contain at least one part.
   *
   * @generated from field: repeated lf.a2a.v1.Part parts = 4;
   */
  parts: Part[];

  /**
   * Optional. Metadata included with the artifact.
   *
   * @generated from field: google.protobuf.Struct metadata = 5;
   */
  metadata?: JsonObject;

  /**
   * The URIs of extensions that are present or contributed to this Artifact.
   *
   * @generated from field: repeated string extensions = 6;
   */
  extensions: string[];
};

/**
 * Describes the message lf.a2a.v1.Artifact.
 * Use `create(ArtifactSchema)` to create a new message.
 */
export declare const ArtifactSchema: GenMessage<Artifact>;

/**
 * An event sent by the agent to notify the client of a change in a task's status.
 *
 * @generated from message lf.a2a.v1.TaskStatusUpdateEvent
 */
export declare type TaskStatusUpdateEvent = Message$1<"lf.a2a.v1.TaskStatusUpdateEvent"> & {
  /**
   * The ID of the task that has changed.
   *
   * @generated from field: string task_id = 1;
   */
  taskId: string;

  /**
   * The ID of the context that the task belongs to.
   *
   * @generated from field: string context_id = 2;
   */
  contextId: string;

  /**
   * The new status of the task.
   *
   * @generated from field: lf.a2a.v1.TaskStatus status = 3;
   */
  status?: TaskStatus;

  /**
   * Optional. Metadata associated with the task update.
   *
   * @generated from field: google.protobuf.Struct metadata = 4;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.TaskStatusUpdateEvent.
 * Use `create(TaskStatusUpdateEventSchema)` to create a new message.
 */
export declare const TaskStatusUpdateEventSchema: GenMessage<TaskStatusUpdateEvent>;

/**
 * A task delta where an artifact has been generated.
 *
 * @generated from message lf.a2a.v1.TaskArtifactUpdateEvent
 */
export declare type TaskArtifactUpdateEvent = Message$1<"lf.a2a.v1.TaskArtifactUpdateEvent"> & {
  /**
   * The ID of the task for this artifact.
   *
   * @generated from field: string task_id = 1;
   */
  taskId: string;

  /**
   * The ID of the context that this task belongs to.
   *
   * @generated from field: string context_id = 2;
   */
  contextId: string;

  /**
   * The artifact that was generated or updated.
   *
   * @generated from field: lf.a2a.v1.Artifact artifact = 3;
   */
  artifact?: Artifact;

  /**
   * If true, the content of this artifact should be appended to a previously
   * sent artifact with the same ID.
   *
   * @generated from field: bool append = 4;
   */
  append: boolean;

  /**
   * If true, this is the final chunk of the artifact.
   *
   * @generated from field: bool last_chunk = 5;
   */
  lastChunk: boolean;

  /**
   * Optional. Metadata associated with the artifact update.
   *
   * @generated from field: google.protobuf.Struct metadata = 6;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.TaskArtifactUpdateEvent.
 * Use `create(TaskArtifactUpdateEventSchema)` to create a new message.
 */
export declare const TaskArtifactUpdateEventSchema: GenMessage<TaskArtifactUpdateEvent>;

/**
 * Defines authentication details, used for push notifications.
 *
 * @generated from message lf.a2a.v1.AuthenticationInfo
 */
export declare type AuthenticationInfo = Message$1<"lf.a2a.v1.AuthenticationInfo"> & {
  /**
   * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
   * Examples: `Bearer`, `Basic`, `Digest`.
   * Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
   *
   * @generated from field: string scheme = 1;
   */
  scheme: string;

  /**
   * Push Notification credentials. Format depends on the scheme (e.g., token for Bearer).
   *
   * @generated from field: string credentials = 2;
   */
  credentials: string;
};

/**
 * Describes the message lf.a2a.v1.AuthenticationInfo.
 * Use `create(AuthenticationInfoSchema)` to create a new message.
 */
export declare const AuthenticationInfoSchema: GenMessage<AuthenticationInfo>;

/**
 * Declares a combination of a target URL, transport and protocol version for interacting with the agent.
 * This allows agents to expose the same functionality over multiple protocol binding mechanisms.
 *
 * @generated from message lf.a2a.v1.AgentInterface
 */
export declare type AgentInterface = Message$1<"lf.a2a.v1.AgentInterface"> & {
  /**
   * The URL where this interface is available. Must be a valid absolute HTTPS URL in production.
   * Example: "https://api.example.com/a2a/v1", "https://grpc.example.com/a2a"
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * The protocol binding supported at this URL. This is an open form string, to be
   * easily extended for other protocol bindings. The core ones officially
   * supported are `JSONRPC`, `GRPC` and `HTTP+JSON`.
   *
   * @generated from field: string protocol_binding = 2;
   */
  protocolBinding: string;

  /**
   * Tenant ID to be used in the request when calling the agent.
   *
   * @generated from field: string tenant = 3;
   */
  tenant: string;

  /**
   * The version of the A2A protocol this interface exposes.
   * Use the latest supported minor version per major version.
   * Examples: "0.3", "1.0"
   *
   * @generated from field: string protocol_version = 4;
   */
  protocolVersion: string;
};

/**
 * Describes the message lf.a2a.v1.AgentInterface.
 * Use `create(AgentInterfaceSchema)` to create a new message.
 */
export declare const AgentInterfaceSchema: GenMessage<AgentInterface>;

/**
 * A self-describing manifest for an agent. It provides essential
 * metadata including the agent's identity, capabilities, skills, supported
 * communication methods, and security requirements.
 * Next ID: 20
 *
 * @generated from message lf.a2a.v1.AgentCard
 */
export declare type AgentCard = Message$1<"lf.a2a.v1.AgentCard"> & {
  /**
   * A human readable name for the agent.
   * Example: "Recipe Agent"
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * A human-readable description of the agent, assisting users and other agents
   * in understanding its purpose.
   * Example: "Agent that helps users with recipes and cooking."
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Ordered list of supported interfaces. The first entry is preferred.
   *
   * @generated from field: repeated lf.a2a.v1.AgentInterface supported_interfaces = 3;
   */
  supportedInterfaces: AgentInterface[];

  /**
   * The service provider of the agent.
   *
   * @generated from field: lf.a2a.v1.AgentProvider provider = 4;
   */
  provider?: AgentProvider;

  /**
   * The version of the agent.
   * Example: "1.0.0"
   *
   * @generated from field: string version = 5;
   */
  version: string;

  /**
   * A URL providing additional documentation about the agent.
   *
   * @generated from field: optional string documentation_url = 6;
   */
  documentationUrl?: string;

  /**
   * A2A Capability set supported by the agent.
   *
   * @generated from field: lf.a2a.v1.AgentCapabilities capabilities = 7;
   */
  capabilities?: AgentCapabilities;

  /**
   * The security scheme details used for authenticating with this agent.
   *
   * @generated from field: map<string, lf.a2a.v1.SecurityScheme> security_schemes = 8;
   */
  securitySchemes: { [key: string]: SecurityScheme };

  /**
   * Security requirements for contacting the agent.
   *
   * @generated from field: repeated lf.a2a.v1.SecurityRequirement security_requirements = 9;
   */
  securityRequirements: SecurityRequirement[];

  /**
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * The set of interaction modes that the agent supports across all skills.
   * This can be overridden per skill. Defined as media types.
   *
   * @generated from field: repeated string default_input_modes = 10;
   */
  defaultInputModes: string[];

  /**
   * The media types supported as outputs from this agent.
   *
   * @generated from field: repeated string default_output_modes = 11;
   */
  defaultOutputModes: string[];

  /**
   * Skills represent the abilities of an agent.
   * It is largely a descriptive concept but represents a more focused set of behaviors that the
   * agent is likely to succeed at.
   *
   * @generated from field: repeated lf.a2a.v1.AgentSkill skills = 12;
   */
  skills: AgentSkill[];

  /**
   * JSON Web Signatures computed for this `AgentCard`.
   *
   * @generated from field: repeated lf.a2a.v1.AgentCardSignature signatures = 13;
   */
  signatures: AgentCardSignature[];

  /**
   * Optional. A URL to an icon for the agent.
   *
   * @generated from field: optional string icon_url = 14;
   */
  iconUrl?: string;
};

/**
 * Describes the message lf.a2a.v1.AgentCard.
 * Use `create(AgentCardSchema)` to create a new message.
 */
export declare const AgentCardSchema: GenMessage<AgentCard>;

/**
 * Represents the service provider of an agent.
 *
 * @generated from message lf.a2a.v1.AgentProvider
 */
export declare type AgentProvider = Message$1<"lf.a2a.v1.AgentProvider"> & {
  /**
   * A URL for the agent provider's website or relevant documentation.
   * Example: "https://ai.google.dev"
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * The name of the agent provider's organization.
   * Example: "Google"
   *
   * @generated from field: string organization = 2;
   */
  organization: string;
};

/**
 * Describes the message lf.a2a.v1.AgentProvider.
 * Use `create(AgentProviderSchema)` to create a new message.
 */
export declare const AgentProviderSchema: GenMessage<AgentProvider>;

/**
 * Defines optional capabilities supported by an agent.
 *
 * @generated from message lf.a2a.v1.AgentCapabilities
 */
export declare type AgentCapabilities = Message$1<"lf.a2a.v1.AgentCapabilities"> & {
  /**
   * Indicates if the agent supports streaming responses.
   *
   * @generated from field: optional bool streaming = 1;
   */
  streaming?: boolean;

  /**
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   *
   * @generated from field: optional bool push_notifications = 2;
   */
  pushNotifications?: boolean;

  /**
   * A list of protocol extensions supported by the agent.
   *
   * @generated from field: repeated lf.a2a.v1.AgentExtension extensions = 3;
   */
  extensions: AgentExtension[];

  /**
   * Indicates if the agent supports providing an extended agent card when authenticated.
   *
   * @generated from field: optional bool extended_agent_card = 4;
   */
  extendedAgentCard?: boolean;
};

/**
 * Describes the message lf.a2a.v1.AgentCapabilities.
 * Use `create(AgentCapabilitiesSchema)` to create a new message.
 */
export declare const AgentCapabilitiesSchema: GenMessage<AgentCapabilities>;

/**
 * A declaration of a protocol extension supported by an Agent.
 *
 * @generated from message lf.a2a.v1.AgentExtension
 */
export declare type AgentExtension = Message$1<"lf.a2a.v1.AgentExtension"> & {
  /**
   * The unique URI identifying the extension.
   *
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * A human-readable description of how this agent uses the extension.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * If true, the client must understand and comply with the extension's requirements.
   *
   * @generated from field: bool required = 3;
   */
  required: boolean;

  /**
   * Optional. Extension-specific configuration parameters.
   *
   * @generated from field: google.protobuf.Struct params = 4;
   */
  params?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.AgentExtension.
 * Use `create(AgentExtensionSchema)` to create a new message.
 */
export declare const AgentExtensionSchema: GenMessage<AgentExtension>;

/**
 * Represents a distinct capability or function that an agent can perform.
 *
 * @generated from message lf.a2a.v1.AgentSkill
 */
export declare type AgentSkill = Message$1<"lf.a2a.v1.AgentSkill"> & {
  /**
   * A unique identifier for the agent's skill.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * A human-readable name for the skill.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * A detailed description of the skill.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * A set of keywords describing the skill's capabilities.
   *
   * @generated from field: repeated string tags = 4;
   */
  tags: string[];

  /**
   * Example prompts or scenarios that this skill can handle.
   *
   * @generated from field: repeated string examples = 5;
   */
  examples: string[];

  /**
   * The set of supported input media types for this skill, overriding the agent's defaults.
   *
   * @generated from field: repeated string input_modes = 6;
   */
  inputModes: string[];

  /**
   * The set of supported output media types for this skill, overriding the agent's defaults.
   *
   * @generated from field: repeated string output_modes = 7;
   */
  outputModes: string[];

  /**
   * Security schemes necessary for this skill.
   *
   * @generated from field: repeated lf.a2a.v1.SecurityRequirement security_requirements = 8;
   */
  securityRequirements: SecurityRequirement[];
};

/**
 * Describes the message lf.a2a.v1.AgentSkill.
 * Use `create(AgentSkillSchema)` to create a new message.
 */
export declare const AgentSkillSchema: GenMessage<AgentSkill>;

/**
 * AgentCardSignature represents a JWS signature of an AgentCard.
 * This follows the JSON format of an RFC 7515 JSON Web Signature (JWS).
 *
 * @generated from message lf.a2a.v1.AgentCardSignature
 */
export declare type AgentCardSignature = Message$1<"lf.a2a.v1.AgentCardSignature"> & {
  /**
   * (-- api-linter: core::0140::reserved-words=disabled
   *     aip.dev/not-precedent: Backwards compatibility --)
   * Required. The protected JWS header for the signature. This is always a
   * base64url-encoded JSON object.
   *
   * @generated from field: string protected = 1;
   */
  protected: string;

  /**
   * Required. The computed signature, base64url-encoded.
   *
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * The unprotected JWS header values.
   *
   * @generated from field: google.protobuf.Struct header = 3;
   */
  header?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.AgentCardSignature.
 * Use `create(AgentCardSignatureSchema)` to create a new message.
 */
export declare const AgentCardSignatureSchema: GenMessage<AgentCardSignature>;

/**
 * A container associating a push notification configuration with a specific task.
 *
 * @generated from message lf.a2a.v1.TaskPushNotificationConfig
 */
export declare type TaskPushNotificationConfig = Message$1<"lf.a2a.v1.TaskPushNotificationConfig"> & {
  /**
   * Optional. Tenant ID.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The push notification configuration details.
   * A unique identifier (e.g. UUID) for this push notification configuration.
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * The ID of the task this configuration is associated with.
   *
   * @generated from field: string task_id = 3;
   */
  taskId: string;

  /**
   * The URL where the notification should be sent.
   *
   * @generated from field: string url = 4;
   */
  url: string;

  /**
   * A token unique for this task or session.
   *
   * @generated from field: string token = 5;
   */
  token: string;

  /**
   * Authentication information required to send the notification.
   *
   * @generated from field: lf.a2a.v1.AuthenticationInfo authentication = 6;
   */
  authentication?: AuthenticationInfo;
};

/**
 * Describes the message lf.a2a.v1.TaskPushNotificationConfig.
 * Use `create(TaskPushNotificationConfigSchema)` to create a new message.
 */
export declare const TaskPushNotificationConfigSchema: GenMessage<TaskPushNotificationConfig>;

/**
 * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
 * A list of strings.
 *
 * @generated from message lf.a2a.v1.StringList
 */
export declare type StringList = Message$1<"lf.a2a.v1.StringList"> & {
  /**
   * The individual string values.
   *
   * @generated from field: repeated string list = 1;
   */
  list: string[];
};

/**
 * Describes the message lf.a2a.v1.StringList.
 * Use `create(StringListSchema)` to create a new message.
 */
export declare const StringListSchema: GenMessage<StringList>;

/**
 * Defines the security requirements for an agent.
 *
 * @generated from message lf.a2a.v1.SecurityRequirement
 */
export declare type SecurityRequirement = Message$1<"lf.a2a.v1.SecurityRequirement"> & {
  /**
   * A map of security schemes to the required scopes.
   *
   * @generated from field: map<string, lf.a2a.v1.StringList> schemes = 1;
   */
  schemes: { [key: string]: StringList };
};

/**
 * Describes the message lf.a2a.v1.SecurityRequirement.
 * Use `create(SecurityRequirementSchema)` to create a new message.
 */
export declare const SecurityRequirementSchema: GenMessage<SecurityRequirement>;

/**
 * Defines a security scheme that can be used to secure an agent's endpoints.
 * This is a discriminated union type based on the OpenAPI 3.2 Security Scheme Object.
 * See: https://spec.openapis.org/oas/v3.2.0.html#security-scheme-object
 *
 * @generated from message lf.a2a.v1.SecurityScheme
 */
export declare type SecurityScheme = Message$1<"lf.a2a.v1.SecurityScheme"> & {
  /**
   * @generated from oneof lf.a2a.v1.SecurityScheme.scheme
   */
  scheme: {
    /**
     * API key-based authentication.
     *
     * @generated from field: lf.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1;
     */
    value: APIKeySecurityScheme;
    case: "apiKeySecurityScheme";
  } | {
    /**
     * HTTP authentication (Basic, Bearer, etc.).
     *
     * @generated from field: lf.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2;
     */
    value: HTTPAuthSecurityScheme;
    case: "httpAuthSecurityScheme";
  } | {
    /**
     * OAuth 2.0 authentication.
     *
     * @generated from field: lf.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3;
     */
    value: OAuth2SecurityScheme;
    case: "oauth2SecurityScheme";
  } | {
    /**
     * OpenID Connect authentication.
     *
     * @generated from field: lf.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4;
     */
    value: OpenIdConnectSecurityScheme;
    case: "openIdConnectSecurityScheme";
  } | {
    /**
     * Mutual TLS authentication.
     *
     * @generated from field: lf.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5;
     */
    value: MutualTlsSecurityScheme;
    case: "mtlsSecurityScheme";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message lf.a2a.v1.SecurityScheme.
 * Use `create(SecuritySchemeSchema)` to create a new message.
 */
export declare const SecuritySchemeSchema: GenMessage<SecurityScheme>;

/**
 * Defines a security scheme using an API key.
 *
 * @generated from message lf.a2a.v1.APIKeySecurityScheme
 */
export declare type APIKeySecurityScheme = Message$1<"lf.a2a.v1.APIKeySecurityScheme"> & {
  /**
   * An optional description for the security scheme.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * The location of the API key. Valid values are "query", "header", or "cookie".
   *
   * @generated from field: string location = 2;
   */
  location: string;

  /**
   * The name of the header, query, or cookie parameter to be used.
   *
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message lf.a2a.v1.APIKeySecurityScheme.
 * Use `create(APIKeySecuritySchemeSchema)` to create a new message.
 */
export declare const APIKeySecuritySchemeSchema: GenMessage<APIKeySecurityScheme>;

/**
 * Defines a security scheme using HTTP authentication.
 *
 * @generated from message lf.a2a.v1.HTTPAuthSecurityScheme
 */
export declare type HTTPAuthSecurityScheme = Message$1<"lf.a2a.v1.HTTPAuthSecurityScheme"> & {
  /**
   * An optional description for the security scheme.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * The name of the HTTP Authentication scheme to be used in the Authorization header,
   * as defined in RFC7235 (e.g., "Bearer").
   * This value should be registered in the IANA Authentication Scheme registry.
   *
   * @generated from field: string scheme = 2;
   */
  scheme: string;

  /**
   * A hint to the client to identify how the bearer token is formatted (e.g., "JWT").
   * Primarily for documentation purposes.
   *
   * @generated from field: string bearer_format = 3;
   */
  bearerFormat: string;
};

/**
 * Describes the message lf.a2a.v1.HTTPAuthSecurityScheme.
 * Use `create(HTTPAuthSecuritySchemeSchema)` to create a new message.
 */
export declare const HTTPAuthSecuritySchemeSchema: GenMessage<HTTPAuthSecurityScheme>;

/**
 * Defines a security scheme using OAuth 2.0.
 *
 * @generated from message lf.a2a.v1.OAuth2SecurityScheme
 */
export declare type OAuth2SecurityScheme = Message$1<"lf.a2a.v1.OAuth2SecurityScheme"> & {
  /**
   * An optional description for the security scheme.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * An object containing configuration information for the supported OAuth 2.0 flows.
   *
   * @generated from field: lf.a2a.v1.OAuthFlows flows = 2;
   */
  flows?: OAuthFlows;

  /**
   * URL to the OAuth2 authorization server metadata [RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414).
   * TLS is required.
   *
   * @generated from field: string oauth2_metadata_url = 3;
   */
  oauth2MetadataUrl: string;
};

/**
 * Describes the message lf.a2a.v1.OAuth2SecurityScheme.
 * Use `create(OAuth2SecuritySchemeSchema)` to create a new message.
 */
export declare const OAuth2SecuritySchemeSchema: GenMessage<OAuth2SecurityScheme>;

/**
 * Defines a security scheme using OpenID Connect.
 *
 * @generated from message lf.a2a.v1.OpenIdConnectSecurityScheme
 */
export declare type OpenIdConnectSecurityScheme = Message$1<"lf.a2a.v1.OpenIdConnectSecurityScheme"> & {
  /**
   * An optional description for the security scheme.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * The [OpenID Connect Discovery URL](https://openid.net/specs/openid-connect-discovery-1_0.html) for the OIDC provider's metadata.
   *
   * @generated from field: string open_id_connect_url = 2;
   */
  openIdConnectUrl: string;
};

/**
 * Describes the message lf.a2a.v1.OpenIdConnectSecurityScheme.
 * Use `create(OpenIdConnectSecuritySchemeSchema)` to create a new message.
 */
export declare const OpenIdConnectSecuritySchemeSchema: GenMessage<OpenIdConnectSecurityScheme>;

/**
 * Defines a security scheme using mTLS authentication.
 *
 * @generated from message lf.a2a.v1.MutualTlsSecurityScheme
 */
export declare type MutualTlsSecurityScheme = Message$1<"lf.a2a.v1.MutualTlsSecurityScheme"> & {
  /**
   * An optional description for the security scheme.
   *
   * @generated from field: string description = 1;
   */
  description: string;
};

/**
 * Describes the message lf.a2a.v1.MutualTlsSecurityScheme.
 * Use `create(MutualTlsSecuritySchemeSchema)` to create a new message.
 */
export declare const MutualTlsSecuritySchemeSchema: GenMessage<MutualTlsSecurityScheme>;

/**
 * Defines the configuration for the supported OAuth 2.0 flows.
 *
 * @generated from message lf.a2a.v1.OAuthFlows
 */
export declare type OAuthFlows = Message$1<"lf.a2a.v1.OAuthFlows"> & {
  /**
   * @generated from oneof lf.a2a.v1.OAuthFlows.flow
   */
  flow: {
    /**
     * Configuration for the OAuth Authorization Code flow.
     *
     * @generated from field: lf.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;
     */
    value: AuthorizationCodeOAuthFlow;
    case: "authorizationCode";
  } | {
    /**
     * Configuration for the OAuth Client Credentials flow.
     *
     * @generated from field: lf.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;
     */
    value: ClientCredentialsOAuthFlow;
    case: "clientCredentials";
  } | {
    /**
     * Deprecated: Use Authorization Code + PKCE instead.
     *
     * @generated from field: lf.a2a.v1.ImplicitOAuthFlow implicit = 3 [deprecated = true];
     * @deprecated
     */
    value: ImplicitOAuthFlow;
    case: "implicit";
  } | {
    /**
     * Deprecated: Use Authorization Code + PKCE or Device Code.
     *
     * @generated from field: lf.a2a.v1.PasswordOAuthFlow password = 4 [deprecated = true];
     * @deprecated
     */
    value: PasswordOAuthFlow;
    case: "password";
  } | {
    /**
     * Configuration for the OAuth Device Code flow.
     *
     * @generated from field: lf.a2a.v1.DeviceCodeOAuthFlow device_code = 5;
     */
    value: DeviceCodeOAuthFlow;
    case: "deviceCode";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message lf.a2a.v1.OAuthFlows.
 * Use `create(OAuthFlowsSchema)` to create a new message.
 */
export declare const OAuthFlowsSchema: GenMessage<OAuthFlows>;

/**
 * Defines configuration details for the OAuth 2.0 Authorization Code flow.
 *
 * @generated from message lf.a2a.v1.AuthorizationCodeOAuthFlow
 */
export declare type AuthorizationCodeOAuthFlow = Message$1<"lf.a2a.v1.AuthorizationCodeOAuthFlow"> & {
  /**
   * The authorization URL to be used for this flow.
   *
   * @generated from field: string authorization_url = 1;
   */
  authorizationUrl: string;

  /**
   * The token URL to be used for this flow.
   *
   * @generated from field: string token_url = 2;
   */
  tokenUrl: string;

  /**
   * The URL to be used for obtaining refresh tokens.
   *
   * @generated from field: string refresh_url = 3;
   */
  refreshUrl: string;

  /**
   * The available scopes for the OAuth2 security scheme.
   *
   * @generated from field: map<string, string> scopes = 4;
   */
  scopes: { [key: string]: string };

  /**
   * Indicates if PKCE (RFC 7636) is required for this flow.
   * PKCE should always be used for public clients and is recommended for all clients.
   *
   * @generated from field: bool pkce_required = 5;
   */
  pkceRequired: boolean;
};

/**
 * Describes the message lf.a2a.v1.AuthorizationCodeOAuthFlow.
 * Use `create(AuthorizationCodeOAuthFlowSchema)` to create a new message.
 */
export declare const AuthorizationCodeOAuthFlowSchema: GenMessage<AuthorizationCodeOAuthFlow>;

/**
 * Defines configuration details for the OAuth 2.0 Client Credentials flow.
 *
 * @generated from message lf.a2a.v1.ClientCredentialsOAuthFlow
 */
export declare type ClientCredentialsOAuthFlow = Message$1<"lf.a2a.v1.ClientCredentialsOAuthFlow"> & {
  /**
   * The token URL to be used for this flow.
   *
   * @generated from field: string token_url = 1;
   */
  tokenUrl: string;

  /**
   * The URL to be used for obtaining refresh tokens.
   *
   * @generated from field: string refresh_url = 2;
   */
  refreshUrl: string;

  /**
   * The available scopes for the OAuth2 security scheme.
   *
   * @generated from field: map<string, string> scopes = 3;
   */
  scopes: { [key: string]: string };
};

/**
 * Describes the message lf.a2a.v1.ClientCredentialsOAuthFlow.
 * Use `create(ClientCredentialsOAuthFlowSchema)` to create a new message.
 */
export declare const ClientCredentialsOAuthFlowSchema: GenMessage<ClientCredentialsOAuthFlow>;

/**
 * Deprecated: Use Authorization Code + PKCE instead.
 *
 * @generated from message lf.a2a.v1.ImplicitOAuthFlow
 */
export declare type ImplicitOAuthFlow = Message$1<"lf.a2a.v1.ImplicitOAuthFlow"> & {
  /**
   * The authorization URL to be used for this flow. This MUST be in the
   * form of a URL. The OAuth2 standard requires the use of TLS
   *
   * @generated from field: string authorization_url = 1;
   */
  authorizationUrl: string;

  /**
   * The URL to be used for obtaining refresh tokens. This MUST be in the
   * form of a URL. The OAuth2 standard requires the use of TLS.
   *
   * @generated from field: string refresh_url = 2;
   */
  refreshUrl: string;

  /**
   * The available scopes for the OAuth2 security scheme. A map between the
   * scope name and a short description for it. The map MAY be empty.
   *
   * @generated from field: map<string, string> scopes = 3;
   */
  scopes: { [key: string]: string };
};

/**
 * Describes the message lf.a2a.v1.ImplicitOAuthFlow.
 * Use `create(ImplicitOAuthFlowSchema)` to create a new message.
 */
export declare const ImplicitOAuthFlowSchema: GenMessage<ImplicitOAuthFlow>;

/**
 * Deprecated: Use Authorization Code + PKCE or Device Code.
 *
 * @generated from message lf.a2a.v1.PasswordOAuthFlow
 */
export declare type PasswordOAuthFlow = Message$1<"lf.a2a.v1.PasswordOAuthFlow"> & {
  /**
   * The token URL to be used for this flow. This MUST be in the form of a URL.
   * The OAuth2 standard requires the use of TLS.
   *
   * @generated from field: string token_url = 1;
   */
  tokenUrl: string;

  /**
   * The URL to be used for obtaining refresh tokens. This MUST be in the
   * form of a URL. The OAuth2 standard requires the use of TLS.
   *
   * @generated from field: string refresh_url = 2;
   */
  refreshUrl: string;

  /**
   * The available scopes for the OAuth2 security scheme. A map between the
   * scope name and a short description for it. The map MAY be empty.
   *
   * @generated from field: map<string, string> scopes = 3;
   */
  scopes: { [key: string]: string };
};

/**
 * Describes the message lf.a2a.v1.PasswordOAuthFlow.
 * Use `create(PasswordOAuthFlowSchema)` to create a new message.
 */
export declare const PasswordOAuthFlowSchema: GenMessage<PasswordOAuthFlow>;

/**
 * Defines configuration details for the OAuth 2.0 Device Code flow (RFC 8628).
 * This flow is designed for input-constrained devices such as IoT devices,
 * and CLI tools where the user authenticates on a separate device.
 *
 * @generated from message lf.a2a.v1.DeviceCodeOAuthFlow
 */
export declare type DeviceCodeOAuthFlow = Message$1<"lf.a2a.v1.DeviceCodeOAuthFlow"> & {
  /**
   * The device authorization endpoint URL.
   *
   * @generated from field: string device_authorization_url = 1;
   */
  deviceAuthorizationUrl: string;

  /**
   * The token URL to be used for this flow.
   *
   * @generated from field: string token_url = 2;
   */
  tokenUrl: string;

  /**
   * The URL to be used for obtaining refresh tokens.
   *
   * @generated from field: string refresh_url = 3;
   */
  refreshUrl: string;

  /**
   * The available scopes for the OAuth2 security scheme.
   *
   * @generated from field: map<string, string> scopes = 4;
   */
  scopes: { [key: string]: string };
};

/**
 * Describes the message lf.a2a.v1.DeviceCodeOAuthFlow.
 * Use `create(DeviceCodeOAuthFlowSchema)` to create a new message.
 */
export declare const DeviceCodeOAuthFlowSchema: GenMessage<DeviceCodeOAuthFlow>;

/**
 * Represents a request for the `SendMessage` method.
 *
 * @generated from message lf.a2a.v1.SendMessageRequest
 */
export declare type SendMessageRequest = Message$1<"lf.a2a.v1.SendMessageRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The message to send to the agent.
   *
   * @generated from field: lf.a2a.v1.Message message = 2;
   */
  message?: Message;

  /**
   * Configuration for the send request.
   *
   * @generated from field: lf.a2a.v1.SendMessageConfiguration configuration = 3;
   */
  configuration?: SendMessageConfiguration;

  /**
   * A flexible key-value map for passing additional context or parameters.
   *
   * @generated from field: google.protobuf.Struct metadata = 4;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.SendMessageRequest.
 * Use `create(SendMessageRequestSchema)` to create a new message.
 */
export declare const SendMessageRequestSchema: GenMessage<SendMessageRequest>;

/**
 * Represents a request for the `GetTask` method.
 *
 * @generated from message lf.a2a.v1.GetTaskRequest
 */
export declare type GetTaskRequest = Message$1<"lf.a2a.v1.GetTaskRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The resource ID of the task to retrieve.
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * The maximum number of most recent messages from the task's history to retrieve. An
   * unset value means the client does not impose any limit. A value of zero is
   * a request to not include any messages. The server MUST NOT return more
   * messages than the provided value, but MAY apply a lower limit.
   *
   * @generated from field: optional int32 history_length = 3;
   */
  historyLength?: number;
};

/**
 * Describes the message lf.a2a.v1.GetTaskRequest.
 * Use `create(GetTaskRequestSchema)` to create a new message.
 */
export declare const GetTaskRequestSchema: GenMessage<GetTaskRequest>;

/**
 * Parameters for listing tasks with optional filtering criteria.
 *
 * @generated from message lf.a2a.v1.ListTasksRequest
 */
export declare type ListTasksRequest = Message$1<"lf.a2a.v1.ListTasksRequest"> & {
  /**
   * Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * Filter tasks by context ID to get tasks from a specific conversation or session.
   *
   * @generated from field: string context_id = 2;
   */
  contextId: string;

  /**
   * Filter tasks by their current status state.
   *
   * @generated from field: lf.a2a.v1.TaskState status = 3;
   */
  status: TaskState;

  /**
   * The maximum number of tasks to return. The service may return fewer than this value.
   * If unspecified, at most 50 tasks will be returned.
   * The minimum value is 1.
   * The maximum value is 100.
   *
   * @generated from field: optional int32 page_size = 4;
   */
  pageSize?: number;

  /**
   * A page token, received from a previous `ListTasks` call.
   * `ListTasksResponse.next_page_token`.
   * Provide this to retrieve the subsequent page.
   *
   * @generated from field: string page_token = 5;
   */
  pageToken: string;

  /**
   * The maximum number of messages to include in each task's history.
   *
   * @generated from field: optional int32 history_length = 6;
   */
  historyLength?: number;

  /**
   * Filter tasks which have a status updated after the provided timestamp in ISO 8601 format (e.g., "2023-10-27T10:00:00Z").
   * Only tasks with a status timestamp time greater than or equal to this value will be returned.
   *
   * @generated from field: google.protobuf.Timestamp status_timestamp_after = 7;
   */
  statusTimestampAfter?: Timestamp;

  /**
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   *
   * @generated from field: optional bool include_artifacts = 8;
   */
  includeArtifacts?: boolean;
};

/**
 * Describes the message lf.a2a.v1.ListTasksRequest.
 * Use `create(ListTasksRequestSchema)` to create a new message.
 */
export declare const ListTasksRequestSchema: GenMessage<ListTasksRequest>;

/**
 * Result object for `ListTasks` method containing an array of tasks and pagination information.
 *
 * @generated from message lf.a2a.v1.ListTasksResponse
 */
export declare type ListTasksResponse = Message$1<"lf.a2a.v1.ListTasksResponse"> & {
  /**
   * Array of tasks matching the specified criteria.
   *
   * @generated from field: repeated lf.a2a.v1.Task tasks = 1;
   */
  tasks: Task[];

  /**
   * A token to retrieve the next page of results, or empty if there are no more results in the list.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * The page size used for this response.
   *
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  /**
   * Total number of tasks available (before pagination).
   *
   * @generated from field: int32 total_size = 4;
   */
  totalSize: number;
};

/**
 * Describes the message lf.a2a.v1.ListTasksResponse.
 * Use `create(ListTasksResponseSchema)` to create a new message.
 */
export declare const ListTasksResponseSchema: GenMessage<ListTasksResponse>;

/**
 * Represents a request for the `CancelTask` method.
 *
 * @generated from message lf.a2a.v1.CancelTaskRequest
 */
export declare type CancelTaskRequest = Message$1<"lf.a2a.v1.CancelTaskRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The resource ID of the task to cancel.
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * A flexible key-value map for passing additional context or parameters.
   *
   * @generated from field: google.protobuf.Struct metadata = 3;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message lf.a2a.v1.CancelTaskRequest.
 * Use `create(CancelTaskRequestSchema)` to create a new message.
 */
export declare const CancelTaskRequestSchema: GenMessage<CancelTaskRequest>;

/**
 * Represents a request for the `GetTaskPushNotificationConfig` method.
 *
 * @generated from message lf.a2a.v1.GetTaskPushNotificationConfigRequest
 */
export declare type GetTaskPushNotificationConfigRequest = Message$1<"lf.a2a.v1.GetTaskPushNotificationConfigRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The parent task resource ID.
   *
   * @generated from field: string task_id = 2;
   */
  taskId: string;

  /**
   * The resource ID of the configuration to retrieve.
   *
   * @generated from field: string id = 3;
   */
  id: string;
};

/**
 * Describes the message lf.a2a.v1.GetTaskPushNotificationConfigRequest.
 * Use `create(GetTaskPushNotificationConfigRequestSchema)` to create a new message.
 */
export declare const GetTaskPushNotificationConfigRequestSchema: GenMessage<GetTaskPushNotificationConfigRequest>;

/**
 * Represents a request for the `DeleteTaskPushNotificationConfig` method.
 *
 * @generated from message lf.a2a.v1.DeleteTaskPushNotificationConfigRequest
 */
export declare type DeleteTaskPushNotificationConfigRequest = Message$1<"lf.a2a.v1.DeleteTaskPushNotificationConfigRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The parent task resource ID.
   *
   * @generated from field: string task_id = 2;
   */
  taskId: string;

  /**
   * The resource ID of the configuration to delete.
   *
   * @generated from field: string id = 3;
   */
  id: string;
};

/**
 * Describes the message lf.a2a.v1.DeleteTaskPushNotificationConfigRequest.
 * Use `create(DeleteTaskPushNotificationConfigRequestSchema)` to create a new message.
 */
export declare const DeleteTaskPushNotificationConfigRequestSchema: GenMessage<DeleteTaskPushNotificationConfigRequest>;

/**
 * Represents a request for the `SubscribeToTask` method.
 *
 * @generated from message lf.a2a.v1.SubscribeToTaskRequest
 */
export declare type SubscribeToTaskRequest = Message$1<"lf.a2a.v1.SubscribeToTaskRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * The resource ID of the task to subscribe to.
   *
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message lf.a2a.v1.SubscribeToTaskRequest.
 * Use `create(SubscribeToTaskRequestSchema)` to create a new message.
 */
export declare const SubscribeToTaskRequestSchema: GenMessage<SubscribeToTaskRequest>;

/**
 * Represents a request for the `ListTaskPushNotificationConfigs` method.
 *
 * @generated from message lf.a2a.v1.ListTaskPushNotificationConfigsRequest
 */
export declare type ListTaskPushNotificationConfigsRequest = Message$1<"lf.a2a.v1.ListTaskPushNotificationConfigsRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 4;
   */
  tenant: string;

  /**
   * The parent task resource ID.
   *
   * @generated from field: string task_id = 1;
   */
  taskId: string;

  /**
   * The maximum number of configurations to return.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token received from a previous `ListTaskPushNotificationConfigsRequest` call.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;
};

/**
 * Describes the message lf.a2a.v1.ListTaskPushNotificationConfigsRequest.
 * Use `create(ListTaskPushNotificationConfigsRequestSchema)` to create a new message.
 */
export declare const ListTaskPushNotificationConfigsRequestSchema: GenMessage<ListTaskPushNotificationConfigsRequest>;

/**
 * Represents a request for the `GetExtendedAgentCard` method.
 *
 * @generated from message lf.a2a.v1.GetExtendedAgentCardRequest
 */
export declare type GetExtendedAgentCardRequest = Message$1<"lf.a2a.v1.GetExtendedAgentCardRequest"> & {
  /**
   * Optional. Tenant ID, provided as a path parameter.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;
};

/**
 * Describes the message lf.a2a.v1.GetExtendedAgentCardRequest.
 * Use `create(GetExtendedAgentCardRequestSchema)` to create a new message.
 */
export declare const GetExtendedAgentCardRequestSchema: GenMessage<GetExtendedAgentCardRequest>;

/**
 * Represents the response for the `SendMessage` method.
 *
 * @generated from message lf.a2a.v1.SendMessageResponse
 */
export declare type SendMessageResponse = Message$1<"lf.a2a.v1.SendMessageResponse"> & {
  /**
   * The payload of the response.
   *
   * @generated from oneof lf.a2a.v1.SendMessageResponse.payload
   */
  payload: {
    /**
     * The task created or updated by the message.
     *
     * @generated from field: lf.a2a.v1.Task task = 1;
     */
    value: Task;
    case: "task";
  } | {
    /**
     * A message from the agent.
     *
     * @generated from field: lf.a2a.v1.Message message = 2;
     */
    value: Message;
    case: "message";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message lf.a2a.v1.SendMessageResponse.
 * Use `create(SendMessageResponseSchema)` to create a new message.
 */
export declare const SendMessageResponseSchema: GenMessage<SendMessageResponse>;

/**
 * A wrapper object used in streaming operations to encapsulate different types of response data.
 *
 * @generated from message lf.a2a.v1.StreamResponse
 */
export declare type StreamResponse = Message$1<"lf.a2a.v1.StreamResponse"> & {
  /**
   * The payload of the stream response.
   *
   * @generated from oneof lf.a2a.v1.StreamResponse.payload
   */
  payload: {
    /**
     * A Task object containing the current state of the task.
     *
     * @generated from field: lf.a2a.v1.Task task = 1;
     */
    value: Task;
    case: "task";
  } | {
    /**
     * A Message object containing a message from the agent.
     *
     * @generated from field: lf.a2a.v1.Message message = 2;
     */
    value: Message;
    case: "message";
  } | {
    /**
     * An event indicating a task status update.
     *
     * @generated from field: lf.a2a.v1.TaskStatusUpdateEvent status_update = 3;
     */
    value: TaskStatusUpdateEvent;
    case: "statusUpdate";
  } | {
    /**
     * An event indicating a task artifact update.
     *
     * @generated from field: lf.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;
     */
    value: TaskArtifactUpdateEvent;
    case: "artifactUpdate";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message lf.a2a.v1.StreamResponse.
 * Use `create(StreamResponseSchema)` to create a new message.
 */
export declare const StreamResponseSchema: GenMessage<StreamResponse>;

/**
 * Represents a successful response for the `ListTaskPushNotificationConfigs`
 * method.
 *
 * @generated from message lf.a2a.v1.ListTaskPushNotificationConfigsResponse
 */
export declare type ListTaskPushNotificationConfigsResponse = Message$1<"lf.a2a.v1.ListTaskPushNotificationConfigsResponse"> & {
  /**
   * The list of push notification configurations.
   *
   * @generated from field: repeated lf.a2a.v1.TaskPushNotificationConfig configs = 1;
   */
  configs: TaskPushNotificationConfig[];

  /**
   * A token to retrieve the next page of results, or empty if there are no more results in the list.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message lf.a2a.v1.ListTaskPushNotificationConfigsResponse.
 * Use `create(ListTaskPushNotificationConfigsResponseSchema)` to create a new message.
 */
export declare const ListTaskPushNotificationConfigsResponseSchema: GenMessage<ListTaskPushNotificationConfigsResponse>;

/**
 * Defines the possible lifecycle states of a `Task`.
 *
 * @generated from enum lf.a2a.v1.TaskState
 */
export enum TaskState {
  /**
   * The task is in an unknown or indeterminate state.
   *
   * @generated from enum value: TASK_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Indicates that a task has been successfully submitted and acknowledged.
   *
   * @generated from enum value: TASK_STATE_SUBMITTED = 1;
   */
  SUBMITTED = 1,

  /**
   * Indicates that a task is actively being processed by the agent.
   *
   * @generated from enum value: TASK_STATE_WORKING = 2;
   */
  WORKING = 2,

  /**
   * Indicates that a task has finished successfully. This is a terminal state.
   *
   * @generated from enum value: TASK_STATE_COMPLETED = 3;
   */
  COMPLETED = 3,

  /**
   * Indicates that a task has finished with an error. This is a terminal state.
   *
   * @generated from enum value: TASK_STATE_FAILED = 4;
   */
  FAILED = 4,

  /**
   * Indicates that a task was canceled before completion. This is a terminal state.
   *
   * @generated from enum value: TASK_STATE_CANCELED = 5;
   */
  CANCELED = 5,

  /**
   * Indicates that the agent requires additional user input to proceed. This is an interrupted state.
   *
   * @generated from enum value: TASK_STATE_INPUT_REQUIRED = 6;
   */
  INPUT_REQUIRED = 6,

  /**
   * Indicates that the agent has decided to not perform the task.
   * This may be done during initial task creation or later once an agent
   * has determined it can't or won't proceed. This is a terminal state.
   *
   * @generated from enum value: TASK_STATE_REJECTED = 7;
   */
  REJECTED = 7,

  /**
   * Indicates that authentication is required to proceed. This is an interrupted state.
   *
   * @generated from enum value: TASK_STATE_AUTH_REQUIRED = 8;
   */
  AUTH_REQUIRED = 8,
}

/**
 * Describes the enum lf.a2a.v1.TaskState.
 */
export declare const TaskStateSchema: GenEnum<TaskState>;

/**
 * Defines the sender of a message in A2A protocol communication.
 *
 * @generated from enum lf.a2a.v1.Role
 */
export enum Role {
  /**
   * The role is unspecified.
   *
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The message is from the client to the server.
   *
   * @generated from enum value: ROLE_USER = 1;
   */
  USER = 1,

  /**
   * The message is from the server to the client.
   *
   * @generated from enum value: ROLE_AGENT = 2;
   */
  AGENT = 2,
}

/**
 * Describes the enum lf.a2a.v1.Role.
 */
export declare const RoleSchema: GenEnum<Role>;

/**
 * Provides operations for interacting with agents using the A2A protocol.
 *
 * @generated from service lf.a2a.v1.A2AService
 */
export declare const A2AService: GenService<{
  /**
   * Sends a message to an agent.
   *
   * @generated from rpc lf.a2a.v1.A2AService.SendMessage
   */
  sendMessage: {
    methodKind: "unary";
    input: typeof SendMessageRequestSchema;
    output: typeof SendMessageResponseSchema;
  },
  /**
   * Sends a streaming message to an agent, allowing for real-time interaction and status updates.
   * Streaming version of `SendMessage`
   *
   * @generated from rpc lf.a2a.v1.A2AService.SendStreamingMessage
   */
  sendStreamingMessage: {
    methodKind: "server_streaming";
    input: typeof SendMessageRequestSchema;
    output: typeof StreamResponseSchema;
  },
  /**
   * Gets the latest state of a task.
   *
   * @generated from rpc lf.a2a.v1.A2AService.GetTask
   */
  getTask: {
    methodKind: "unary";
    input: typeof GetTaskRequestSchema;
    output: typeof TaskSchema;
  },
  /**
   * Lists tasks that match the specified filter.
   *
   * @generated from rpc lf.a2a.v1.A2AService.ListTasks
   */
  listTasks: {
    methodKind: "unary";
    input: typeof ListTasksRequestSchema;
    output: typeof ListTasksResponseSchema;
  },
  /**
   * Cancels a task in progress.
   *
   * @generated from rpc lf.a2a.v1.A2AService.CancelTask
   */
  cancelTask: {
    methodKind: "unary";
    input: typeof CancelTaskRequestSchema;
    output: typeof TaskSchema;
  },
  /**
   * Subscribes to task updates for tasks not in a terminal state.
   * Returns `UnsupportedOperationError` if the task is already in a terminal state (completed, failed, canceled, rejected).
   *
   * @generated from rpc lf.a2a.v1.A2AService.SubscribeToTask
   */
  subscribeToTask: {
    methodKind: "server_streaming";
    input: typeof SubscribeToTaskRequestSchema;
    output: typeof StreamResponseSchema;
  },
  /**
   * (-- api-linter: client-libraries::4232::required-fields=disabled
   *     api-linter: core::0133::method-signature=disabled
   *     api-linter: core::0133::request-message-name=disabled
   *     aip.dev/not-precedent: method_signature preserved for backwards compatibility --)
   * Creates a push notification config for a task.
   *
   * @generated from rpc lf.a2a.v1.A2AService.CreateTaskPushNotificationConfig
   */
  createTaskPushNotificationConfig: {
    methodKind: "unary";
    input: typeof TaskPushNotificationConfigSchema;
    output: typeof TaskPushNotificationConfigSchema;
  },
  /**
   * Gets a push notification config for a task.
   *
   * @generated from rpc lf.a2a.v1.A2AService.GetTaskPushNotificationConfig
   */
  getTaskPushNotificationConfig: {
    methodKind: "unary";
    input: typeof GetTaskPushNotificationConfigRequestSchema;
    output: typeof TaskPushNotificationConfigSchema;
  },
  /**
   * Get a list of push notifications configured for a task.
   *
   * @generated from rpc lf.a2a.v1.A2AService.ListTaskPushNotificationConfigs
   */
  listTaskPushNotificationConfigs: {
    methodKind: "unary";
    input: typeof ListTaskPushNotificationConfigsRequestSchema;
    output: typeof ListTaskPushNotificationConfigsResponseSchema;
  },
  /**
   * Gets the extended agent card for the authenticated agent.
   *
   * @generated from rpc lf.a2a.v1.A2AService.GetExtendedAgentCard
   */
  getExtendedAgentCard: {
    methodKind: "unary";
    input: typeof GetExtendedAgentCardRequestSchema;
    output: typeof AgentCardSchema;
  },
  /**
   * Deletes a push notification config for a task.
   *
   * @generated from rpc lf.a2a.v1.A2AService.DeleteTaskPushNotificationConfig
   */
  deleteTaskPushNotificationConfig: {
    methodKind: "unary";
    input: typeof DeleteTaskPushNotificationConfigRequestSchema;
    output: typeof EmptySchema;
  },
}>;

