// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file standards/open/v1/RT000YHJ5.proto (package standards.open.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_type_date } from "../../../google/type/date_pb";

/**
 * Describes the file standards/open/v1/RT000YHJ5.proto.
 */
export const file_standards_open_v1_RT000YHJ5 = /*@__PURE__*/
  fileDesc("CiFzdGFuZGFyZHMvb3Blbi92MS9SVDAwMFlISjUucHJvdG8SEXN0YW5kYXJkcy5vcGVuLnYxIpsBCglSVDAwMFlISjUSNAoHcmVjb3JkcxgBIAMoCzIjLnN0YW5kYXJkcy5vcGVuLnYxLlJUMDAwWUhKNS5SZWNvcmQaWAoGUmVjb3JkEhAKCG1tbW1tbW1tGAEgASgJEhMKC2VudGl0eV9uYW1lGAIgASgJEhAKCGNjY2NjY2NjGAMgASgJEhUKDXN1Yl9mdW5kX25hbWUYBCABKAlCKFomZ28uYWxpcy5idWlsZC9jb21tb24vc3RhbmRhcmRzL29wZW4vdjFiBnByb3RvMw", [file_google_type_date]);

/**
 * Describes the message standards.open.v1.RT000YHJ5.
 * Use `create(RT000YHJ5Schema)` to create a new message.
 */
export const RT000YHJ5Schema = /*@__PURE__*/
  messageDesc(file_standards_open_v1_RT000YHJ5, 0);

/**
 * Describes the message standards.open.v1.RT000YHJ5.Record.
 * Use `create(RT000YHJ5_RecordSchema)` to create a new message.
 */
export const RT000YHJ5_RecordSchema = /*@__PURE__*/
  messageDesc(file_standards_open_v1_RT000YHJ5, 0, 0);

