// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file standards/open/v1/RT00085Z9.proto (package standards.open.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../../google/type/date_pb";

/**
 * Describes the file standards/open/v1/RT00085Z9.proto.
 */
export declare const file_standards_open_v1_RT00085Z9: GenFile;

/**
 * Wolfsberg Group Financial Crime Compliance Questionnaire (FCCQ) v1.1.
 *
 * @generated from message standards.open.v1.RT00085Z9
 */
export declare type RT00085Z9 = Message<"standards.open.v1.RT00085Z9"> & {
  /**
   * The name of the financial institution
   *
   * @generated from field: string financial_institution_name = 1;
   */
  financialInstitutionName: string;

  /**
   * The three letter ISO code of the country in which the LE is located
   *
   * @generated from field: string country = 2;
   */
  country: string;

  /**
   * Section 1. Information related to legal entity and its ownership
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership entity_and_ownership = 3;
   */
  entityAndOwnership?: RT00085Z9_EntityAndOwnership | undefined;

  /**
   * Section 2. Information related to the AML, CTF and Sanctions program
   *
   * @generated from field: standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsProgram aml_and_ctf_and_sanctions_program = 4;
   */
  amlAndCtfAndSanctionsProgram?: RT00085Z9_AMLAndCTFAndSanctionsProgram | undefined;

  /**
   * Section 3. Information related to the Anti Bribery and Corruption section program
   *
   * @generated from field: standards.open.v1.RT00085Z9.AntiBriberyAndCorruption anti_bribery_and_corruption = 5;
   */
  antiBriberyAndCorruption?: RT00085Z9_AntiBriberyAndCorruption | undefined;

  /**
   * Section 4. Information related to the AML, CTF and Sanctions Policies and Procedures
   *
   * @generated from field: standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsPoliciesAndProcedures aml_ctf_and_sanctions_policies_and_procedures = 7;
   */
  amlCtfAndSanctionsPoliciesAndProcedures?: RT00085Z9_AMLAndCTFAndSanctionsPoliciesAndProcedures | undefined;

  /**
   * Section 5. Information related to KYC, CDD and EDD
   *
   * @generated from field: standards.open.v1.RT00085Z9.KYCAndCDDAndEDD kyc_and_cdd_and_edd = 8;
   */
  kycAndCddAndEdd?: RT00085Z9_KYCAndCDDAndEDD | undefined;

  /**
   * Section 6. Information related to Monitoring and Reporting
   *
   * @generated from field: standards.open.v1.RT00085Z9.MonitoringAndReporting monitoring_and_reporting = 9;
   */
  monitoringAndReporting?: RT00085Z9_MonitoringAndReporting | undefined;

  /**
   * Section 7. Information related to Payment Transparency
   *
   * @generated from field: standards.open.v1.RT00085Z9.PaymentTransparency payment_transparency = 10;
   */
  paymentTransparency?: RT00085Z9_PaymentTransparency | undefined;

  /**
   * Section 8. Information related to Sanctions processes and procedures
   *
   * @generated from field: standards.open.v1.RT00085Z9.Sanctions sanctions = 11;
   */
  sanctions?: RT00085Z9_Sanctions | undefined;

  /**
   * Section 9. Information related to Training and Education
   *
   * @generated from field: standards.open.v1.RT00085Z9.TrainingAndEducation training_and_education = 12;
   */
  trainingAndEducation?: RT00085Z9_TrainingAndEducation | undefined;

  /**
   * Section 10. Audit information
   *
   * @generated from field: standards.open.v1.RT00085Z9.Audit audit = 13;
   */
  audit?: RT00085Z9_Audit | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.
 * Use `create(RT00085Z9Schema)` to create a new message.
 */
export declare const RT00085Z9Schema: GenMessage<RT00085Z9>;

/**
 * Response where a NO requires further information
 *
 * @generated from message standards.open.v1.RT00085Z9.YesNoExplain
 */
export declare type RT00085Z9_YesNoExplain = Message<"standards.open.v1.RT00085Z9.YesNoExplain"> & {
  /**
   * Yes / No response.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain.Response response = 1;
   */
  response: RT00085Z9_YesNoExplain_Response;

  /**
   * Explanation if the answer is `NO`
   *
   * @generated from field: string explanation = 2;
   */
  explanation: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.YesNoExplain.
 * Use `create(RT00085Z9_YesNoExplainSchema)` to create a new message.
 */
export declare const RT00085Z9_YesNoExplainSchema: GenMessage<RT00085Z9_YesNoExplain>;

/**
 * @generated from enum standards.open.v1.RT00085Z9.YesNoExplain.Response
 */
export enum RT00085Z9_YesNoExplain_Response {
  /**
   * @generated from enum value: RESPONSE_UNSPECIFIED = 0;
   */
  RESPONSE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: YES = 1;
   */
  YES = 1,

  /**
   * @generated from enum value: NO = 2;
   */
  NO = 2,
}

/**
 * Describes the enum standards.open.v1.RT00085Z9.YesNoExplain.Response.
 */
export declare const RT00085Z9_YesNoExplain_ResponseSchema: GenEnum<RT00085Z9_YesNoExplain_Response>;

/**
 * Response where a YES requires further information
 *
 * @generated from message standards.open.v1.RT00085Z9.YesExplainNo
 */
export declare type RT00085Z9_YesExplainNo = Message<"standards.open.v1.RT00085Z9.YesExplainNo"> & {
  /**
   * Yes / No response.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesExplainNo.Response response = 1;
   */
  response: RT00085Z9_YesExplainNo_Response;

  /**
   * Explanation if the answer is `YES`
   *
   * @generated from field: string explanation = 2;
   */
  explanation: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.YesExplainNo.
 * Use `create(RT00085Z9_YesExplainNoSchema)` to create a new message.
 */
export declare const RT00085Z9_YesExplainNoSchema: GenMessage<RT00085Z9_YesExplainNo>;

/**
 * @generated from enum standards.open.v1.RT00085Z9.YesExplainNo.Response
 */
export enum RT00085Z9_YesExplainNo_Response {
  /**
   * @generated from enum value: RESPONSE_UNSPECIFIED = 0;
   */
  RESPONSE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: YES = 1;
   */
  YES = 1,

  /**
   * @generated from enum value: NO = 2;
   */
  NO = 2,
}

/**
 * Describes the enum standards.open.v1.RT00085Z9.YesExplainNo.Response.
 */
export declare const RT00085Z9_YesExplainNo_ResponseSchema: GenEnum<RT00085Z9_YesExplainNo_Response>;

/**
 * Response where further information is required regardless of whether a Yes or No is provided
 *
 * @generated from message standards.open.v1.RT00085Z9.YesNoAndExplain
 */
export declare type RT00085Z9_YesNoAndExplain = Message<"standards.open.v1.RT00085Z9.YesNoAndExplain"> & {
  /**
   * Yes / No response.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoAndExplain.Response response = 1;
   */
  response: RT00085Z9_YesNoAndExplain_Response;

  /**
   * Provide further information for the response
   *
   * @generated from field: string explanation = 2;
   */
  explanation: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.YesNoAndExplain.
 * Use `create(RT00085Z9_YesNoAndExplainSchema)` to create a new message.
 */
export declare const RT00085Z9_YesNoAndExplainSchema: GenMessage<RT00085Z9_YesNoAndExplain>;

/**
 * @generated from enum standards.open.v1.RT00085Z9.YesNoAndExplain.Response
 */
export enum RT00085Z9_YesNoAndExplain_Response {
  /**
   * @generated from enum value: RESPONSE_UNSPECIFIED = 0;
   */
  RESPONSE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: YES = 1;
   */
  YES = 1,

  /**
   * @generated from enum value: NO = 2;
   */
  NO = 2,
}

/**
 * Describes the enum standards.open.v1.RT00085Z9.YesNoAndExplain.Response.
 */
export declare const RT00085Z9_YesNoAndExplain_ResponseSchema: GenEnum<RT00085Z9_YesNoAndExplain_Response>;

/**
 * Definition of a name and digital signature
 *
 * @generated from message standards.open.v1.RT00085Z9.NameAndDigitalSignature
 */
export declare type RT00085Z9_NameAndDigitalSignature = Message<"standards.open.v1.RT00085Z9.NameAndDigitalSignature"> & {
  /**
   * @generated from field: string full_name = 1;
   */
  fullName: string;

  /**
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date | undefined;

  /**
   * @generated from field: string signature = 3;
   */
  signature: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.NameAndDigitalSignature.
 * Use `create(RT00085Z9_NameAndDigitalSignatureSchema)` to create a new message.
 */
export declare const RT00085Z9_NameAndDigitalSignatureSchema: GenMessage<RT00085Z9_NameAndDigitalSignature>;

/**
 * Definition of Entity and Ownership section
 *
 * @generated from message standards.open.v1.RT00085Z9.EntityAndOwnership
 */
export declare type RT00085Z9_EntityAndOwnership = Message<"standards.open.v1.RT00085Z9.EntityAndOwnership"> & {
  /**
   * Q1. The full legal name of the entity
   *
   * @generated from field: string legal_name = 1;
   */
  legalName: string;

  /**
   * Q2 List all foreign branches covered by this questionnaire.
   *
   * @generated from field: repeated standards.open.v1.RT00085Z9.EntityAndOwnership.Branch covered_branches = 2;
   */
  coveredBranches: RT00085Z9_EntityAndOwnership_Branch[];

  /**
   * Q3 The full legal (registered) address of the entity
   *
   * @generated from field: string legal_address = 3;
   */
  legalAddress: string;

  /**
   * Q4 The full primary business address of the entity
   *
   * @generated from field: string business_address = 4;
   */
  businessAddress: string;

  /**
   * Q5 The date in which the entity was incorporated
   *
   * @generated from field: google.type.Date date_of_incorporation = 5;
   */
  dateOfIncorporation?: Date | undefined;

  /**
   * Q6 Select the applicable ownership types and attach an ownership chart if available
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.OwnershipType ownership_types = 6;
   */
  ownershipTypes: RT00085Z9_EntityAndOwnership_OwnershipType;

  /**
   * Q6a1 If publicly traded, provide the primary security identifier the traded instrument
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier security_identifier = 7;
   */
  securityIdentifier?: RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier | undefined;

  /**
   * Q6d1 If privately owned, provide details of shareholders with a holding of 10%
   * or more up the ownership chain
   *
   * @generated from field: repeated standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder significant_shareholders = 8;
   */
  significantShareholders: RT00085Z9_EntityAndOwnership_SignificantShareholder[];

  /**
   * If privately owned, has a beneficial ownership structure chart been attached?
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain structure_chart = 9;
   */
  structureChart?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q7 Provide the % of the entity's total shares composed of bearer shares (for example 10% enter as 0.1)
   *
   * @generated from field: float percent_bearer_shares = 10;
   */
  percentBearerShares: number;

  /**
   * Q8 Does the entity operate any of its branches, operate under an Offshore Banking License (OBL)?
   *
   * @generated from field: bool any_branches_under_offshore_banking_license = 11;
   */
  anyBranchesUnderOffshoreBankingLicense: boolean;

  /**
   * Q8a, List any branches operate under offshore banking license (if TRUE to Q1.8)
   *
   * @generated from field: repeated standards.open.v1.RT00085Z9.EntityAndOwnership.Branch branches_under_offshore_banking_license = 12;
   */
  branchesUnderOffshoreBankingLicense: RT00085Z9_EntityAndOwnership_Branch[];
};

/**
 * Describes the message standards.open.v1.RT00085Z9.EntityAndOwnership.
 * Use `create(RT00085Z9_EntityAndOwnershipSchema)` to create a new message.
 */
export declare const RT00085Z9_EntityAndOwnershipSchema: GenMessage<RT00085Z9_EntityAndOwnership>;

/**
 * Information about a foreign branch
 *
 * @generated from message standards.open.v1.RT00085Z9.EntityAndOwnership.Branch
 */
export declare type RT00085Z9_EntityAndOwnership_Branch = Message<"standards.open.v1.RT00085Z9.EntityAndOwnership.Branch"> & {
  /**
   * The name of the branch
   *
   * @generated from field: string branch_name = 1;
   */
  branchName: string;

  /**
   * The country in which the branch is located (the three letter ISO code)
   *
   * @generated from field: string location = 2;
   */
  location: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.EntityAndOwnership.Branch.
 * Use `create(RT00085Z9_EntityAndOwnership_BranchSchema)` to create a new message.
 */
export declare const RT00085Z9_EntityAndOwnership_BranchSchema: GenMessage<RT00085Z9_EntityAndOwnership_Branch>;

/**
 * Information to be provided if publicly traded
 *
 * @generated from message standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier
 */
export declare type RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier = Message<"standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier"> & {
  /**
   * Codification chosen to identify the financial instrument
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier.FinancialInstrumentIdentifier financial_identifier = 4;
   */
  financialIdentifier: RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier_FinancialInstrumentIdentifier;

  /**
   * Identifier of the affected instrument
   *
   * @generated from field: string instrument = 5;
   */
  instrument: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier.
 * Use `create(RT00085Z9_EntityAndOwnership_TradedSecurityIdentifierSchema)` to create a new message.
 */
export declare const RT00085Z9_EntityAndOwnership_TradedSecurityIdentifierSchema: GenMessage<RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier>;

/**
 * Enumerations of financial identifiers
 *
 * @generated from enum standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier.FinancialInstrumentIdentifier
 */
export enum RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier_FinancialInstrumentIdentifier {
  /**
   * Source not specified by the user.
   *
   * @generated from enum value: IDENTIFIER_UNSPECIFIED = 0;
   */
  IDENTIFIER_UNSPECIFIED = 0,

  /**
   * FIGI (Financial Instrument Global Identifier). To look up the FIGI navigate to https://www.openfigi.com/.
   *
   * @generated from enum value: FIGI = 1;
   */
  FIGI = 1,

  /**
   * PermID (Refinitiv Permanent Identifier). To look up the PermID navigate to https://permid.org/
   *
   * @generated from enum value: PERM_ID = 2;
   */
  PERM_ID = 2,
}

/**
 * Describes the enum standards.open.v1.RT00085Z9.EntityAndOwnership.TradedSecurityIdentifier.FinancialInstrumentIdentifier.
 */
export declare const RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier_FinancialInstrumentIdentifierSchema: GenEnum<RT00085Z9_EntityAndOwnership_TradedSecurityIdentifier_FinancialInstrumentIdentifier>;

/**
 * The definition of a beneficial owner resource
 *
 * @generated from message standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder
 */
export declare type RT00085Z9_EntityAndOwnership_SignificantShareholder = Message<"standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder"> & {
  /**
   * The resource name of the client
   *
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * The type of beneficial owner
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.BeneficialOwnerType beneficial_owner_type = 2;
   */
  beneficialOwnerType: RT00085Z9_EntityAndOwnership_SignificantShareholder_BeneficialOwnerType;

  /**
   * The ultimate effective interest in the legal entity on a look through basis
   *
   * @generated from field: double beneficial_ownership = 3;
   */
  beneficialOwnership: number;

  /**
   * Complete if the beneficial person is a natural person
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.NaturalPerson natural_person_ownership_details = 4;
   */
  naturalPersonOwnershipDetails?: RT00085Z9_EntityAndOwnership_SignificantShareholder_NaturalPerson | undefined;

  /**
   * Complete if the `SignificantShareholder` is a legal entity
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.LegalEntity legal_entity_ownership_details = 5;
   */
  legalEntityOwnershipDetails?: RT00085Z9_EntityAndOwnership_SignificantShareholder_LegalEntity | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.
 * Use `create(RT00085Z9_EntityAndOwnership_SignificantShareholderSchema)` to create a new message.
 */
export declare const RT00085Z9_EntityAndOwnership_SignificantShareholderSchema: GenMessage<RT00085Z9_EntityAndOwnership_SignificantShareholder>;

/**
 * Information relating to a natural person
 *
 * @generated from message standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.NaturalPerson
 */
export declare type RT00085Z9_EntityAndOwnership_SignificantShareholder_NaturalPerson = Message<"standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.NaturalPerson"> & {
  /**
   * The first name
   *
   * @generated from field: string given_name = 1;
   */
  givenName: string;

  /**
   * The last name
   *
   * @generated from field: string family_name = 2;
   */
  familyName: string;

  /**
   * The phone number including country code
   *
   * @generated from field: string phone_number = 3;
   */
  phoneNumber: string;

  /**
   * The email address of the manager
   *
   * @generated from field: string email_address = 4;
   */
  emailAddress: string;

  /**
   * The three letter ISO code of the country of residence
   *
   * @generated from field: string country_of_residence = 5;
   */
  countryOfResidence: string;

  /**
   * Place of address
   *
   * @generated from field: string address = 6;
   */
  address: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.NaturalPerson.
 * Use `create(RT00085Z9_EntityAndOwnership_SignificantShareholder_NaturalPersonSchema)` to create a new message.
 */
export declare const RT00085Z9_EntityAndOwnership_SignificantShareholder_NaturalPersonSchema: GenMessage<RT00085Z9_EntityAndOwnership_SignificantShareholder_NaturalPerson>;

/**
 * Information relating to a legal beneficial owner
 *
 * @generated from message standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.LegalEntity
 */
export declare type RT00085Z9_EntityAndOwnership_SignificantShareholder_LegalEntity = Message<"standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.LegalEntity"> & {
  /**
   * The name of the company
   *
   * @generated from field: string legal_name = 1;
   */
  legalName: string;

  /**
   * The registered office of the company
   *
   * @generated from field: string registered_office = 2;
   */
  registeredOffice: string;

  /**
   * The LEI identifier of the company (if available)
   *
   * @generated from field: string LEI = 3;
   */
  LEI: string;

  /**
   * The directors or managers of the legal entity
   *
   * @generated from field: repeated standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.NaturalPerson directors_or_managers = 4;
   */
  directorsOrManagers: RT00085Z9_EntityAndOwnership_SignificantShareholder_NaturalPerson[];

  /**
   * The own
   *
   * If PRIVATE, then the shareholders owning more than 10% or more of the entity
   *        repeated SignificantShareholder shareholders = 7;
   *
   * @generated from field: standards.open.v1.RT00085Z9.EntityAndOwnership.OwnershipType ownership_type = 6;
   */
  ownershipType: RT00085Z9_EntityAndOwnership_OwnershipType;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.LegalEntity.
 * Use `create(RT00085Z9_EntityAndOwnership_SignificantShareholder_LegalEntitySchema)` to create a new message.
 */
export declare const RT00085Z9_EntityAndOwnership_SignificantShareholder_LegalEntitySchema: GenMessage<RT00085Z9_EntityAndOwnership_SignificantShareholder_LegalEntity>;

/**
 * Types of account holders
 *
 * @generated from enum standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.BeneficialOwnerType
 */
export enum RT00085Z9_EntityAndOwnership_SignificantShareholder_BeneficialOwnerType {
  /**
   * Beneficial owner unspecified
   *
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * The beneficial owner is a natural person
   *
   * @generated from enum value: NATURAL_PERSON = 1;
   */
  NATURAL_PERSON = 1,

  /**
   * The beneficial owner is a legal entity
   *
   * @generated from enum value: LEGAL_ENTITY = 2;
   */
  LEGAL_ENTITY = 2,
}

/**
 * Describes the enum standards.open.v1.RT00085Z9.EntityAndOwnership.SignificantShareholder.BeneficialOwnerType.
 */
export declare const RT00085Z9_EntityAndOwnership_SignificantShareholder_BeneficialOwnerTypeSchema: GenEnum<RT00085Z9_EntityAndOwnership_SignificantShareholder_BeneficialOwnerType>;

/**
 * Enumerations of ownership type
 *
 * @generated from enum standards.open.v1.RT00085Z9.EntityAndOwnership.OwnershipType
 */
export enum RT00085Z9_EntityAndOwnership_OwnershipType {
  /**
   * The ownership type is unspecified
   *
   * @generated from enum value: OWNERSHIP_TYPE_UNSPECIFIED = 0;
   */
  OWNERSHIP_TYPE_UNSPECIFIED = 0,

  /**
   * Publicly Traded (25% of shares publicly traded)
   *
   * @generated from enum value: PUBLICLY_TRADED = 1;
   */
  PUBLICLY_TRADED = 1,

  /**
   * Member owned / mutual
   *
   * @generated from enum value: MEMBER_OR_MUTUAL = 2;
   */
  MEMBER_OR_MUTUAL = 2,

  /**
   * Government or state owned by more than 25%
   *
   * @generated from enum value: GOVERNMENT_OR_STATE = 3;
   */
  GOVERNMENT_OR_STATE = 3,

  /**
   * Privately owned
   *
   * @generated from enum value: PRIVATE = 4;
   */
  PRIVATE = 4,
}

/**
 * Describes the enum standards.open.v1.RT00085Z9.EntityAndOwnership.OwnershipType.
 */
export declare const RT00085Z9_EntityAndOwnership_OwnershipTypeSchema: GenEnum<RT00085Z9_EntityAndOwnership_OwnershipType>;

/**
 * Definition of AML, CTF and Sanctions Program Section
 *
 * @generated from message standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsProgram
 */
export declare type RT00085Z9_AMLAndCTFAndSanctionsProgram = Message<"standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsProgram"> & {
  /**
   * Q9a Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Appointed Officer with sufficient experience/expertise
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain appointed_officer_with_sufficient_experience = 2;
   */
  appointedOfficerWithSufficientExperience?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9b Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Cash reporting
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain cash_reporting = 3;
   */
  cashReporting?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9c Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): CDD
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain CDD = 4;
   */
  CDD?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9d Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): EDD
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain EDD = 5;
   */
  EDD?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9e Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Beneficial Ownership
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain beneficial_ownership = 6;
   */
  beneficialOwnership?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9f Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Independent Testing
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain independent_testing = 7;
   */
  independentTesting?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9g Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Periodic Review
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain periodic_review = 8;
   */
  periodicReview?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9h Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Policies and Procedures
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_and_procedures = 9;
   */
  policiesAndProcedures?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9i Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Risk Assessment
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain risk_assessment = 10;
   */
  riskAssessment?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9j Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Sanctions
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain sanctions = 11;
   */
  sanctions?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9k Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): PEP Screening
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain pep_screening = 12;
   */
  pepScreening?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9l Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Adverse Information Screening
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain adverse_information_screening = 13;
   */
  adverseInformationScreening?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9m Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Suspicious Activity Reporting
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain suspicious_activity_reporting = 14;
   */
  suspiciousActivityReporting?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9n Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Training and Education
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain training_and_education = 15;
   */
  trainingAndEducation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q9o Does the Entity have a programme that sets minimum AML, CTF and Sanctions standards regarding the following component (if NO, explain): Transaction Monitoring
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain transaction_monitoring = 16;
   */
  transactionMonitoring?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q10 Is the Entity's AML, CTF & Sanctions policy approved at least annually by the Board or equivalent Senior Management Committee? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policy_approved_at_least_annually_by_senior_committee = 17;
   */
  policyApprovedAtLeastAnnuallyBySeniorCommittee?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q11 & Q11a. Does the Entity use third parties to carry out any components of its AML, CTF & Sanctions programme? If YES, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesExplainNo use_third_parties = 18;
   */
  useThirdParties?: RT00085Z9_YesExplainNo | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsProgram.
 * Use `create(RT00085Z9_AMLAndCTFAndSanctionsProgramSchema)` to create a new message.
 */
export declare const RT00085Z9_AMLAndCTFAndSanctionsProgramSchema: GenMessage<RT00085Z9_AMLAndCTFAndSanctionsProgram>;

/**
 * Definition of the Anti Bribery and Corruption section
 *
 * @generated from message standards.open.v1.RT00085Z9.AntiBriberyAndCorruption
 */
export declare type RT00085Z9_AntiBriberyAndCorruption = Message<"standards.open.v1.RT00085Z9.AntiBriberyAndCorruption"> & {
  /**
   * Q12 Has the Entity documented policies and procedures consistent with applicable ABC regulations and
   * requirements to [reasonably] prevent, detect and report bribery and corruption? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain documented_anti_bribery_and_corruption_policies_and_procedures = 1;
   */
  documentedAntiBriberyAndCorruptionPoliciesAndProcedures?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q13 Does the Entity's internal audit function or other independent third party cover ABC Policies and Procedures?
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_internal_audit_function_covers_abc_policies_and_procedures = 17;
   */
  entityInternalAuditFunctionCoversAbcPoliciesAndProcedures?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q14a Does the Entity provide mandatory ABC training to::
   * Board and senior Committee Management.
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_provides_mandatory_abc_training_to_board_and_senior_management_committee = 18;
   */
  entityProvidesMandatoryAbcTrainingToBoardAndSeniorManagementCommittee?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q14b Does the Entity provide mandatory ABC training to::
   * 1st Line of Defence.
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_provides_mandatory_abc_training_to_first_line_of_defence = 19;
   */
  entityProvidesMandatoryAbcTrainingToFirstLineOfDefence?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q14c Does the Entity provide mandatory ABC training to::
   * 2nd Line of Defence.
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_provides_mandatory_abc_training_to_second_line_of_defence = 20;
   */
  entityProvidesMandatoryAbcTrainingToSecondLineOfDefence?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q14d Does the Entity provide mandatory ABC training to::
   * 3rd Line of Defence.
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_provides_mandatory_abc_training_to_third_line_of_defence = 21;
   */
  entityProvidesMandatoryAbcTrainingToThirdLineOfDefence?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q14e Does the Entity provide mandatory ABC training to::
   * 3rd parties to which specific compliance activities subject to ABC risk have been outsourced
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_provides_mandatory_abc_training_to_third_parties_subject_to_abc_risk = 22;
   */
  entityProvidesMandatoryAbcTrainingToThirdPartiesSubjectToAbcRisk?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q14f Does the Entity provide mandatory ABC training to::
   * Non-employed workers as appropriate (contractors/consultants)
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_provides_mandatory_abc_training_to_non_employed_workers_as_appropriate = 23;
   */
  entityProvidesMandatoryAbcTrainingToNonEmployedWorkersAsAppropriate?: RT00085Z9_YesNoExplain | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.AntiBriberyAndCorruption.
 * Use `create(RT00085Z9_AntiBriberyAndCorruptionSchema)` to create a new message.
 */
export declare const RT00085Z9_AntiBriberyAndCorruptionSchema: GenMessage<RT00085Z9_AntiBriberyAndCorruption>;

/**
 * Definition of the AML, CTF & Sanctions Policies & Procedures
 *
 * @generated from message standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsPoliciesAndProcedures
 */
export declare type RT00085Z9_AMLAndCTFAndSanctionsPoliciesAndProcedures = Message<"standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsPoliciesAndProcedures"> & {
  /**
   * Q15a Has the Entity documented policies and procedures consistent with applicable AML, CTF & Sanctions regulations and requirements to reasonably prevent, detect and report:
   * Money laundering
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_documented_policies_and_procedures_for_money_laundering = 1;
   */
  entityHasDocumentedPoliciesAndProceduresForMoneyLaundering?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q15b Has the Entity documented policies and procedures consistent with applicable AML, CTF & Sanctions regulations and requirements to reasonably prevent, detect and report:
   * Terrorist financing
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_documented_policies_and_procedures_for_terrorist_financing = 2;
   */
  entityHasDocumentedPoliciesAndProceduresForTerroristFinancing?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q15c Has the Entity documented policies and procedures consistent with applicable AML, CTF & Sanctions regulations and requirements to reasonably prevent, detect and report:
   * Sanctions violations
   * If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_documented_policies_and_procedures_for_sanctions_violations = 3;
   */
  entityHasDocumentedPoliciesAndProceduresForSanctionsViolations?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16a Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit the opening and keeping of anonymous and fictitious named accounts
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_opening_and_keeping_anonymous_and_fictitious_named_accounts = 7;
   */
  policiesThatProhibitOpeningAndKeepingAnonymousAndFictitiousNamedAccounts?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16b Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit the opening and keeping of accounts for unlicensed banks and/or NBFIs
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_opening_accounts_for_unlicensed_banks_and_or_nbfis = 8;
   */
  policiesThatProhibitOpeningAccountsForUnlicensedBanksAndOrNbfis?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16c Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit dealing with other entities that provide banking services to unlicensed banks
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_dealing_with_entities_providing_banking_to_unlicensed_banks = 9;
   */
  policiesThatProhibitDealingWithEntitiesProvidingBankingToUnlicensedBanks?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16d Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit accounts/relationships with shell banks
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_accounts_or_relationships_with_shell_banks = 10;
   */
  policiesThatProhibitAccountsOrRelationshipsWithShellBanks?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16e Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit dealing with another entity that provides services to shell banks
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_dealing_with_another_entity_that_provides_services_to_shell_banks = 11;
   */
  policiesThatProhibitDealingWithAnotherEntityThatProvidesServicesToShellBanks?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16f Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit opening and keeping of accounts for Section 311 designated entities
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_accounts_for_section_311_entities = 12;
   */
  policiesThatProhibitAccountsForSection311Entities?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16g Does the Entity have policies and procedures that (If NO, explain):
   * Prohibit opening and keeping of accounts for any of unlicensed/unregulated remittance agents, exchanges houses,
   * casa de cambio, bureaux de change or money transfer agents
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_prohibit_accounts_for_unlicensed_or_regulated_remittance_agents_or_exchange_houses_or_money_transfer_agents = 13;
   */
  policiesThatProhibitAccountsForUnlicensedOrRegulatedRemittanceAgentsOrExchangeHousesOrMoneyTransferAgents?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16h Does the Entity have policies and procedures that (If NO, explain):
   * Assess the risks of relationships with domestic and foreign PEPs, including their family and close associates
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_assess_risks_of_relationships_with_peps = 14;
   */
  policiesThatAssessRisksOfRelationshipsWithPeps?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16i Does the Entity have policies and procedures that (If NO, explain):
   * Define escalation processes for financial crime risk issues
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_define_escalation_process_for_financial_crime = 15;
   */
  policiesThatDefineEscalationProcessForFinancialCrime?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16j Does the Entity have policies and procedures that (If NO, explain):
   * Specify how potentially suspicious activity identified by employees is to be escalated and investigated
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_specify_how_suspicious_activities_are_escalated = 17;
   */
  policiesThatSpecifyHowSuspiciousActivitiesAreEscalated?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q16k Does the Entity have policies and procedures that (If NO, explain):
   * Outline the processes regarding screening for sanctions, PEPs and negative media
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_that_outline_process_for_screening_for_sanctions_peps_and_negative_media = 18;
   */
  policiesThatOutlineProcessForScreeningForSanctionsPepsAndNegativeMedia?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q17 Has the Entity defined a risk tolerance statement or similar document which defines a risk boundary around their business? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_had_defined_a_risk_tolerance_statement = 20;
   */
  entityHadDefinedARiskToleranceStatement?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q18 & Q18a Does the Entity have a record retention procedures that comply with applicable laws? If NO, explain. If YES, what is the retention period.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoAndExplain entity_has_record_retention_procedure = 21;
   */
  entityHasRecordRetentionProcedure?: RT00085Z9_YesNoAndExplain | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.AMLAndCTFAndSanctionsPoliciesAndProcedures.
 * Use `create(RT00085Z9_AMLAndCTFAndSanctionsPoliciesAndProceduresSchema)` to create a new message.
 */
export declare const RT00085Z9_AMLAndCTFAndSanctionsPoliciesAndProceduresSchema: GenMessage<RT00085Z9_AMLAndCTFAndSanctionsPoliciesAndProcedures>;

/**
 * Definition of KYC, CDD and EDD information
 *
 * @generated from message standards.open.v1.RT00085Z9.KYCAndCDDAndEDD
 */
export declare type RT00085Z9_KYCAndCDDAndEDD = Message<"standards.open.v1.RT00085Z9.KYCAndCDDAndEDD"> & {
  /**
   * Q19 Does the Entity verify the identity of the customer? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_verifies_identity_of_customer = 1;
   */
  entityVerifiesIdentityOfCustomer?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q20 Do the Entity's policies and procedures set out when CDD must be completed, e.g. at the time of onboarding or within 30 days? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_and_procedures_set_out_when_cdd_must_be_completed = 2;
   */
  policiesAndProceduresSetOutWhenCddMustBeCompleted?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21a Does the Entity gather and retain Ownership structure information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_ownership_structure_information = 3;
   */
  entityGathersOwnershipStructureInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21b Does the Entity gather and retain Customer identification information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_customer_identification_information = 4;
   */
  entityGathersCustomerIdentificationInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21c Does the Entity gather and retain Expected activity information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_expected_activity_information = 5;
   */
  entityGathersExpectedActivityInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21d Does the Entity gather and retain Nature of business/employment information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_nature_of_business_information = 6;
   */
  entityGathersNatureOfBusinessInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21e Does the Entity gather and retain Product usage information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_product_usage_information = 7;
   */
  entityGathersProductUsageInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21f Does the Entity gather and retain Purpose and nature of relationship information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_purpose_and_nature_of_relationship_information = 8;
   */
  entityGathersPurposeAndNatureOfRelationshipInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q21g Does the Entity gather and retain Source of funds information when conducting CDD? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_gathers_source_of_funds_information = 9;
   */
  entityGathersSourceOfFundsInformation?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q22a Is the Ultimate beneficial ownership identified. If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain ultimate_beneficial_ownership_identified = 10;
   */
  ultimateBeneficialOwnershipIdentified?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q22a1 Are ultimate beneficial owners verified?. If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain ultimate_beneficial_ownership_verified = 11;
   */
  ultimateBeneficialOwnershipVerified?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q22b Are the Authorised signatories (where applicable) identified. If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain authorised_signatories_identified = 12;
   */
  authorisedSignatoriesIdentified?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q22c Are the key controllers identified. If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain key_controllers_identified = 13;
   */
  keyControllersIdentified?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q22d Are the other relevant parties identified. If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain other_relevant_parties_identified = 14;
   */
  otherRelevantPartiesIdentified?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q23 Does the due diligence process result in customers receiving a risk classification? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain due_diligence_process_results_in_risk_classification = 16;
   */
  dueDiligenceProcessResultsInRiskClassification?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q24 Does the Entity have a risk based approach to screening customers and connected parties to determine
   * whether they are PEPs, or controlled by PEPs?
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoAndExplain entity_has_risk_based_approach_to_screening_for_pep_connections = 28;
   */
  entityHasRiskBasedApproachToScreeningForPepConnections?: RT00085Z9_YesNoAndExplain | undefined;

  /**
   * Q25 Does the Entity have policies, procedures and processes to review and escalate potential matches from screening customers and connected parties to determine whether they are PEPs, or controlled by PEPs?
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoAndExplain entity_has_escalation_process_for_matches_when_screening_for_pep_connections = 29;
   */
  entityHasEscalationProcessForMatchesWhenScreeningForPepConnections?: RT00085Z9_YesNoAndExplain | undefined;

  /**
   * Q26a Does the Entity have a process to review and update customer information based on KYC renewal
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain process_to_review_and_update_customer_information_on_kyc_renewal = 34;
   */
  processToReviewAndUpdateCustomerInformationOnKycRenewal?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27a Are Non-account customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesExplainNo non_account_customers_restricted_by_fcc_programme = 37;
   */
  nonAccountCustomersRestrictedByFccProgramme?: RT00085Z9_YesExplainNo | undefined;

  /**
   * Q27b Are Non-resident customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain non_resident_customers_restricted_by_fcc_programme = 38;
   */
  nonResidentCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27c Are Shell-banks customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain shell_banks_customers_restricted_by_fcc_programme = 39;
   */
  shellBanksCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27d Are MVTS / MSB customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mvts_msb_customers_restricted_by_fcc_programme = 40;
   */
  mvtsMsbCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27e Are PEP customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain pep_customers_restricted_by_fcc_programme = 41;
   */
  pepCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27f Are PEP related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain pep_related_customers_restricted_by_fcc_programme = 42;
   */
  pepRelatedCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27g Are PEP Close Associate customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain pep_close_associate_customers_restricted_by_fcc_programme = 43;
   */
  pepCloseAssociateCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27h Are Correspondent Banks related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain correspondent_bank_customers_restricted_by_fcc_programme = 44;
   */
  correspondentBankCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27h1 If Correspondent Banks EDD or EDD & restricted, does the EDD assessment contain the elements as set out in the Wolfsberg Correspondent Banking Principles 2014? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain correspondent_bank_customers_assessment_contains_worlsberg_principles_elements = 45;
   */
  correspondentBankCustomersAssessmentContainsWorlsbergPrinciplesElements?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27i Are Arms, defense and military related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain arms_defense_and_military_customers_restricted_by_fcc_programme = 46;
   */
  armsDefenseAndMilitaryCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27j Are Atomic Power related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain atomic_power_customers_restricted_by_fcc_programme = 47;
   */
  atomicPowerCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27k Are Extractive Industry related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain extractive_industry_customers_restricted_by_fcc_programme = 48;
   */
  extractiveIndustryCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27l Are Precious metals and stones related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain precious_metals_and_stones_customers_restricted_by_fcc_programme = 49;
   */
  preciousMetalsAndStonesCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27m Are Unregulated Charity customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain unregulated_charity_customers_restricted_by_fcc_programme = 50;
   */
  unregulatedCharityCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27n Are Regulated Charity customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain regulated_charity_customers_restricted_by_fcc_programme = 51;
   */
  regulatedCharityCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27o Are Red light business / Adult entertainment customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain red_light_or_adult_entertainment_customers_restricted_by_fcc_programme = 52;
   */
  redLightOrAdultEntertainmentCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27p Are Non-Government Organisations customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain ngo_customers_restricted_by_fcc_programme = 53;
   */
  ngoCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27q Are Virtual Currency customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain virtual_currency_cutsomers_restricted_by_fcc_programme = 54;
   */
  virtualCurrencyCutsomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27r Are Marijuana related customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain marijuana_related_customers_restricted_by_fcc_programme = 55;
   */
  marijuanaRelatedCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27s Are Embassy or Consulate customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain embassy_or_consulate_customers_restricted_by_fcc_programme = 56;
   */
  embassyOrConsulateCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27t Are Gambling  customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain gambling_customers_restricted_by_fcc_programme = 57;
   */
  gamblingCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27u Are Payment Service Provider customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain payment_service_provider_customers_restricted_by_fcc_programme = 58;
   */
  paymentServiceProviderCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q27v Are other types of customers subject to EDD and/or are restricted, or prohibited by the Entity's FCC programme? If YES (i.e. restricted), please provide details.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain other_customers_restricted_by_fcc_programme = 59;
   */
  otherCustomersRestrictedByFccProgramme?: RT00085Z9_YesNoExplain | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.KYCAndCDDAndEDD.
 * Use `create(RT00085Z9_KYCAndCDDAndEDDSchema)` to create a new message.
 */
export declare const RT00085Z9_KYCAndCDDAndEDDSchema: GenMessage<RT00085Z9_KYCAndCDDAndEDD>;

/**
 * Definition for Monitoring & Reporting information
 *
 * @generated from message standards.open.v1.RT00085Z9.MonitoringAndReporting
 */
export declare type RT00085Z9_MonitoringAndReporting = Message<"standards.open.v1.RT00085Z9.MonitoringAndReporting"> & {
  /**
   * Q29 Does the Entity have risk based policies, procedures and monitoring processes for the identification and reporting of suspicious activity?
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_risk_based_policies = 1;
   */
  entityHasRiskBasedPolicies?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q30 What is the method used by the Entity to monitor transactions for suspicious activities?
   *
   * @generated from field: string method_used_by_entity_to_monitor_transaction_for_suspicious_activities = 2;
   */
  methodUsedByEntityToMonitorTransactionForSuspiciousActivities: string;

  /**
   * Q31 Does the Entity have regulatory requirements to report suspicious transactions?
   *
   * @generated from field: bool entity_has_regulatory_requirements_to_report_suspicious_transactions = 4;
   */
  entityHasRegulatoryRequirementsToReportSuspiciousTransactions: boolean;

  /**
   * Q31a If TRUE to Q31, does the Entity have policies, procedures and processes to comply with suspicious transaction reporting requirements? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_policies_procedures_processes_to_comply_with_suspicious_transaction_monitoring_requirements = 5;
   */
  entityHasPoliciesProceduresProcessesToComplyWithSuspiciousTransactionMonitoringRequirements?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q32 Does the Entity have policies, procedures and processes to review and escalate matters arising from the monitoring of customer transactions and activity? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_policies_procedures_and_processes_to_review_and_escalate = 6;
   */
  entityHasPoliciesProceduresAndProcessesToReviewAndEscalate?: RT00085Z9_YesNoExplain | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.MonitoringAndReporting.
 * Use `create(RT00085Z9_MonitoringAndReportingSchema)` to create a new message.
 */
export declare const RT00085Z9_MonitoringAndReportingSchema: GenMessage<RT00085Z9_MonitoringAndReporting>;

/**
 * Definition for Payment Transparency Information
 *
 * @generated from message standards.open.v1.RT00085Z9.PaymentTransparency
 */
export declare type RT00085Z9_PaymentTransparency = Message<"standards.open.v1.RT00085Z9.PaymentTransparency"> & {
  /**
   * Q33 Does the Entity adhere to the Wolfsberg Group Payment Transparency Standards? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_adheres_to_wolfsberg_payment_transparency_standards = 1;
   */
  entityAdheresToWolfsbergPaymentTransparencyStandards?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q34a Does the Entity have policies, procedures and processes to [reasonably] comply with and have controls in place to ensure compliance with (if NO explain):FATF Recommendation 16
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_and_procedures_to_comply_with_fatf_recommendation_16 = 2;
   */
  policiesAndProceduresToComplyWithFatfRecommendation16?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q34b Does the Entity have policies, procedures and processes to [reasonably] comply with and have controls in place to ensure compliance with (if NO explain): Local Regulations
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain policies_and_procedures_to_comply_with_local_regulations = 3;
   */
  policiesAndProceduresToComplyWithLocalRegulations?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q34b1 Specify the relevant local Payment and Transparency regulations
   *
   * @generated from field: string specify_relevant_local_payment_and_transparency_regulation = 4;
   */
  specifyRelevantLocalPaymentAndTransparencyRegulation: string;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.PaymentTransparency.
 * Use `create(RT00085Z9_PaymentTransparencySchema)` to create a new message.
 */
export declare const RT00085Z9_PaymentTransparencySchema: GenMessage<RT00085Z9_PaymentTransparency>;

/**
 * Definition of Sanctions policies and processes
 *
 * @generated from message standards.open.v1.RT00085Z9.Sanctions
 */
export declare type RT00085Z9_Sanctions = Message<"standards.open.v1.RT00085Z9.Sanctions"> & {
  /**
   * Q35 Does the Entity have a Sanctions Policy approved by management regarding compliance with sanctions law applicable to the Entity, including with respect its business conducted with, or through accounts held at foreign financial institutions? If NO, explain.
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_management_approved_sanctions_policy = 1;
   */
  entityHasManagementApprovedSanctionsPolicy?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q36 Does the Entity screen its customers, including beneficial ownership information collected by the Entity, during onboarding and regularly thereafter against Sanctions Lists? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_screens_customers_against_sanctions_lists = 4;
   */
  entityScreensCustomersAgainstSanctionsLists?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q37a Is the following sanctions list used in its screening process: Consolidated United Nations Security Council Sanctions List (UN)
   *
   * @generated from field: bool consolidated_united_nations_sanctions_list_used_in_screening = 8;
   */
  consolidatedUnitedNationsSanctionsListUsedInScreening: boolean;

  /**
   * Q37b Is the following sanctions list used in its screening process: United States Department of the Treasury's Office of Foreign Assets Control (OFAC)
   *
   * @generated from field: bool usa_dept_of_treasury_ofac_sanctions_list_used_in_screening = 9;
   */
  usaDeptOfTreasuryOfacSanctionsListUsedInScreening: boolean;

  /**
   * Q37c Is the following sanctions list used in its screening process: Office of Financial Sanctions Implementation HMT (OFSI)
   *
   * @generated from field: bool office_of_financial_sanctions_implementation_hmt_sanctions_list_used_in_screening = 10;
   */
  officeOfFinancialSanctionsImplementationHmtSanctionsListUsedInScreening: boolean;

  /**
   * Q37d Is the following sanctions list used in its screening process: European Union Consolidated List (EU)
   *
   * @generated from field: bool european_union_consolidated_list_used_in_screening = 11;
   */
  europeanUnionConsolidatedListUsedInScreening: boolean;

  /**
   * Q37e Is the following sanctions list used in its screening process: Lists maintained by other G7 member countries
   *
   * @generated from field: bool list_maintained_by_other_G7_member_country_used_in_screening = 12;
   */
  listMaintainedByOtherG7MemberCountryUsedInScreening: boolean;

  /**
   * Q37f If TRUE for Q37e, specify
   *
   * @generated from field: string other_G7_member_country_sanctions_list_used_in_screening = 13;
   */
  otherG7MemberCountrySanctionsListUsedInScreening: string;

  /**
   * Q38 Does the Entity have a physical presence, e.g., branches, subsidiaries, or representative offices located in countries/regions against which UN, OFAC, OFSI, EU and G7 member countries have enacted comprehensive jurisdiction-based Sanctions? If YES, eplain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesExplainNo entity_has_physical_presence_in_sanctioned_countries = 16;
   */
  entityHasPhysicalPresenceInSanctionedCountries?: RT00085Z9_YesExplainNo | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.Sanctions.
 * Use `create(RT00085Z9_SanctionsSchema)` to create a new message.
 */
export declare const RT00085Z9_SanctionsSchema: GenMessage<RT00085Z9_Sanctions>;

/**
 * Definition of Training and Education Information
 *
 * @generated from message standards.open.v1.RT00085Z9.TrainingAndEducation
 */
export declare type RT00085Z9_TrainingAndEducation = Message<"standards.open.v1.RT00085Z9.TrainingAndEducation"> & {
  /**
   * Q39a Does the Entity provide mandatory training on (if NO, explain): Identification and reporting of transactions to government authorities
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain provides_mandatory_training_on_identification_and_reporting_of_transaction_to_government_authorities = 1;
   */
  providesMandatoryTrainingOnIdentificationAndReportingOfTransactionToGovernmentAuthorities?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q39b Does the Entity provide mandatory training on (if NO, explain): Examples of different forms of money laundering, terrorist financing and sanctions violations relevant for the types of products and services offered
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain provides_mandatory_training_on_examples_of_different_types_of_money_laundering = 2;
   */
  providesMandatoryTrainingOnExamplesOfDifferentTypesOfMoneyLaundering?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q39c Does the Entity provide mandatory training on (if NO, explain): Internal policies for controlling money laundering, terrorist financing and sanctions violations
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain provides_mandatory_training_on_internal_policies_for_controlling_money_laundering = 3;
   */
  providesMandatoryTrainingOnInternalPoliciesForControllingMoneyLaundering?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q39d Does the Entity provide mandatory training on (if NO, explain): New issues that occur in the market, e.g., significant regulatory actions or new regulations
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain provides_mandatory_training_on_conduct_and_culture = 5;
   */
  providesMandatoryTrainingOnConductAndCulture?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q40a Is the above mandatory training provided to (if NO, explain): Board and Senior Committee Management
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mandatory_training_provided_to_board_and_senior_commitee_management = 6;
   */
  mandatoryTrainingProvidedToBoardAndSeniorCommiteeManagement?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q40b Is the above mandatory training provided to (if NO, explain): 1st Line of Defence
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mandatory_training_provided_to_first_line_of_defence = 7;
   */
  mandatoryTrainingProvidedToFirstLineOfDefence?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q40c Is the above mandatory training provided to (if NO, explain): 2nd Line of Defence
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mandatory_training_provided_to_second_line_of_defence = 8;
   */
  mandatoryTrainingProvidedToSecondLineOfDefence?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q40d Is the above mandatory training provided to (if NO, explain): 3nd Line of Defence
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mandatory_training_provided_to_third_line_of_defence = 9;
   */
  mandatoryTrainingProvidedToThirdLineOfDefence?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q40e Is the above mandatory training provided to (if NO, explain): 3rd parties to which specific FCC activities have been outsourced
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mandatory_training_provided_to_third_parities_to_which_activities_outsourced = 10;
   */
  mandatoryTrainingProvidedToThirdParitiesToWhichActivitiesOutsourced?: RT00085Z9_YesNoExplain | undefined;

  /**
   * Q40f Is the above mandatory training provided to (if NO, explain): Non-employed workers (contractors/consultants)
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain mandatory_training_provided_to_non_employed_workers = 11;
   */
  mandatoryTrainingProvidedToNonEmployedWorkers?: RT00085Z9_YesNoExplain | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.TrainingAndEducation.
 * Use `create(RT00085Z9_TrainingAndEducationSchema)` to create a new message.
 */
export declare const RT00085Z9_TrainingAndEducationSchema: GenMessage<RT00085Z9_TrainingAndEducation>;

/**
 * Definition of Audit information
 *
 * @generated from message standards.open.v1.RT00085Z9.Audit
 */
export declare type RT00085Z9_Audit = Message<"standards.open.v1.RT00085Z9.Audit"> & {
  /**
   * Q41 In addition to inspections by the government supervisors/regulators, does the Entity have an internal audit function, a testing function or other independent third party, or both, that assesses FCC AML, CTF and Sanctions policies and practices on a regular basis? If NO, explain
   *
   * @generated from field: standards.open.v1.RT00085Z9.YesNoExplain entity_has_internal_audit_or_similar_testing_function = 1;
   */
  entityHasInternalAuditOrSimilarTestingFunction?: RT00085Z9_YesNoExplain | undefined;
};

/**
 * Describes the message standards.open.v1.RT00085Z9.Audit.
 * Use `create(RT00085Z9_AuditSchema)` to create a new message.
 */
export declare const RT00085Z9_AuditSchema: GenMessage<RT00085Z9_Audit>;

/**
 * Batch set of RT00085Z9 responses
 *
 * @generated from message standards.open.v1.RT00085Z9_batch
 */
export declare type RT00085Z9_batch = Message<"standards.open.v1.RT00085Z9_batch"> & {
  /**
   * @generated from field: repeated standards.open.v1.RT00085Z9 response = 1;
   */
  response: RT00085Z9[];
};

/**
 * Describes the message standards.open.v1.RT00085Z9_batch.
 * Use `create(RT00085Z9_batchSchema)` to create a new message.
 */
export declare const RT00085Z9_batchSchema: GenMessage<RT00085Z9_batch>;

