// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file alis/open/in/v1/in.proto (package alis.open.in.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "../../../../google/protobuf/timestamp_pb";
import type { Instrument as Instrument$1 } from "../../px/v1/px_pb";
import type { Instrument as Instrument$2 } from "../../cx/v1/cx_pb";

/**
 * Describes the file alis/open/in/v1/in.proto.
 */
export declare const file_alis_open_in_v1_in: GenFile;

/**
 * Instrument defines a financial instrument
 * as a resource in the IN domain.
 *
 * @generated from message alis.open.in.v1.Instrument
 */
export declare type Instrument = Message<"alis.open.in.v1.Instrument"> & {
  /**
   * The Instrument name is the unique identifier
   * across organisations. The Instrument ID must be a valid Bloomberg
   * or custom FIGI, as defined by www.openfigi.com.
   *
   * Format: instruments/{instrumentID}
   * Example: "instruments/BBG000B9XRY4"
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Figi Type. Either a global or custom FIGI,
   * else set to unspecified
   *
   * @generated from field: alis.open.in.v1.FigiType figi_type = 2;
   */
  figiType: FigiType;

  /**
   * Human readable display name of the instrument.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Security Description of the instrument.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Market Sector
   * The asset class/category of the particular instrument
   * Format: EQUITY, MONEY_MARKET, etc.
   *
   * @generated from field: alis.open.in.v1.Instrument.MarketSector market_sector = 5;
   */
  marketSector: Instrument_MarketSector;

  /**
   * Description of the specific instrument type within its market sector.
   * This typically depends on the market sector and is fairly flexible
   * Possible values defined at https://www.openfigi.com/api/enumValues/v3/securityType
   *
   * @generated from field: string security_type = 6;
   */
  securityType: string;

  /**
   * Instrument classifications
   *
   * @generated from field: alis.open.in.v1.Instrument.Classifications classifications = 7;
   */
  classifications?: Instrument_Classifications;

  /**
   * External identifiers for the instrument.
   *
   * @generated from field: alis.open.in.v1.Instrument.ExternalIDs external_ids = 8;
   */
  externalIds?: Instrument_ExternalIDs;

  /**
   * Exchange Code
   * Code for the trading venue or environment on which
   * the instrument trades. If an exchange is specified,
   * the code will be for the specified exchange.
   * Format: US, UN, SJ etc.
   *
   * @generated from field: string exch_code = 9;
   */
  exchCode: string;

  /**
   * Currency
   * The 3-letter currency code defined in ISO 4217.
   * Currency in which the security was issued.
   * Equities: Trading currency for the security.
   * Fixed Income: Provides the currency in which
   * the bond was issued, not necessarily the currency
   * in which the bond trades or pays its coupons.
   *
   * @generated from field: string currency_code = 10;
   */
  currencyCode: string;

  /**
   * The ISO country code
   * (-- api-linter: core::0143::standardized-codes=disabled
   *     aip.dev/not-precedent: 'Country' is a well defined attributes within Finance. --)
   *
   * @generated from field: string country_code = 11;
   */
  countryCode: string;

  /**
   * Name of the issuing entity of the security.
   *
   * @generated from field: string issuer = 12;
   */
  issuer: string;

  /**
   * Display Ticker
   * Used for display purposes only
   * For source specific tickers and identifiers refer to the external_ids attribute.
   *
   * @generated from field: string ticker = 15;
   */
  ticker: string;

  /**
   * Website
   *
   * @generated from field: string website_uri = 17;
   */
  websiteUri: string;

  /**
   * Boolean indicating whether the instrument has a Figi equal to its composite Figi
   *
   * @generated from field: bool is_composite_figi = 18;
   */
  isCompositeFigi: boolean;

  /**
   * Boolean indicating whether the instrument has a Figi equal to its shareClass Figi
   *
   * @generated from field: bool is_share_class_figi = 19;
   */
  isShareClassFigi: boolean;

  /**
   * Time the Instrument was last updated
   *
   * @generated from field: google.protobuf.Timestamp update_time = 20;
   */
  updateTime?: Timestamp;

  /**
   * Exchange identifiers
   *
   * @generated from field: alis.open.in.v1.Instrument.ExchangeIdentifiers exchange_identifiers = 22;
   */
  exchangeIdentifiers?: Instrument_ExchangeIdentifiers;

  /**
   * Engines
   *
   * @generated from field: alis.open.in.v1.Instrument.Engines engines = 23;
   */
  engines?: Instrument_Engines;

  /**
   * Custom attributes
   * USE WITH CAUTION.
   * NB: There are no validations on this field, values are fully managed by the user.
   * AN EXAMPLE:
   * The usage of this field could be to capture custom classifications:
   * The key of the map could be the classification group name (say "sets"), and the value could be the name of the   assigned element.
   * An example map entry in this case would be:
   * < "sets/rezco_asset_class", "sets/rezco_asset_class/elements/customEquity23">
   *
   * @generated from field: map<string, string> custom_attributes = 24;
   */
  customAttributes: { [key: string]: string };

  /**
   * Source Meta
   *
   * @generated from field: map<string, alis.open.in.v1.Instrument.SourceMetaData> source_meta = 99;
   */
  sourceMeta: { [key: string]: Instrument_SourceMetaData };
};

/**
 * Describes the message alis.open.in.v1.Instrument.
 * Use `create(InstrumentSchema)` to create a new message.
 */
export declare const InstrumentSchema: GenMessage<Instrument>;

/**
 * A set of classifications specific to the instrument.
 *
 * @generated from message alis.open.in.v1.Instrument.Classifications
 */
export declare type Instrument_Classifications = Message<"alis.open.in.v1.Instrument.Classifications"> & {
  /**
   * Bloomberg Industry Group
   * Bloomberg Industry Classification System) level I classification of the security
   * based on its business or economic function and characteristics
   *
   * @generated from field: string bloomberg_industry_sector = 1;
   */
  bloombergIndustrySector: string;

  /**
   * Bloomberg Industry Group
   * Bloomberg Industry Classification System) level II classification of the security
   * based on its business or economic function and characteristics
   *
   * @generated from field: string bloomberg_industry_group = 2;
   */
  bloombergIndustryGroup: string;

  /**
   * Bloomberg Industry SubGroup
   * Bloomberg Industry Classification System) level III classification of the security
   * based on its business or economic function and characteristics
   *
   * @generated from field: string bloomberg_industry_subgroup = 3;
   */
  bloombergIndustrySubgroup: string;

  /**
   * GICS Sector name
   * A text description indicating GICS sector classification. GICS (Global Industry
   * Classification Standard) is an industry classification standard developed by
   * MSCI in collaboration with Standard & Poors (S&P).
   *
   * @generated from field: string gics_sector = 4;
   */
  gicsSector: string;

  /**
   * Primary Global Industry Classification Standard (GICS) Industry Group Description.
   * GICS Classifies companies with increasing granularity by Sector, Industry Group, Industry and Sub-Industry.
   *
   * @generated from field: string gics_industry = 5;
   */
  gicsIndustry: string;

  /**
   * GICS Sub_industry
   *
   * @generated from field: string gics_subindustry = 6;
   */
  gicsSubindustry: string;

  /**
   * Investment theme
   * This theme attribute provides a flexible and lightweight way for the user to classify / group
   * instruments into user specified themes or ideas.  The available themes are set by the
   * user and are not shared between instrument deployments.  Given that this is a classification,
   * each instrument can only belong to a single theme at any point in time.
   *
   * @generated from field: string theme = 7;
   */
  theme: string;

  /**
   * Instrument sector
   * This is a generic sector field and not necessarily linked to a classification system.
   *
   * @generated from field: string sector = 8;
   */
  sector: string;

  /**
   * Instrument industry
   * This is a generic industry field and not necessarily linked to a classification system.
   *
   * @generated from field: string industry = 9;
   */
  industry: string;

  /**
   * Name of the sector that the research entity is classified into.
   * The list of sector classifiers may be found on the Morningstar Mapping Reference endpoint on Morningstar Equity API.
   * https://equityapi.morningstar.com/DataCatalog.aspx?catalogid=38
   *
   * @generated from field: string morningstar_sector = 10;
   */
  morningstarSector: string;

  /**
   * Name of the industry group that the research entity is classified into.
   * The list of industry group classifiers may be found on the Morningstar Mapping Reference endpoint on Morningstar Equity API.
   * https://equityapi.morningstar.com/DataCatalog.aspx?catalogid=38
   *
   * @generated from field: string morningstar_industry_group = 11;
   */
  morningstarIndustryGroup: string;

  /**
   * Name of the industry that the research entity is classified into.
   * The list of industry classifiers may be found on the Morningstar Mapping Reference endpoint on Morningstar Equity API.
   * https://equityapi.morningstar.com/DataCatalog.aspx?catalogid=38
   *
   * @generated from field: string morningstar_industry = 12;
   */
  morningstarIndustry: string;

  /**
   * ICB Industry
   * The Industry Classification Benchmark (ICB) is a globally recognized
   * standard for categorizing companies and securities.
   *
   * @generated from field: string icb_industry = 13;
   */
  icbIndustry: string;
};

/**
 * Describes the message alis.open.in.v1.Instrument.Classifications.
 * Use `create(Instrument_ClassificationsSchema)` to create a new message.
 */
export declare const Instrument_ClassificationsSchema: GenMessage<Instrument_Classifications>;

/**
 * External identifiers
 *
 * @generated from message alis.open.in.v1.Instrument.ExternalIDs
 */
export declare type Instrument_ExternalIDs = Message<"alis.open.in.v1.Instrument.ExternalIDs"> & {
  /**
   * FIGI as defined by www.openfigi.com.
   *
   * @generated from field: string figi = 1;
   */
  figi: string;

  /**
   * Composite Financial Instrument Global Identifier - The Composite Financial Instrument Global Identifier
   * (FIGI) enables users to link multiple FIGIs at the trading venue level within the same country or market
   * in order to obtain an aggregated view for an instrument within that country or market.
   *
   * @generated from field: string composite_figi = 2;
   */
  compositeFigi: string;

  /**
   * Share Class Financial Instrument Global Identifier - A Share Class level Financial Instrument Global Identifier
   * is assigned to an instrument that is traded in more than one country. This enables users to link multiple
   * Composite FIGIs for the same instrument in order to obtain an aggregated view for that instrument across all
   * countries (globally).
   *
   * @generated from field: string share_class_figi = 3;
   */
  shareClassFigi: string;

  /**
   * ISIN
   * An International Securities Identification Number (ISIN) is a code that uniquely identifies a specific
   * securities issue.
   *
   * @generated from field: string isin = 4;
   */
  isin: string;

  /**
   * SEDOL (Stock Exchange Daily Official List)
   * a list of security identifiers used in the United Kingdom and Ireland for clearing purposes.
   * The numbers are assigned by the London Stock Exchange, on request by the security issuer.
   *
   * @generated from field: string sedol = 5;
   */
  sedol: string;

  /**
   * CUSIP
   * a nine-digit numeric (e.g. 037833100 for Apple) or nine-character alphanumeric (e.g. 38259P508 for Google)
   * code that identifies a North American financial security for the purposes of facilitating clearing and
   * settlement of trades.
   * https://en.wikipedia.org/wiki/CUSIP
   *
   * @generated from field: string cusip = 6;
   */
  cusip: string;

  /**
   * RIC (Reuters instrument code)
   * is a ticker-like code used by Refinitiv to identify financial instruments and indices.
   * https://en.wikipedia.org/wiki/Reuters_Instrument_Code
   *
   * @generated from field: string ric = 7;
   */
  ric: string;

  /**
   * Primary RIC (Reuters instrument code)
   * is a ticker-like code used by Refinitiv to identify financial instruments and indices.
   * https://en.wikipedia.org/wiki/Reuters_Instrument_Code
   *
   * @generated from field: string primary_ric = 8;
   */
  primaryRic: string;

  /**
   * Bloomberg Ticker
   * a string of characters or numbers to identify a company or entity uniquely in Bloomberg.
   *
   * @generated from field: string bloomberg_ticker = 9;
   */
  bloombergTicker: string;

  /**
   * MSCI Security Code is a unique identifier assigned to each security by MSCI.
   *
   * @generated from field: string msci_sec_code = 10;
   */
  msciSecCode: string;

  /**
   * A Central Index Key or CIK number is a number given to an individual, company, or foreign government by
   * the United States Securities and Exchange Commission. The number is used to identify its filings in
   * several online databases, including EDGAR.
   *
   * @generated from field: string cik = 11;
   */
  cik: string;

  /**
   * InvestOne Id
   * InvestOne is an investment accounting solution for institutional asset managers.
   *
   * @generated from field: string invest_one = 12;
   */
  investOne: string;

  /**
   * Morningstar SecId
   *
   * @generated from field: string morningstar_sec_id = 13;
   */
  morningstarSecId: string;

  /**
   * Morningstar CompanyId
   *
   * @generated from field: string morningstar_company_id = 14;
   */
  morningstarCompanyId: string;

  /**
   * MCH Id
   * MCH (Multi-Currency Horizon) is an investment accounting solution for institutional asset managers.
   *
   * @generated from field: string mch = 15;
   */
  mch: string;

  /**
   * Multifonds Id
   * Multifonds is an investment accounting solution for institutional asset managers.
   *
   * @generated from field: string multifonds = 16;
   */
  multifonds: string;

  /**
   * Fundamental Id
   * Fundamental is an investment accounting solution for institutional asset managers.
   *
   * @generated from field: string fundamental = 17;
   */
  fundamental: string;

  /**
   * Morgan Stanley Id
   * Morgan Stanley is an investment trading solution provider for institutional asset managers.
   *
   * @generated from field: string morgan_stanley = 18;
   */
  morganStanley: string;

  /**
   * JSE Alpha Code
   * The ticker used by the Johannesburg Stock Exchange
   *
   * @generated from field: string jse_alpha_code = 19;
   */
  jseAlphaCode: string;

  /**
   * Refinitiv PermID
   * PermIDs are open, permanent and universal identifiers where underlying attributes capture the
   * context of the identity they each represent.
   * https://permid.org/
   *
   * @generated from field: string perm_id = 20;
   */
  permId: string;

  /**
   * Datastream Symbol
   *
   * @generated from field: string datastream_symbol = 21;
   */
  datastreamSymbol: string;

  /**
   * IEX Identifier
   *
   * @generated from field: string iex_id = 22;
   */
  iexId: string;

  /**
   * Portfolio Exchange Branch is the unique identifier keeping
   * track of tickerised Portfolio Branches.
   * A particular Portfolio Branch may be tickerised and created
   * as an instrument in IN. This identifier is used to link the
   * instrument bak to the Portfolio Branch in Portfolio Exchange.
   *
   * Format: "portfolios/{portfolioID}/branches/{branchID}"
   * Example: "portfolios/PXPK9F123456/branches/example_branch"
   *
   * @generated from field: string portfolio_exchange_branch = 23;
   */
  portfolioExchangeBranch: string;

  /**
   * Research Figi represents the instrument that should be referenced for investment research purposes.
   * For example: Even though the actual instrument that is held in a given portfolio is the ADR BBG013CYP248. The instrument to reference for investment research purposes should be the actual referenced Equity BBG000BC9LX8.
   *
   * @generated from field: string research_figi = 24;
   */
  researchFigi: string;
};

/**
 * Describes the message alis.open.in.v1.Instrument.ExternalIDs.
 * Use `create(Instrument_ExternalIDsSchema)` to create a new message.
 */
export declare const Instrument_ExternalIDsSchema: GenMessage<Instrument_ExternalIDs>;

/**
 * Exchange identifiers
 *
 * @generated from message alis.open.in.v1.Instrument.ExchangeIdentifiers
 */
export declare type Instrument_ExchangeIdentifiers = Message<"alis.open.in.v1.Instrument.ExchangeIdentifiers"> & {
  /**
   * Exchange MIC
   * The Market Identifier Code (MIC) (ISO 10383) is a unique identification code
   * used to identify securities trading exchanges, regulated and non-regulated
   * trading markets. The MIC is a four alphanumeric character code, and is
   * defined in ISO 10383.
   *
   * @generated from field: string mic = 1;
   */
  mic: string;

  /**
   * Exchange operating mic
   *
   * @generated from field: string operating_mic = 12;
   */
  operatingMic: string;

  /**
   * Bloomberg Exchange Code
   *
   * @generated from field: string bloomberg_exchange_code = 2;
   */
  bloombergExchangeCode: string;

  /**
   * Morningstar Exchange Code
   *
   * @generated from field: string morningstar_exchange_code = 3;
   */
  morningstarExchangeCode: string;
};

/**
 * Describes the message alis.open.in.v1.Instrument.ExchangeIdentifiers.
 * Use `create(Instrument_ExchangeIdentifiersSchema)` to create a new message.
 */
export declare const Instrument_ExchangeIdentifiersSchema: GenMessage<Instrument_ExchangeIdentifiers>;

/**
 * Instrument details required for common Alis Engines
 *
 * @generated from message alis.open.in.v1.Instrument.Engines
 */
export declare type Instrument_Engines = Message<"alis.open.in.v1.Instrument.Engines"> & {
  /**
   * Portfolio Exchange Engine details
   *
   * @generated from field: alis.open.px.v1.Instrument px = 1;
   */
  px?: Instrument$1;

  /**
   * Compliance Exchange Engine details
   *
   * @generated from field: alis.open.cx.v1.Instrument cx = 2;
   */
  cx?: Instrument$2;
};

/**
 * Describes the message alis.open.in.v1.Instrument.Engines.
 * Use `create(Instrument_EnginesSchema)` to create a new message.
 */
export declare const Instrument_EnginesSchema: GenMessage<Instrument_Engines>;

/**
 * This represents the attribute level source details
 *
 * @generated from message alis.open.in.v1.Instrument.SourceMetaData
 */
export declare type Instrument_SourceMetaData = Message<"alis.open.in.v1.Instrument.SourceMetaData"> & {
  /**
   * Source the attribute
   *
   * @generated from field: alis.open.in.v1.Source source = 1;
   */
  source: Source;

  /**
   * Time Updated
   *
   * @generated from field: google.protobuf.Timestamp update_time = 2;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message alis.open.in.v1.Instrument.SourceMetaData.
 * Use `create(Instrument_SourceMetaDataSchema)` to create a new message.
 */
export declare const Instrument_SourceMetaDataSchema: GenMessage<Instrument_SourceMetaData>;

/**
 * The instrument market sector
 * Consistent with the OpenFIGI definitions at https://www.openfigi.com/api/enumValues/v3/marketSecDes
 *
 * @generated from enum alis.open.in.v1.Instrument.MarketSector
 */
export enum Instrument_MarketSector {
  /**
   * Market Sector not specified
   *
   * @generated from enum value: MARKET_SECTOR_UNSPECIFIED = 0;
   */
  MARKET_SECTOR_UNSPECIFIED = 0,

  /**
   * Commodities
   *
   * @generated from enum value: COMMODITY = 1;
   */
  COMMODITY = 1,

  /**
   * Corporate Bonds
   *
   * @generated from enum value: CORPORATE = 2;
   */
  CORPORATE = 2,

  /**
   * Currency
   *
   * @generated from enum value: CURRENCY = 3;
   */
  CURRENCY = 3,

  /**
   * Equity
   *
   * @generated from enum value: EQUITY = 4;
   */
  EQUITY = 4,

  /**
   * Market index
   *
   * @generated from enum value: INDEX = 5;
   */
  INDEX = 5,

  /**
   * Money Market
   *
   * @generated from enum value: MONEY_MARKET = 6;
   */
  MONEY_MARKET = 6,

  /**
   * Government Bonds
   *
   * @generated from enum value: GOVERNMENT = 7;
   */
  GOVERNMENT = 7,

  /**
   * Mortgage Backed
   *
   * @generated from enum value: MTGE = 8;
   */
  MTGE = 8,

  /**
   * Municipal Bonds
   *
   * @generated from enum value: MUNI = 9;
   */
  MUNI = 9,

  /**
   * Preferred Stock
   *
   * @generated from enum value: PFD = 10;
   */
  PFD = 10,
}

/**
 * Describes the enum alis.open.in.v1.Instrument.MarketSector.
 */
export declare const Instrument_MarketSectorSchema: GenEnum<Instrument_MarketSector>;

/**
 * The FIGI type.
 *
 * @generated from enum alis.open.in.v1.FigiType
 */
export enum FigiType {
  /**
   * Figi Type is not provided
   *
   * @generated from enum value: FIGI_TYPE_UNSPECIFIED = 0;
   */
  FIGI_TYPE_UNSPECIFIED = 0,

  /**
   * Global FIGI
   *
   * @generated from enum value: GLOBAL = 1;
   */
  GLOBAL = 1,

  /**
   * Custom generated figi, not available on www.openfigi.com, yet...
   *
   * @generated from enum value: CUSTOM = 2;
   */
  CUSTOM = 2,
}

/**
 * Describes the enum alis.open.in.v1.FigiType.
 */
export declare const FigiTypeSchema: GenEnum<FigiType>;

/**
 * Data sources
 *
 * @generated from enum alis.open.in.v1.Source
 */
export enum Source {
  /**
   * Source not specified by the user.
   *
   * @generated from enum value: SOURCE_UNSPECIFIED = 0;
   */
  SOURCE_UNSPECIFIED = 0,

  /**
   * The user record.  This is used for fields with no source dimension.
   * All instruments will therefore have at least USER source entry.
   *
   * @generated from enum value: USER = 1;
   */
  USER = 1,

  /**
   * Openfigi
   *
   * @generated from enum value: OPENFIGI = 2;
   */
  OPENFIGI = 2,

  /**
   * PermID
   *
   * @generated from enum value: PERMID = 3;
   */
  PERMID = 3,

  /**
   * Datastream
   *
   * @generated from enum value: DATASTREAM = 4;
   */
  DATASTREAM = 4,

  /**
   * Bloomberg
   *
   * @generated from enum value: BLOOMBERG = 5;
   */
  BLOOMBERG = 5,

  /**
   * The originator of the instrument
   *
   * @generated from enum value: ORIGINATOR = 6;
   */
  ORIGINATOR = 6,

  /**
   * IEX
   * https://iexcloud.io
   *
   * @generated from enum value: IEX = 7;
   */
  IEX = 7,

  /**
   * Morningstar
   * https://edw.morningstar.com/Stock.aspx?ClientId=rezco
   * https://equityapi.morningstar.com/DataCatalog.aspx
   *
   * @generated from enum value: MORNINGSTAR = 8;
   */
  MORNINGSTAR = 8,

  /**
   * Source that utilises the existing instrument dataset and Generative AI to populate reference data.
   *
   * @generated from enum value: AI = 9;
   */
  AI = 9,
}

/**
 * Describes the enum alis.open.in.v1.Source.
 */
export declare const SourceSchema: GenEnum<Source>;

/**
 * The state of the instrument.
 *
 * @generated from enum alis.open.in.v1.State
 */
export enum State {
  /**
   * State not specified by the user.
   *
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * The instrument is active.
   *
   * @generated from enum value: ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * The instrument is archived. This state is specified if a user
   * has archived the instrument.
   *
   * @generated from enum value: ARCHIVED = 2;
   */
  ARCHIVED = 2,

  /**
   * The instrument is stale. This state is specified if IN
   * has not received an update for the instrument in a while.
   *
   * @generated from enum value: STALE = 3;
   */
  STALE = 3,
}

/**
 * Describes the enum alis.open.in.v1.State.
 */
export declare const StateSchema: GenEnum<State>;

