// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file alis/open/iam/v1/oauth.proto (package alis.open.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { IdentityProvider } from "./user_pb";
import type { Duration } from "../../../../google/protobuf/duration_pb";

/**
 * Describes the file alis/open/iam/v1/oauth.proto.
 */
export declare const file_alis_open_iam_v1_oauth: GenFile;

/**
 * Optional IAM config to use on a product deployment which, if set, will create an alis managed oauth reverse proxy endpoint
 * This endpoint can be used by backend-for-frontend services to authenticate users
 *
 * @generated from message alis.open.iam.v1.IamConfig
 */
export declare type IamConfig = Message<"alis.open.iam.v1.IamConfig"> & {
  /**
   * The set of valid oauth providers
   *
   * @generated from field: alis.open.iam.v1.IamConfig.AuthProviders auth_providers = 1;
   */
  authProviders?: IamConfig_AuthProviders;

  /**
   * Specification of self signup requirements
   *
   * If empty, then self signup is not allowed.
   *
   * @generated from field: alis.open.iam.v1.IamConfig.SelfSignupSpec self_signup_spec = 2;
   */
  selfSignupSpec?: IamConfig_SelfSignupSpec;

  /**
   * The uri to the logo to use on the signin & signup pages.
   * Suggested that the image has aspect ratio 1:1 (eg 32x32, 64x64, ...)
   * Format: https://...
   *
   * @generated from field: string logo_uri = 3;
   */
  logoUri: string;

  /**
   * Once a user has successfully been authenticated using the relevant
   * auth provider, various cookies will be set that will be used for
   * authenticating any calls that the user makes to the API.
   *
   * Cookies are set BY a specific host and FOR a specific domain.
   *
   * The host and domain combination can be best
   * explained using the following examples:
   *
   * 	 Host: app.example.com
   * 	 Domain: Unspecified
   * 		In this example, the authentication is hosted on
   * 		app.example.com and, since the domain is not
   * 		specified, the domain will default to the host. This means
   * 		that the auth cookies will only be valid for
   * 		app.example.com and can NOT be used by any other
   * 		domains, such as reports.example.com
   *
   * 	 Host: one.app.example.com
   * 	 Domain: app.example.com
   * 		In this example, the authentication is hosted on
   * 		one.app.example.com and the domain specified is one
   * 		level higher, ie. app.example.com. This means that
   * 		the auth cookies will be valid for <b>any</b> sub-domains of
   * 		app.example.com, such as
   * 		one.app.example.com, two.app.example.com,
   * 		anything.app.example.com.
   *      The cookies are however NOT valid for any other sub-domain of
   * 		example.com, such as reports.example.com
   *
   * 	 Host: abc.app.example.com
   * 	 Domain: example.com
   * 		In this example, the authentication is hosted on
   * 		abc.app.example.com and the domain specified is at
   * 		the top most level, ie. example.com. This means that
   * 		the auth cookies will be valid for <b>any</b> sub-domains of
   * 		example.com, such as abc.app.example.com,
   * 		xyz.app.example.com,
   * 		anything.app.example.com
   * 		As well as:
   * 		some.reports.example.com,
   * 		reports.example.com, example.com, etc.
   *
   * @generated from field: repeated alis.open.iam.v1.IamConfig.CookieDomain cookie_domains = 4;
   */
  cookieDomains: IamConfig_CookieDomain[];

  /**
   * The google group that all users that have Google as their identity provider are added to.
   * If empty, no group is used.
   * If specified, the members of this group will be kept in sync with the users that have Google as their identity provider.
   *
   * Example: builders@alis.exchange
   *
   * @generated from field: string google_group = 5;
   */
  googleGroup: string;
};

/**
 * Describes the message alis.open.iam.v1.IamConfig.
 * Use `create(IamConfigSchema)` to create a new message.
 */
export declare const IamConfigSchema: GenMessage<IamConfig>;

/**
 * Definition of the Oauth providers for the Config
 *
 * @generated from message alis.open.iam.v1.IamConfig.AuthProviders
 */
export declare type IamConfig_AuthProviders = Message<"alis.open.iam.v1.IamConfig.AuthProviders"> & {
  /**
   * Google oauth provider
   *
   * @generated from field: alis.open.iam.v1.OauthProvider google = 1;
   */
  google?: OauthProvider;

  /**
   * Microsoft oauth provider
   *
   * @generated from field: alis.open.iam.v1.OauthProvider microsoft = 2;
   */
  microsoft?: OauthProvider;

  /**
   * Email auth provider
   *
   * @generated from field: alis.open.iam.v1.EmailAuthProvider email = 3;
   */
  email?: EmailAuthProvider;

  /**
   * Linked auth provider
   *
   * @generated from field: alis.open.iam.v1.OauthProvider linkedin = 4;
   */
  linkedin?: OauthProvider;

  /**
   * Apple auth provider
   *
   * @generated from field: alis.open.iam.v1.AppleAuthProvider apple = 5;
   */
  apple?: AppleAuthProvider;
};

/**
 * Describes the message alis.open.iam.v1.IamConfig.AuthProviders.
 * Use `create(IamConfig_AuthProvidersSchema)` to create a new message.
 */
export declare const IamConfig_AuthProvidersSchema: GenMessage<IamConfig_AuthProviders>;

/**
 * The description of self signup
 *
 * @generated from message alis.open.iam.v1.IamConfig.SelfSignupSpec
 */
export declare type IamConfig_SelfSignupSpec = Message<"alis.open.iam.v1.IamConfig.SelfSignupSpec"> & {
  /**
   * The domains and associated providers (optional)
   * which are allowed to self signup.
   *
   * If no DomainProviders are specified, self signup is not allowed.
   *
   * @generated from field: repeated alis.open.iam.v1.IamConfig.SelfSignupSpec.DomainProvider domain_providers = 1;
   */
  domainProviders: IamConfig_SelfSignupSpec_DomainProvider[];

  /**
   * The default roles assigned to a user when they self sign up
   * Format: ["roles/*", ...]
   *
   * @generated from field: repeated string default_roles = 2;
   */
  defaultRoles: string[];
};

/**
 * Describes the message alis.open.iam.v1.IamConfig.SelfSignupSpec.
 * Use `create(IamConfig_SelfSignupSpecSchema)` to create a new message.
 */
export declare const IamConfig_SelfSignupSpecSchema: GenMessage<IamConfig_SelfSignupSpec>;

/**
 * Definition of a Domain Provider that allows
 * a mapping between a domain and Identity Provider.
 *
 * This allows auto redirect to the relevant IdP when a user
 * from the specific domain signs up
 *
 * @generated from message alis.open.iam.v1.IamConfig.SelfSignupSpec.DomainProvider
 */
export declare type IamConfig_SelfSignupSpec_DomainProvider = Message<"alis.open.iam.v1.IamConfig.SelfSignupSpec.DomainProvider"> & {
  /**
   * The relevant domain which is allowed to self signup
   * "*" indicates all domains are allowed.
   *
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * The associated Identity Provider (IdP)
   *
   * In the case that the IdP is:
   * 	UNSPECIFIED - will provide options of available IdPs for sign up
   * 	(Any specified) - will automatically redirect to the relevant IdP for sign up
   *
   * In the case that the domain is specified as '*'
   * then this field needs to be UNSPECIFIED
   *
   * @generated from field: alis.open.iam.v1.IdentityProvider identity_provider = 2;
   */
  identityProvider: IdentityProvider;

  /**
   * Whether to force users to provide their credentials when signing in.
   *
   * The default (false) behaviour is that users are allowed to select
   * and account from a corporate identity for which they are already
   * signed in for. Some organisations may however require users to
   * follow an entire authentication flow when signing in,
   * rather than just selecting the relevant account from the
   * already signed in corporate identities.
   *
   * @generated from field: bool force_login = 3;
   */
  forceLogin: boolean;
};

/**
 * Describes the message alis.open.iam.v1.IamConfig.SelfSignupSpec.DomainProvider.
 * Use `create(IamConfig_SelfSignupSpec_DomainProviderSchema)` to create a new message.
 */
export declare const IamConfig_SelfSignupSpec_DomainProviderSchema: GenMessage<IamConfig_SelfSignupSpec_DomainProvider>;

/**
 * The definition of the cookie domain
 *
 * @generated from message alis.open.iam.v1.IamConfig.CookieDomain
 */
export declare type IamConfig_CookieDomain = Message<"alis.open.iam.v1.IamConfig.CookieDomain"> & {
  /**
   * The host refers to the sub-domain which will
   * the authentication, ie. require users to sign in or sign up.
   *
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * The domain refers to the domain for
   * which the auth cookies are valid.
   *
   * By default, the domain is set to the host, but may
   * be specified to use a higher level domain.
   *
   * @generated from field: string domain = 2;
   */
  domain: string;

  /**
   * The same site setting to use for the refresh_token and id_token cookies.
   * If none is specified, lax is used.
   * For embedded applications, like the excel addin, none must be used.
   *
   * @generated from field: alis.open.iam.v1.IamConfig.CookieDomain.SameSite same_site = 3;
   */
  sameSite: IamConfig_CookieDomain_SameSite;
};

/**
 * Describes the message alis.open.iam.v1.IamConfig.CookieDomain.
 * Use `create(IamConfig_CookieDomainSchema)` to create a new message.
 */
export declare const IamConfig_CookieDomainSchema: GenMessage<IamConfig_CookieDomain>;

/**
 * The enum for the SameSite setting
 *
 * @generated from enum alis.open.iam.v1.IamConfig.CookieDomain.SameSite
 */
export enum IamConfig_CookieDomain_SameSite {
  /**
   * Unspecified
   *
   * @generated from enum value: SAME_SITE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The cookie is sent in the request
   * if the request is for the same site
   * as the cookie.
   *
   * @generated from enum value: SAME_SITE_STRICT = 1;
   */
  STRICT = 1,

  /**
   * The cookie is sent in the request
   * if the request is for the same site
   * as the cookie, or if the request is
   * from a top-level navigation.
   *
   * @generated from enum value: SAME_SITE_LAX = 2;
   */
  LAX = 2,

  /**
   * The cookie is sent in the request
   * regardless of the site.
   *
   * @generated from enum value: SAME_SITE_NONE = 3;
   */
  NONE = 3,
}

/**
 * Describes the enum alis.open.iam.v1.IamConfig.CookieDomain.SameSite.
 */
export declare const IamConfig_CookieDomain_SameSiteSchema: GenEnum<IamConfig_CookieDomain_SameSite>;

/**
 * The UI config is used by the Vue Console to dynamically configure the UI
 *
 * TODO: Ruan to populate
 *
 * @generated from message alis.open.iam.v1.UiConfig
 */
export declare type UiConfig = Message<"alis.open.iam.v1.UiConfig"> & {
};

/**
 * Describes the message alis.open.iam.v1.UiConfig.
 * Use `create(UiConfigSchema)` to create a new message.
 */
export declare const UiConfigSchema: GenMessage<UiConfig>;

/**
 * Definition of an OAuth provider
 *
 * @generated from message alis.open.iam.v1.OauthProvider
 */
export declare type OauthProvider = Message<"alis.open.iam.v1.OauthProvider"> & {
  /**
   * The client id of the oauth provider.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * The client secret of the oauth provider.
   *
   * @generated from field: string client_secret = 2;
   */
  clientSecret: string;
};

/**
 * Describes the message alis.open.iam.v1.OauthProvider.
 * Use `create(OauthProviderSchema)` to create a new message.
 */
export declare const OauthProviderSchema: GenMessage<OauthProvider>;

/**
 * Email provider
 *
 * @generated from message alis.open.iam.v1.EmailAuthProvider
 */
export declare type EmailAuthProvider = Message<"alis.open.iam.v1.EmailAuthProvider"> & {
  /**
   * The email address that the email will be received _from_.
   * E.g. noreply@alis.build
   *
   * @generated from field: string from_email = 1;
   */
  fromEmail: string;

  /**
   * In order to enable sign up using email, a server is required
   * to send the emails on your behalf.
   *
   * @generated from field: alis.open.iam.v1.EmailAuthProvider.Server server = 2;
   */
  server?: EmailAuthProvider_Server;

  /**
   * The time that needs to pass before a user can request another email.
   * Default is none, but highly recommended to set to prevent spam.
   *
   * @generated from field: google.protobuf.Duration throttle_duration = 3;
   */
  throttleDuration?: Duration;

  /**
   * The duration that a user must is auto signed in for after clicking the sign in link.
   * This corresponds directly to the expiry date on the refresh token.
   * If not set, a user is signed in for 8 hours.
   *
   * @generated from field: google.protobuf.Duration signed_in_duration = 4;
   */
  signedInDuration?: Duration;
};

/**
 * Describes the message alis.open.iam.v1.EmailAuthProvider.
 * Use `create(EmailAuthProviderSchema)` to create a new message.
 */
export declare const EmailAuthProviderSchema: GenMessage<EmailAuthProvider>;

/**
 * The available servers.
 *
 * @generated from message alis.open.iam.v1.EmailAuthProvider.Server
 */
export declare type EmailAuthProvider_Server = Message<"alis.open.iam.v1.EmailAuthProvider.Server"> & {
  /**
   * Usage of the SendGrid Email API to send
   * through the sign in information.
   *
   * @generated from field: alis.open.iam.v1.EmailAuthProvider.Sendgrid sendgrid = 1;
   */
  sendgrid?: EmailAuthProvider_Sendgrid;
};

/**
 * Describes the message alis.open.iam.v1.EmailAuthProvider.Server.
 * Use `create(EmailAuthProvider_ServerSchema)` to create a new message.
 */
export declare const EmailAuthProvider_ServerSchema: GenMessage<EmailAuthProvider_Server>;

/**
 * Definition of the Sendgrid email server
 *
 * @generated from message alis.open.iam.v1.EmailAuthProvider.Sendgrid
 */
export declare type EmailAuthProvider_Sendgrid = Message<"alis.open.iam.v1.EmailAuthProvider.Sendgrid"> & {
  /**
   * The SendGrid API key to use.
   *
   * The key should be created (https://app.sendgrid.com/settings/api_keys)
   * to have Restriced Access and needs to have the following permissions:
   *   - Mail Send
   *
   * @generated from field: string api_key = 1;
   */
  apiKey: string;

  /**
   * The template to use for sending the email
   *
   * @generated from oneof alis.open.iam.v1.EmailAuthProvider.Sendgrid.template
   */
  template: {
    /**
     * The SendGrid Dynamic Template ID to use.
     * Create template at https://mc.sendgrid.com/dynamic-templates.
     *
     * In order for the template to work, it should include
     * the following data variables:
     *   - data.signInUrl
     *
     * The `data.signInUrl` can be added to a button for example that
     * allows the user to click to.
     *
     * TODO: other templates like html
     *
     * @generated from field: string dynamic_template_id = 2;
     */
    value: string;
    case: "dynamicTemplateId";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message alis.open.iam.v1.EmailAuthProvider.Sendgrid.
 * Use `create(EmailAuthProvider_SendgridSchema)` to create a new message.
 */
export declare const EmailAuthProvider_SendgridSchema: GenMessage<EmailAuthProvider_Sendgrid>;

/**
 * Apple provider
 *
 * @generated from message alis.open.iam.v1.AppleAuthProvider
 */
export declare type AppleAuthProvider = Message<"alis.open.iam.v1.AppleAuthProvider"> & {
  /**
   * The team id of the apple provider.
   *
   * @generated from field: string team_id = 1;
   */
  teamId: string;

  /**
   * The client id of the oauth provider.
   *
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * The client secret of the oauth provider.
   *
   * @generated from field: string client_secret = 3;
   */
  clientSecret: string;

  /**
   * The key id of the private/secret key.
   *
   * @generated from field: string key_id = 4;
   */
  keyId: string;
};

/**
 * Describes the message alis.open.iam.v1.AppleAuthProvider.
 * Use `create(AppleAuthProviderSchema)` to create a new message.
 */
export declare const AppleAuthProviderSchema: GenMessage<AppleAuthProvider>;

/**
 * Structure of the alis.build generated refresh token
 *
 * @generated from message alis.open.iam.v1.RefreshToken
 */
export declare type RefreshToken = Message<"alis.open.iam.v1.RefreshToken"> & {
  /**
   * The provider's refresh token
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * The provider
   *
   * @generated from field: alis.open.iam.v1.IdentityProvider provider = 2;
   */
  provider: IdentityProvider;

  /**
   * The redirect uri used to get the refresh token
   *
   * @generated from field: string redirect_uri = 3;
   */
  redirectUri: string;
};

/**
 * Describes the message alis.open.iam.v1.RefreshToken.
 * Use `create(RefreshTokenSchema)` to create a new message.
 */
export declare const RefreshTokenSchema: GenMessage<RefreshToken>;

