// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file alis/open/iam/v1/user.proto (package alis.open.iam.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RetrieveRulesRequest, RetrieveRulesResponse, ValidateMessageRequest, ValidateMessageResponse } from "../../validation/v1/validation_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { GetIamPolicyRequest, SetIamPolicyRequest, TestIamPermissionsRequest, TestIamPermissionsResponse } from "@alis-build/google-common-protos/google/iam/v1/iam_policy_pb.js";
import { Policy } from "@alis-build/google-common-protos/google/iam/v1/policy_pb.js";
import { AddIamBindingsRequest, RemoveIamBindingsRequest } from "./iam_pb.js";
import { BatchRetrieveMaskedUsersRequest, BatchRetrieveMaskedUsersResponse, CreateUserRequest, DeleteUserRequest, EditMyInfoRequest, EditMyMetadataRequest, EditUserInfoRequest, EditUserMetadataRequest, GetUserRequest, ListUsersRequest, ListUsersResponse, LookupUserRequest, LookupUserResponse, MaskedUser, RemoveMyUserRequest, RetrieveMaskedUserRequest, RetrieveMaskedUsersRequest, RetrieveMaskedUsersResponse, RetrieveMyUserRequest, RetrieveUserByEmailRequest, SetUserPictureRequest, SetUserPictureResponse, SyncToGoogleGroupRequest, SyncToGoogleGroupResponse, UpdateUserRequest, User } from "./user_pb.js";
import { Empty } from "@alis-build/google-common-protos/google/protobuf/empty_pb.js";

/**
 * UsersService provides RPCs for managing User resources.
 *
 * @generated from service alis.open.iam.v1.UsersService
 */
export const UsersService = {
  typeName: "alis.open.iam.v1.UsersService",
  methods: {
    /**
     * Validates any proto message that is used directly or indirectly by this service.
     * Most common use case is to validate request messages from a client-side application.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.ValidateMessage
     */
    validateMessage: {
      name: "ValidateMessage",
      I: ValidateMessageRequest,
      O: ValidateMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
     * Serves as live auto-documentation of the validation rules in this service.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RetrieveRules
     */
    retrieveRules: {
      name: "RetrieveRules",
      I: RetrieveRulesRequest,
      O: RetrieveRulesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets the IAM policy for a resource implemented in this service.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.GetIamPolicy
     */
    getIamPolicy: {
      name: "GetIamPolicy",
      I: GetIamPolicyRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Sets the IAM policy for a resource implemented in this service.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.SetIamPolicy
     */
    setIamPolicy: {
      name: "SetIamPolicy",
      I: SetIamPolicyRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Returns permissions that a caller has on the specified resource.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.TestIamPermissions
     */
    testIamPermissions: {
      name: "TestIamPermissions",
      I: TestIamPermissionsRequest,
      O: TestIamPermissionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.AddIamBindings
     */
    addIamBindings: {
      name: "AddIamBindings",
      I: AddIamBindingsRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Removes principals or some of the roles they have on an IAM Policy protected resource.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RemoveIamBindings
     */
    removeIamBindings: {
      name: "RemoveIamBindings",
      I: RemoveIamBindingsRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Gets information about a User.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new User.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a User.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a User.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Lists Users. Results are sorted by name, ascending.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieve a User by their email.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RetrieveUserByEmail
     */
    retrieveUserByEmail: {
      name: "RetrieveUserByEmail",
      I: RetrieveUserByEmailRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Look up a User based on a search text.
     *
     * This method retrieves a set of results, which are Users, based on the request.
     * The lookup for these Users are done across the given_name, family_name, email and contact number.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.LookupUser
     */
    lookupUser: {
      name: "LookupUser",
      I: LookupUserRequest,
      O: LookupUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves the set of Users requested, with only a
     * subset of the User information returned.
     *
     * This is equivalent to a BatchGet method, but only a subset of the User information,
     * which does not contain any sensitive information such as email or group configurations.
     *
     * Differs from the RetrieveMaskedUsers method in that it returns only
     * the Users that were specified in the request.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.BatchRetrieveMaskedUsers
     */
    batchRetrieveMaskedUsers: {
      name: "BatchRetrieveMaskedUsers",
      I: BatchRetrieveMaskedUsersRequest,
      O: BatchRetrieveMaskedUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves all Users that match the filter criteria, if specified,
     * with only a subset of the User information.
     *
     * This is equivalent to a List method, but only a subset of the User information,
     * which does not contain any sensitive information such as email or group configurations.
     *
     * Differs from the BatchRetrieveMaskedUsers method in that it returns all
     * the Users that match the filter, if the filter is specified.
     *
     * This is useful for displaying a list of Users without revealing sensitive information like email.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RetrieveMaskedUsers
     */
    retrieveMaskedUsers: {
      name: "RetrieveMaskedUsers",
      I: RetrieveMaskedUsersRequest,
      O: RetrieveMaskedUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a User with some of their details hidden.
     * This is useful for displaying a User without revealing sensitive information like email.
     * Both name and email can be used to retrieve the User.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RetrieveMaskedUser
     */
    retrieveMaskedUser: {
      name: "RetrieveMaskedUser",
      I: RetrieveMaskedUserRequest,
      O: MaskedUser,
      kind: MethodKind.Unary,
    },
    /**
     * Edits a User's non-auth related information like family name and picture.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.EditUserInfo
     */
    editUserInfo: {
      name: "EditUserInfo",
      I: EditUserInfoRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Edits a User's metadata
     *
     * @generated from rpc alis.open.iam.v1.UsersService.EditUserMetadata
     */
    editUserMetadata: {
      name: "EditUserMetadata",
      I: EditUserMetadataRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves the currently signed in user.
     * This is useful for client-side applications to get the signed in user's information.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RetrieveMyUser
     */
    retrieveMyUser: {
      name: "RetrieveMyUser",
      I: RetrieveMyUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Edits the info of the currently signed in user.
     * This is useful for client-side applications to edit the signed in user's information.
     * Allows the user to edit their given_name, family_name, picture, contact_number, position, education, linkedin_uri and metadata.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.EditMyInfo
     */
    editMyInfo: {
      name: "EditMyInfo",
      I: EditMyInfoRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Edits the metadata of the currently signed in user.
     * This is useful for client-side applications to edit the signed in user's metadata.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.EditMyMetadata
     */
    editMyMetadata: {
      name: "EditMyMetadata",
      I: EditMyMetadataRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Removes the currently signed in user.
     * This is useful if a user wants to delete their account.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.RemoveMyUser
     */
    removeMyUser: {
      name: "RemoveMyUser",
      I: RemoveMyUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Syncs all google User's to the google group configured in the IamConfig.
     * Will not delete service accounts.
     *
     * @generated from rpc alis.open.iam.v1.UsersService.SyncToGoogleGroup
     */
    syncToGoogleGroup: {
      name: "SyncToGoogleGroup",
      I: SyncToGoogleGroupRequest,
      O: SyncToGoogleGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sets the user's profile picture
     *
     * @generated from rpc alis.open.iam.v1.UsersService.SetUserPicture
     */
    setUserPicture: {
      name: "SetUserPicture",
      I: SetUserPictureRequest,
      O: SetUserPictureResponse,
      kind: MethodKind.Unary,
    },
  }
};
