// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file alis/open/iam/v1/user.proto (package alis.open.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Any } from "@alis-build/google-common-protos/google/protobuf/any_pb";
import type { Timestamp } from "@alis-build/google-common-protos/google/protobuf/timestamp_pb";
import type { FieldMask } from "@alis-build/google-common-protos/google/protobuf/field_mask_pb";
import type { RetrieveRulesRequestSchema, RetrieveRulesResponseSchema, ValidateMessageRequestSchema, ValidateMessageResponseSchema } from "../../validation/v1/validation_pb";
import type { GetIamPolicyRequestSchema, SetIamPolicyRequestSchema, TestIamPermissionsRequestSchema, TestIamPermissionsResponseSchema } from "@alis-build/google-common-protos/google/iam/v1/iam_policy_pb";
import type { PolicySchema } from "@alis-build/google-common-protos/google/iam/v1/policy_pb";
import type { AddIamBindingsRequestSchema, RemoveIamBindingsRequestSchema } from "./iam_pb";
import type { EmptySchema } from "@alis-build/google-common-protos/google/protobuf/empty_pb";

/**
 * Describes the file alis/open/iam/v1/user.proto.
 */
export declare const file_alis_open_iam_v1_user: GenFile;

/**
 * The request message for the `UploadImage` method.
 *
 * @generated from message alis.open.iam.v1.SetUserPictureRequest
 */
export declare type SetUserPictureRequest = Message<"alis.open.iam.v1.SetUserPictureRequest"> & {
  /**
   * The user to set the picture for
   * Format: users/*
   *
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * The image data as bytes.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * The image mime type.
   *
   * The current types supported are:
   * - image/jpeg,
   * - image/jpg
   * - image/png,
   *
   * @generated from field: string mime_type = 3;
   */
  mimeType: string;
};

/**
 * Describes the message alis.open.iam.v1.SetUserPictureRequest.
 * Use `create(SetUserPictureRequestSchema)` to create a new message.
 */
export declare const SetUserPictureRequestSchema: GenMessage<SetUserPictureRequest>;

/**
 * The response message for the `UploadImage` method.
 *
 * @generated from message alis.open.iam.v1.SetUserPictureResponse
 */
export declare type SetUserPictureResponse = Message<"alis.open.iam.v1.SetUserPictureResponse"> & {
  /**
   * The uri link to the original image.
   *
   * @generated from field: string public_uri = 1;
   */
  publicUri: string;
};

/**
 * Describes the message alis.open.iam.v1.SetUserPictureResponse.
 * Use `create(SetUserPictureResponseSchema)` to create a new message.
 */
export declare const SetUserPictureResponseSchema: GenMessage<SetUserPictureResponse>;

/**
 * A User of a deployment
 *
 * @generated from message alis.open.iam.v1.User
 */
export declare type User = Message<"alis.open.iam.v1.User"> & {
  /**
   * The unique name of the User which cannot be changed.
   * Format: users/([a-z0-9-]{2,50})
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The email of the User.
   *
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * The given name of the User
   *
   * @generated from field: string given_name = 7;
   */
  givenName: string;

  /**
   * The family name of the User
   *
   * @generated from field: string family_name = 8;
   */
  familyName: string;

  /**
   * The picture of the User
   * Format: https://...
   *
   * @generated from field: string picture = 9;
   */
  picture: string;

  /**
   * The contact number of the User
   *
   * @generated from field: string contact_number = 10;
   */
  contactNumber: string;

  /**
   * Current position
   * Example: Senior Build Engineer at Alis Exchange.
   *
   * @generated from field: string position = 13;
   */
  position: string;

  /**
   * Education
   * Example: PhD in Astrophysics
   *
   * @generated from field: string education = 14;
   */
  education: string;

  /**
   * LinkedIn profile
   * Example: https://www.linkedin.com/in/jankrynauw/
   *
   * @generated from field: string linkedin_uri = 15;
   */
  linkedinUri: string;

  /**
   * Whether the User's email has been verified.
   * The email might be masked if synched from alis but the User has not signed in yet.
   * The email might also be unverified if the User self-signed up with email but has not
   * yet signed in with a link sent to their email.
   *
   * @generated from field: bool verified_email = 5;
   */
  verifiedEmail: boolean;

  /**
   * The default identity provider of the User
   * When a user enters their email to sign in, the default identity provider is used to redirect them
   * or send them an email link.
   *
   * @generated from field: alis.open.iam.v1.IdentityProvider identity_provider = 6;
   */
  identityProvider: IdentityProvider;

  /**
   * The last google group (if any) that the User was synched to.
   * This field is used to track if there are any Users that have not yet been
   * successfully synched to the relevant google group since it was added/changed in the config
   *
   * @generated from field: string google_group = 12;
   */
  googleGroup: string;

  /**
   * Any metadata about the User. The user can edit this using EditMyInfo.
   *
   * @generated from field: google.protobuf.Any metadata = 11;
   */
  metadata?: Any;

  /**
   * Any internal metadata about the User. The user can not edit this, but can see it.
   *
   * @generated from field: google.protobuf.Any internal_metadata = 19;
   */
  internalMetadata?: Any;

  /**
   * The creation time of the User.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 2;
   */
  createTime?: Timestamp;

  /**
   * The last time the User was updated.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 3;
   */
  updateTime?: Timestamp;

  /**
   * The last time the user signed in.
   * This does not include refreshing of tokens.
   *
   * @generated from field: google.protobuf.Timestamp last_sign_in_time = 16;
   */
  lastSignInTime?: Timestamp;

  /**
   * The last time the user's access token was refreshed.
   * Since this is done every 5 minutes, it is a good indicator of the user's activity.
   *
   * @generated from field: google.protobuf.Timestamp last_refresh_time = 20;
   */
  lastRefreshTime?: Timestamp;

  /**
   * The google identity of the user if any.
   *
   * @generated from field: alis.open.iam.v1.User.GoogleIdentity google_identity = 17;
   */
  googleIdentity?: User_GoogleIdentity;

  /**
   * The microsoft identity of the user if any.
   *
   * @generated from field: alis.open.iam.v1.User.MicrosoftIdentity microsoft_identity = 18;
   */
  microsoftIdentity?: User_MicrosoftIdentity;

  /**
   * The linkedin identity of the user if any.
   *
   * @generated from field: alis.open.iam.v1.User.LinkedinIdentity linkedin_identity = 21;
   */
  linkedinIdentity?: User_LinkedinIdentity;

  /**
   * The subscriptions that the user is part of
   *
   * @generated from field: repeated alis.open.iam.v1.User.Subscription subscriptions = 22;
   */
  subscriptions: User_Subscription[];

  /**
   * The ids of the groups the user is part of
   *
   * @generated from field: repeated string group_ids = 23;
   */
  groupIds: string[];

  /**
   * The apple identity of the user if any.
   *
   * @generated from field: alis.open.iam.v1.User.AppleIdentity apple_identity = 24;
   */
  appleIdentity?: User_AppleIdentity;

  /**
   * The details of each account this user belongs to if multiple accounts are
   * supported. Key is the account id.
   *
   * @generated from field: map<string, alis.open.iam.v1.User.Account> accounts = 99;
   */
  accounts: { [key: string]: User_Account };

  /**
   * Entity tag
   *
   * @generated from field: string etag = 97;
   */
  etag: string;
};

/**
 * Describes the message alis.open.iam.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export declare const UserSchema: GenMessage<User>;

/**
 * Definition of Google Identity
 *
 * @generated from message alis.open.iam.v1.User.GoogleIdentity
 */
export declare type User_GoogleIdentity = Message<"alis.open.iam.v1.User.GoogleIdentity"> & {
  /**
   * The google id of the user.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message alis.open.iam.v1.User.GoogleIdentity.
 * Use `create(User_GoogleIdentitySchema)` to create a new message.
 */
export declare const User_GoogleIdentitySchema: GenMessage<User_GoogleIdentity>;

/**
 * Definition of Microsoft Identity
 *
 * @generated from message alis.open.iam.v1.User.MicrosoftIdentity
 */
export declare type User_MicrosoftIdentity = Message<"alis.open.iam.v1.User.MicrosoftIdentity"> & {
  /**
   * The microsoft id of the user.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message alis.open.iam.v1.User.MicrosoftIdentity.
 * Use `create(User_MicrosoftIdentitySchema)` to create a new message.
 */
export declare const User_MicrosoftIdentitySchema: GenMessage<User_MicrosoftIdentity>;

/**
 * Definition of Linkedin Identity
 *
 * @generated from message alis.open.iam.v1.User.LinkedinIdentity
 */
export declare type User_LinkedinIdentity = Message<"alis.open.iam.v1.User.LinkedinIdentity"> & {
  /**
   * The linkedin id of the user.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message alis.open.iam.v1.User.LinkedinIdentity.
 * Use `create(User_LinkedinIdentitySchema)` to create a new message.
 */
export declare const User_LinkedinIdentitySchema: GenMessage<User_LinkedinIdentity>;

/**
 * Definition of Subscription
 *
 * @generated from message alis.open.iam.v1.User.Subscription
 */
export declare type User_Subscription = Message<"alis.open.iam.v1.User.Subscription"> & {
  /**
   * The name of the subscription
   * Format: accounts/*\/customers/*\/subscriptions/*
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The code of the plan that is part of the subscription
   *
   * @generated from field: string plan = 2;
   */
  plan: string;
};

/**
 * Describes the message alis.open.iam.v1.User.Subscription.
 * Use `create(User_SubscriptionSchema)` to create a new message.
 */
export declare const User_SubscriptionSchema: GenMessage<User_Subscription>;

/**
 * Definition of Apple Identity
 *
 * @generated from message alis.open.iam.v1.User.AppleIdentity
 */
export declare type User_AppleIdentity = Message<"alis.open.iam.v1.User.AppleIdentity"> & {
  /**
   * The apple id of the user.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message alis.open.iam.v1.User.AppleIdentity.
 * Use `create(User_AppleIdentitySchema)` to create a new message.
 */
export declare const User_AppleIdentitySchema: GenMessage<User_AppleIdentity>;

/**
 * @generated from message alis.open.iam.v1.User.Account
 */
export declare type User_Account = Message<"alis.open.iam.v1.User.Account"> & {
  /**
   * The seat the user has for each of the product's offerings.
   *
   * @generated from field: map<int32, alis.open.iam.v1.User.Account.Seat> seats = 1;
   */
  seats: { [key: number]: User_Account_Seat };
};

/**
 * Describes the message alis.open.iam.v1.User.Account.
 * Use `create(User_AccountSchema)` to create a new message.
 */
export declare const User_AccountSchema: GenMessage<User_Account>;

/**
 * A seat
 *
 * @generated from message alis.open.iam.v1.User.Account.Seat
 */
export declare type User_Account_Seat = Message<"alis.open.iam.v1.User.Account.Seat"> & {
  /**
   * The plan of the account for this offering.
   *
   * @generated from field: int32 plan = 1;
   */
  plan: number;

  /**
   * The seat the user has for this offering.
   *
   * @generated from field: int32 seat = 2;
   */
  seat: number;
};

/**
 * Describes the message alis.open.iam.v1.User.Account.Seat.
 * Use `create(User_Account_SeatSchema)` to create a new message.
 */
export declare const User_Account_SeatSchema: GenMessage<User_Account_Seat>;

/**
 * The request message for the GetUser method.
 *
 * @generated from message alis.open.iam.v1.GetUserRequest
 */
export declare type GetUserRequest = Message<"alis.open.iam.v1.GetUserRequest"> & {
  /**
   * The unique name of the User.
   * Format: users/([a-z0-9-]{2,50})
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The fields to return in snake_case.
   * All fields are returned if not set.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 2;
   */
  readMask?: FieldMask;
};

/**
 * Describes the message alis.open.iam.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export declare const GetUserRequestSchema: GenMessage<GetUserRequest>;

/**
 * The request message for the CreateUser method.
 *
 * @generated from message alis.open.iam.v1.CreateUserRequest
 */
export declare type CreateUserRequest = Message<"alis.open.iam.v1.CreateUserRequest"> & {
  /**
   * The user to create
   * Email is the only required field.
   *
   * @generated from field: alis.open.iam.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message alis.open.iam.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export declare const CreateUserRequestSchema: GenMessage<CreateUserRequest>;

/**
 * Request message for the UpdateUser method.
 *
 * @generated from message alis.open.iam.v1.UpdateUserRequest
 */
export declare type UpdateUserRequest = Message<"alis.open.iam.v1.UpdateUserRequest"> & {
  /**
   * The user to update
   *
   * @generated from field: alis.open.iam.v1.User user = 1;
   */
  user?: User;

  /**
   * The set of fields that should be updated
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message alis.open.iam.v1.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export declare const UpdateUserRequestSchema: GenMessage<UpdateUserRequest>;

/**
 * The request message for the DeleteUser method.
 *
 * @generated from message alis.open.iam.v1.DeleteUserRequest
 */
export declare type DeleteUserRequest = Message<"alis.open.iam.v1.DeleteUserRequest"> & {
  /**
   * The unique name of the User.
   * Format: users/([a-z0-9-]{2,50})
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message alis.open.iam.v1.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export declare const DeleteUserRequestSchema: GenMessage<DeleteUserRequest>;

/**
 * The request message for the ListUsers method.
 *
 * @generated from message alis.open.iam.v1.ListUsersRequest
 */
export declare type ListUsersRequest = Message<"alis.open.iam.v1.ListUsersRequest"> & {
  /**
   * The maximum number of Users to return.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token, received from a previous ListUsers call.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * The fields to return in snake_case.
   * All fields are returned if not set.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 4;
   */
  readMask?: FieldMask;

  /**
   * The filter to apply.
   *
   * @generated from field: string filter = 5;
   */
  filter: string;
};

/**
 * Describes the message alis.open.iam.v1.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export declare const ListUsersRequestSchema: GenMessage<ListUsersRequest>;

/**
 * The response message for the ListUsers method.
 *
 * @generated from message alis.open.iam.v1.ListUsersResponse
 */
export declare type ListUsersResponse = Message<"alis.open.iam.v1.ListUsersResponse"> & {
  /**
   * The Users.
   *
   * @generated from field: repeated alis.open.iam.v1.User users = 1;
   */
  users: User[];

  /**
   * A token to retrieve the next page of results.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message alis.open.iam.v1.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export declare const ListUsersResponseSchema: GenMessage<ListUsersResponse>;

/**
 * The request message for the RetrieveUserByEmail method.
 *
 * @generated from message alis.open.iam.v1.RetrieveUserByEmailRequest
 */
export declare type RetrieveUserByEmailRequest = Message<"alis.open.iam.v1.RetrieveUserByEmailRequest"> & {
  /**
   * The email of the User.
   *
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * The fields to return in snake_case.
   * All fields are returned if not set.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 2;
   */
  readMask?: FieldMask;
};

/**
 * Describes the message alis.open.iam.v1.RetrieveUserByEmailRequest.
 * Use `create(RetrieveUserByEmailRequestSchema)` to create a new message.
 */
export declare const RetrieveUserByEmailRequestSchema: GenMessage<RetrieveUserByEmailRequest>;

/**
 * Request message for the BatchRetrieveMaskedUsers method.
 *
 * @generated from message alis.open.iam.v1.BatchRetrieveMaskedUsersRequest
 */
export declare type BatchRetrieveMaskedUsersRequest = Message<"alis.open.iam.v1.BatchRetrieveMaskedUsersRequest"> & {
  /**
   * The names of the Users to retrieve.
   * A maximum of 1000 Users can be retrieved in a single batch.
   * Format: [users/*, users/*, ...]
   *
   * @generated from field: repeated string users = 1;
   */
  users: string[];

  /**
   * Fields to retrieve from the Resource. Defaults to all fields.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 2;
   */
  readMask?: FieldMask;
};

/**
 * Describes the message alis.open.iam.v1.BatchRetrieveMaskedUsersRequest.
 * Use `create(BatchRetrieveMaskedUsersRequestSchema)` to create a new message.
 */
export declare const BatchRetrieveMaskedUsersRequestSchema: GenMessage<BatchRetrieveMaskedUsersRequest>;

/**
 * Response message for the BatchRetrieveMaskedUsers method.
 *
 * @generated from message alis.open.iam.v1.BatchRetrieveMaskedUsersResponse
 */
export declare type BatchRetrieveMaskedUsersResponse = Message<"alis.open.iam.v1.BatchRetrieveMaskedUsersResponse"> & {
  /**
   * The list of Users.
   *
   * @generated from field: repeated alis.open.iam.v1.MaskedUser masked_users = 1;
   */
  maskedUsers: MaskedUser[];
};

/**
 * Describes the message alis.open.iam.v1.BatchRetrieveMaskedUsersResponse.
 * Use `create(BatchRetrieveMaskedUsersResponseSchema)` to create a new message.
 */
export declare const BatchRetrieveMaskedUsersResponseSchema: GenMessage<BatchRetrieveMaskedUsersResponse>;

/**
 * Request message for the LookupUser method.
 *
 * @generated from message alis.open.iam.v1.LookupUserRequest
 */
export declare type LookupUserRequest = Message<"alis.open.iam.v1.LookupUserRequest"> & {
  /**
   * The text that will be used to filter the set of Users.
   *
   * Example: "rua"
   * Will attempt to get all the Users that contain
   * the text 'rua' across the various fields in
   * the User resource
   *
   * @generated from field: string search_text = 1;
   */
  searchText: string;
};

/**
 * Describes the message alis.open.iam.v1.LookupUserRequest.
 * Use `create(LookupUserRequestSchema)` to create a new message.
 */
export declare const LookupUserRequestSchema: GenMessage<LookupUserRequest>;

/**
 * Response message for the LookupUser method.
 *
 * @generated from message alis.open.iam.v1.LookupUserResponse
 */
export declare type LookupUserResponse = Message<"alis.open.iam.v1.LookupUserResponse"> & {
  /**
   * The list of results which match the search text
   *
   * @generated from field: repeated alis.open.iam.v1.LookupUserResponse.Result results = 1;
   */
  results: LookupUserResponse_Result[];
};

/**
 * Describes the message alis.open.iam.v1.LookupUserResponse.
 * Use `create(LookupUserResponseSchema)` to create a new message.
 */
export declare const LookupUserResponseSchema: GenMessage<LookupUserResponse>;

/**
 * Definition of a result
 *
 * @generated from message alis.open.iam.v1.LookupUserResponse.Result
 */
export declare type LookupUserResponse_Result = Message<"alis.open.iam.v1.LookupUserResponse.Result"> & {
  /**
   * The full name of the User
   *
   * Format: users/{user}
   *
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * The display name of the User.
   * Concatenated given_name and family_name
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Masked primary email address
   * Eg. ru***@alisx.com
   *
   * @generated from field: string masked_email = 3;
   */
  maskedEmail: string;
};

/**
 * Describes the message alis.open.iam.v1.LookupUserResponse.Result.
 * Use `create(LookupUserResponse_ResultSchema)` to create a new message.
 */
export declare const LookupUserResponse_ResultSchema: GenMessage<LookupUserResponse_Result>;

/**
 * The request message for the RetrieveMaskedUsers method.
 *
 * @generated from message alis.open.iam.v1.RetrieveMaskedUsersRequest
 */
export declare type RetrieveMaskedUsersRequest = Message<"alis.open.iam.v1.RetrieveMaskedUsersRequest"> & {
  /**
   * The maximum number of Users to return.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token, received from a previous RetrieveMaskedUsers call.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * The fields to return in snake_case.
   * All fields are returned if not set.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 4;
   */
  readMask?: FieldMask;

  /**
   * The filter to apply.
   *
   * @generated from field: string filter = 5;
   */
  filter: string;
};

/**
 * Describes the message alis.open.iam.v1.RetrieveMaskedUsersRequest.
 * Use `create(RetrieveMaskedUsersRequestSchema)` to create a new message.
 */
export declare const RetrieveMaskedUsersRequestSchema: GenMessage<RetrieveMaskedUsersRequest>;

/**
 * The response message for the RetrieveMaskedUsers method.
 *
 * @generated from message alis.open.iam.v1.RetrieveMaskedUsersResponse
 */
export declare type RetrieveMaskedUsersResponse = Message<"alis.open.iam.v1.RetrieveMaskedUsersResponse"> & {
  /**
   * The Users with their emails masked.
   *
   * @generated from field: repeated alis.open.iam.v1.MaskedUser users = 1;
   */
  users: MaskedUser[];

  /**
   * A token to retrieve the next page of results.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message alis.open.iam.v1.RetrieveMaskedUsersResponse.
 * Use `create(RetrieveMaskedUsersResponseSchema)` to create a new message.
 */
export declare const RetrieveMaskedUsersResponseSchema: GenMessage<RetrieveMaskedUsersResponse>;

/**
 * The request message for the RetrieveMaskedUser method.
 *
 * @generated from message alis.open.iam.v1.RetrieveMaskedUserRequest
 */
export declare type RetrieveMaskedUserRequest = Message<"alis.open.iam.v1.RetrieveMaskedUserRequest"> & {
  /**
   * @generated from oneof alis.open.iam.v1.RetrieveMaskedUserRequest.identifier
   */
  identifier: {
    /**
     * The unique name of the User.
     * Format: users/([a-z0-9-]{2,50})
     *
     * @generated from field: string user = 1;
     */
    value: string;
    case: "user";
  } | {
    /**
     * The email of the User.
     *
     * @generated from field: string email = 2;
     */
    value: string;
    case: "email";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message alis.open.iam.v1.RetrieveMaskedUserRequest.
 * Use `create(RetrieveMaskedUserRequestSchema)` to create a new message.
 */
export declare const RetrieveMaskedUserRequestSchema: GenMessage<RetrieveMaskedUserRequest>;

/**
 * A User of a deployment with their email masked.
 *
 * @generated from message alis.open.iam.v1.MaskedUser
 */
export declare type MaskedUser = Message<"alis.open.iam.v1.MaskedUser"> & {
  /**
   * The unique name of the User which cannot be changed.
   * Format: users/([a-z0-9-]{2,50})
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The creation time of the User.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 2;
   */
  createTime?: Timestamp;

  /**
   * The last time the User was updated.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 3;
   */
  updateTime?: Timestamp;

  /**
   * The email of the User. Alis will never overwrite this field.
   *
   * @generated from field: string masked_email = 4;
   */
  maskedEmail: string;

  /**
   * The identity provider of the User.
   *
   * @generated from field: alis.open.iam.v1.IdentityProvider identity_provider = 6;
   */
  identityProvider: IdentityProvider;

  /**
   * The given name of the User.
   *
   * @generated from field: string given_name = 7;
   */
  givenName: string;

  /**
   * The family name of the User.
   *
   * @generated from field: string family_name = 8;
   */
  familyName: string;

  /**
   * The picture of the User.
   * Format: https://...
   *
   * @generated from field: string picture = 9;
   */
  picture: string;

  /**
   * Current position
   * Example: Senior Build Engineer at Alis Exchange.
   *
   * @generated from field: string position = 10;
   */
  position: string;

  /**
   * Education
   * Example: PhD in Astrophysics
   *
   * @generated from field: string education = 11;
   */
  education: string;

  /**
   * LinkedIn profile
   * Example: https://www.linkedin.com/in/jankrynauw/
   *
   * @generated from field: string linkedin_uri = 12;
   */
  linkedinUri: string;
};

/**
 * Describes the message alis.open.iam.v1.MaskedUser.
 * Use `create(MaskedUserSchema)` to create a new message.
 */
export declare const MaskedUserSchema: GenMessage<MaskedUser>;

/**
 * The request message for the EditUserInfo method.
 *
 * @generated from message alis.open.iam.v1.EditUserInfoRequest
 */
export declare type EditUserInfoRequest = Message<"alis.open.iam.v1.EditUserInfoRequest"> & {
  /**
   * The unique name of the User.
   * Format: users/([a-z0-9-]{2,50})
   *
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * The given name of the User
   *
   * @generated from field: string given_name = 2;
   */
  givenName: string;

  /**
   * The family name of the User
   *
   * @generated from field: string family_name = 3;
   */
  familyName: string;

  /**
   * The profile picture of the User
   * Format: https://...
   *
   * @generated from field: string picture = 4;
   */
  picture: string;

  /**
   * The contact number of the User
   *
   * @generated from field: string contact_number = 5;
   */
  contactNumber: string;

  /**
   * Current position
   * Example: Senior Build Engineer at Alis Exchange.
   *
   * @generated from field: string position = 6;
   */
  position: string;

  /**
   * Education
   * Example: PhD in Astrophysics
   *
   * @generated from field: string education = 7;
   */
  education: string;

  /**
   * LinkedIn profile
   * Example: https://www.linkedin.com/in/jankrynauw/
   *
   * @generated from field: string linkedin_uri = 8;
   */
  linkedinUri: string;

  /**
   * The set of fields that should be updated
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message alis.open.iam.v1.EditUserInfoRequest.
 * Use `create(EditUserInfoRequestSchema)` to create a new message.
 */
export declare const EditUserInfoRequestSchema: GenMessage<EditUserInfoRequest>;

/**
 * The request message for the EditUserMetadata method.
 *
 * @generated from message alis.open.iam.v1.EditUserMetadataRequest
 */
export declare type EditUserMetadataRequest = Message<"alis.open.iam.v1.EditUserMetadataRequest"> & {
  /**
   * The unique name of the User.
   * Format: users/([a-z0-9-]{2,50})
   *
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * The metadata to update.
   *
   * @generated from field: google.protobuf.Any metadata = 2;
   */
  metadata?: Any;
};

/**
 * Describes the message alis.open.iam.v1.EditUserMetadataRequest.
 * Use `create(EditUserMetadataRequestSchema)` to create a new message.
 */
export declare const EditUserMetadataRequestSchema: GenMessage<EditUserMetadataRequest>;

/**
 * The request message for the RetrieveMyUser method.
 *
 * @generated from message alis.open.iam.v1.RetrieveMyUserRequest
 */
export declare type RetrieveMyUserRequest = Message<"alis.open.iam.v1.RetrieveMyUserRequest"> & {
};

/**
 * Describes the message alis.open.iam.v1.RetrieveMyUserRequest.
 * Use `create(RetrieveMyUserRequestSchema)` to create a new message.
 */
export declare const RetrieveMyUserRequestSchema: GenMessage<RetrieveMyUserRequest>;

/**
 * The request message for the EditMyInfo method.
 *
 * @generated from message alis.open.iam.v1.EditMyInfoRequest
 */
export declare type EditMyInfoRequest = Message<"alis.open.iam.v1.EditMyInfoRequest"> & {
  /**
   * The given name of the User
   *
   * @generated from field: string given_name = 1;
   */
  givenName: string;

  /**
   * The family name of the User
   *
   * @generated from field: string family_name = 2;
   */
  familyName: string;

  /**
   * The profile picture of the User
   * Format: https://...
   *
   * @generated from field: string picture = 3;
   */
  picture: string;

  /**
   * The contact number of the User
   *
   * @generated from field: string contact_number = 4;
   */
  contactNumber: string;

  /**
   * Current position
   * Example: Senior Build Engineer at Alis Exchange.
   *
   * @generated from field: string position = 5;
   */
  position: string;

  /**
   * Education
   * Example: PhD in Astrophysics
   *
   * @generated from field: string education = 6;
   */
  education: string;

  /**
   * LinkedIn profile
   * Example: https://www.linkedin.com/in/jankrynauw/
   *
   * @generated from field: string linkedin_uri = 7;
   */
  linkedinUri: string;

  /**
   * The set of fields that should be updated
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 10;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message alis.open.iam.v1.EditMyInfoRequest.
 * Use `create(EditMyInfoRequestSchema)` to create a new message.
 */
export declare const EditMyInfoRequestSchema: GenMessage<EditMyInfoRequest>;

/**
 * The request message for the EditMyMetadata method.
 *
 * @generated from message alis.open.iam.v1.EditMyMetadataRequest
 */
export declare type EditMyMetadataRequest = Message<"alis.open.iam.v1.EditMyMetadataRequest"> & {
  /**
   * The metadata to update.
   *
   * @generated from field: google.protobuf.Any metadata = 1;
   */
  metadata?: Any;
};

/**
 * Describes the message alis.open.iam.v1.EditMyMetadataRequest.
 * Use `create(EditMyMetadataRequestSchema)` to create a new message.
 */
export declare const EditMyMetadataRequestSchema: GenMessage<EditMyMetadataRequest>;

/**
 * The request message for the RemoveMyUser method.
 *
 * @generated from message alis.open.iam.v1.RemoveMyUserRequest
 */
export declare type RemoveMyUserRequest = Message<"alis.open.iam.v1.RemoveMyUserRequest"> & {
};

/**
 * Describes the message alis.open.iam.v1.RemoveMyUserRequest.
 * Use `create(RemoveMyUserRequestSchema)` to create a new message.
 */
export declare const RemoveMyUserRequestSchema: GenMessage<RemoveMyUserRequest>;

/**
 * The request message for the SyncToGoogleGroup method.
 *
 * @generated from message alis.open.iam.v1.SyncToGoogleGroupRequest
 */
export declare type SyncToGoogleGroupRequest = Message<"alis.open.iam.v1.SyncToGoogleGroupRequest"> & {
};

/**
 * Describes the message alis.open.iam.v1.SyncToGoogleGroupRequest.
 * Use `create(SyncToGoogleGroupRequestSchema)` to create a new message.
 */
export declare const SyncToGoogleGroupRequestSchema: GenMessage<SyncToGoogleGroupRequest>;

/**
 * The response message for the SyncToGoogleGroup method.
 *
 * @generated from message alis.open.iam.v1.SyncToGoogleGroupResponse
 */
export declare type SyncToGoogleGroupResponse = Message<"alis.open.iam.v1.SyncToGoogleGroupResponse"> & {
  /**
   * The number of Users that were added.
   *
   * @generated from field: int32 nr_added = 1;
   */
  nrAdded: number;

  /**
   * The number of Users that were removed.
   *
   * @generated from field: int32 nr_removed = 2;
   */
  nrRemoved: number;
};

/**
 * Describes the message alis.open.iam.v1.SyncToGoogleGroupResponse.
 * Use `create(SyncToGoogleGroupResponseSchema)` to create a new message.
 */
export declare const SyncToGoogleGroupResponseSchema: GenMessage<SyncToGoogleGroupResponse>;

/**
 * Available identity providers.
 *
 * @generated from enum alis.open.iam.v1.IdentityProvider
 */
export enum IdentityProvider {
  /**
   * Unspecified identity provider.
   *
   * @generated from enum value: IDENTITY_PROVIDER_UNSPECIFIED = 0;
   */
  IDENTITY_PROVIDER_UNSPECIFIED = 0,

  /**
   * Google identity provider.
   *
   * @generated from enum value: GOOGLE = 1;
   */
  GOOGLE = 1,

  /**
   * Microsoft identity provider.
   *
   * @generated from enum value: MICROSOFT = 2;
   */
  MICROSOFT = 2,

  /**
   * Email identity provider.
   *
   * @generated from enum value: EMAIL = 3;
   */
  EMAIL = 3,

  /**
   * LinkedIn identity provider.
   *
   * @generated from enum value: LINKEDIN = 4;
   */
  LINKEDIN = 4,

  /**
   * Apple identity provider.
   *
   * @generated from enum value: APPLE = 5;
   */
  APPLE = 5,
}

/**
 * Describes the enum alis.open.iam.v1.IdentityProvider.
 */
export declare const IdentityProviderSchema: GenEnum<IdentityProvider>;

/**
 * UsersService provides RPCs for managing User resources.
 *
 * @generated from service alis.open.iam.v1.UsersService
 */
export declare const UsersService: GenService<{
  /**
   * Validates any proto message that is used directly or indirectly by this service.
   * Most common use case is to validate request messages from a client-side application.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.ValidateMessage
   */
  validateMessage: {
    methodKind: "unary";
    input: typeof ValidateMessageRequestSchema;
    output: typeof ValidateMessageResponseSchema;
  },
  /**
   * Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
   * Serves as live auto-documentation of the validation rules in this service.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RetrieveRules
   */
  retrieveRules: {
    methodKind: "unary";
    input: typeof RetrieveRulesRequestSchema;
    output: typeof RetrieveRulesResponseSchema;
  },
  /**
   * Gets the IAM policy for a resource implemented in this service.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.GetIamPolicy
   */
  getIamPolicy: {
    methodKind: "unary";
    input: typeof GetIamPolicyRequestSchema;
    output: typeof PolicySchema;
  },
  /**
   * Sets the IAM policy for a resource implemented in this service.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.SetIamPolicy
   */
  setIamPolicy: {
    methodKind: "unary";
    input: typeof SetIamPolicyRequestSchema;
    output: typeof PolicySchema;
  },
  /**
   * Returns permissions that a caller has on the specified resource.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.TestIamPermissions
   */
  testIamPermissions: {
    methodKind: "unary";
    input: typeof TestIamPermissionsRequestSchema;
    output: typeof TestIamPermissionsResponseSchema;
  },
  /**
   * Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.AddIamBindings
   */
  addIamBindings: {
    methodKind: "unary";
    input: typeof AddIamBindingsRequestSchema;
    output: typeof PolicySchema;
  },
  /**
   * Removes principals or some of the roles they have on an IAM Policy protected resource.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RemoveIamBindings
   */
  removeIamBindings: {
    methodKind: "unary";
    input: typeof RemoveIamBindingsRequestSchema;
    output: typeof PolicySchema;
  },
  /**
   * Gets information about a User.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Creates a new User.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Updates a User.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Deletes a User.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Lists Users. Results are sorted by name, ascending.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUsersRequestSchema;
    output: typeof ListUsersResponseSchema;
  },
  /**
   * Retrieve a User by their email.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RetrieveUserByEmail
   */
  retrieveUserByEmail: {
    methodKind: "unary";
    input: typeof RetrieveUserByEmailRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Look up a User based on a search text.
   *
   * This method retrieves a set of results, which are Users, based on the request.
   * The lookup for these Users are done across the given_name, family_name, email and contact number.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.LookupUser
   */
  lookupUser: {
    methodKind: "unary";
    input: typeof LookupUserRequestSchema;
    output: typeof LookupUserResponseSchema;
  },
  /**
   * Retrieves the set of Users requested, with only a
   * subset of the User information returned.
   *
   * This is equivalent to a BatchGet method, but only a subset of the User information,
   * which does not contain any sensitive information such as email or group configurations.
   *
   * Differs from the RetrieveMaskedUsers method in that it returns only
   * the Users that were specified in the request.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.BatchRetrieveMaskedUsers
   */
  batchRetrieveMaskedUsers: {
    methodKind: "unary";
    input: typeof BatchRetrieveMaskedUsersRequestSchema;
    output: typeof BatchRetrieveMaskedUsersResponseSchema;
  },
  /**
   * Retrieves all Users that match the filter criteria, if specified,
   * with only a subset of the User information.
   *
   * This is equivalent to a List method, but only a subset of the User information,
   * which does not contain any sensitive information such as email or group configurations.
   *
   * Differs from the BatchRetrieveMaskedUsers method in that it returns all
   * the Users that match the filter, if the filter is specified.
   *
   * This is useful for displaying a list of Users without revealing sensitive information like email.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RetrieveMaskedUsers
   */
  retrieveMaskedUsers: {
    methodKind: "unary";
    input: typeof RetrieveMaskedUsersRequestSchema;
    output: typeof RetrieveMaskedUsersResponseSchema;
  },
  /**
   * Retrieves a User with some of their details hidden.
   * This is useful for displaying a User without revealing sensitive information like email.
   * Both name and email can be used to retrieve the User.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RetrieveMaskedUser
   */
  retrieveMaskedUser: {
    methodKind: "unary";
    input: typeof RetrieveMaskedUserRequestSchema;
    output: typeof MaskedUserSchema;
  },
  /**
   * Edits a User's non-auth related information like family name and picture.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.EditUserInfo
   */
  editUserInfo: {
    methodKind: "unary";
    input: typeof EditUserInfoRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Edits a User's metadata
   *
   * @generated from rpc alis.open.iam.v1.UsersService.EditUserMetadata
   */
  editUserMetadata: {
    methodKind: "unary";
    input: typeof EditUserMetadataRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Retrieves the currently signed in user.
   * This is useful for client-side applications to get the signed in user's information.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RetrieveMyUser
   */
  retrieveMyUser: {
    methodKind: "unary";
    input: typeof RetrieveMyUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Edits the info of the currently signed in user.
   * This is useful for client-side applications to edit the signed in user's information.
   * Allows the user to edit their given_name, family_name, picture, contact_number, position, education, linkedin_uri and metadata.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.EditMyInfo
   */
  editMyInfo: {
    methodKind: "unary";
    input: typeof EditMyInfoRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Edits the metadata of the currently signed in user.
   * This is useful for client-side applications to edit the signed in user's metadata.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.EditMyMetadata
   */
  editMyMetadata: {
    methodKind: "unary";
    input: typeof EditMyMetadataRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * Removes the currently signed in user.
   * This is useful if a user wants to delete their account.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.RemoveMyUser
   */
  removeMyUser: {
    methodKind: "unary";
    input: typeof RemoveMyUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Syncs all google User's to the google group configured in the IamConfig.
   * Will not delete service accounts.
   *
   * @generated from rpc alis.open.iam.v1.UsersService.SyncToGoogleGroup
   */
  syncToGoogleGroup: {
    methodKind: "unary";
    input: typeof SyncToGoogleGroupRequestSchema;
    output: typeof SyncToGoogleGroupResponseSchema;
  },
  /**
   * Sets the user's profile picture
   *
   * @generated from rpc alis.open.iam.v1.UsersService.SetUserPicture
   */
  setUserPicture: {
    methodKind: "unary";
    input: typeof SetUserPictureRequestSchema;
    output: typeof SetUserPictureResponseSchema;
  },
}>;
