// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file google/iam/v1/iam_policy.proto (package google.iam.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../api/annotations_pb";
import { file_google_api_client } from "../../api/client_pb";
import { file_google_api_field_behavior } from "../../api/field_behavior_pb";
import { file_google_api_resource } from "../../api/resource_pb";
import { file_google_iam_v1_options } from "./options_pb";
import { file_google_iam_v1_policy } from "./policy_pb";
import { file_google_protobuf_field_mask } from "../../protobuf/field_mask_pb";

/**
 * Describes the file google/iam/v1/iam_policy.proto.
 */
export const file_google_iam_v1_iam_policy = /*@__PURE__*/
  fileDesc("Ch5nb29nbGUvaWFtL3YxL2lhbV9wb2xpY3kucHJvdG8SDWdvb2dsZS5pYW0udjEikQEKE1NldElhbVBvbGljeVJlcXVlc3QSHAoIcmVzb3VyY2UYASABKAlCCuJBAQL6QQMKASoSKwoGcG9saWN5GAIgASgLMhUuZ29vZ2xlLmlhbS52MS5Qb2xpY3lCBOJBAQISLwoLdXBkYXRlX21hc2sYAyABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrImUKE0dldElhbVBvbGljeVJlcXVlc3QSHAoIcmVzb3VyY2UYASABKAlCCuJBAQL6QQMKASoSMAoHb3B0aW9ucxgCIAEoCzIfLmdvb2dsZS5pYW0udjEuR2V0UG9saWN5T3B0aW9ucyJUChlUZXN0SWFtUGVybWlzc2lvbnNSZXF1ZXN0EhwKCHJlc291cmNlGAEgASgJQgriQQEC+kEDCgEqEhkKC3Blcm1pc3Npb25zGAIgAygJQgTiQQECIjEKGlRlc3RJYW1QZXJtaXNzaW9uc1Jlc3BvbnNlEhMKC3Blcm1pc3Npb25zGAEgAygJMrQDCglJQU1Qb2xpY3kSdAoMU2V0SWFtUG9saWN5EiIuZ29vZ2xlLmlhbS52MS5TZXRJYW1Qb2xpY3lSZXF1ZXN0GhUuZ29vZ2xlLmlhbS52MS5Qb2xpY3kiKYLT5JMCIyIeL3YxL3tyZXNvdXJjZT0qKn06c2V0SWFtUG9saWN5OgEqEnQKDEdldElhbVBvbGljeRIiLmdvb2dsZS5pYW0udjEuR2V0SWFtUG9saWN5UmVxdWVzdBoVLmdvb2dsZS5pYW0udjEuUG9saWN5IimC0+STAiMiHi92MS97cmVzb3VyY2U9Kip9OmdldElhbVBvbGljeToBKhKaAQoSVGVzdElhbVBlcm1pc3Npb25zEiguZ29vZ2xlLmlhbS52MS5UZXN0SWFtUGVybWlzc2lvbnNSZXF1ZXN0GikuZ29vZ2xlLmlhbS52MS5UZXN0SWFtUGVybWlzc2lvbnNSZXNwb25zZSIvgtPkkwIpIiQvdjEve3Jlc291cmNlPSoqfTp0ZXN0SWFtUGVybWlzc2lvbnM6ASoaHspBG2lhbS1tZXRhLWFwaS5nb29nbGVhcGlzLmNvbUKGAQoRY29tLmdvb2dsZS5pYW0udjFCDklhbVBvbGljeVByb3RvUAFaMGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvaWFtL3YxO2lhbfgBAaoCE0dvb2dsZS5DbG91ZC5JYW0uVjHKAhNHb29nbGVcQ2xvdWRcSWFtXFYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_api_resource, file_google_iam_v1_options, file_google_iam_v1_policy, file_google_protobuf_field_mask]);

/**
 * Describes the message google.iam.v1.SetIamPolicyRequest.
 * Use `create(SetIamPolicyRequestSchema)` to create a new message.
 */
export const SetIamPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_google_iam_v1_iam_policy, 0);

/**
 * Describes the message google.iam.v1.GetIamPolicyRequest.
 * Use `create(GetIamPolicyRequestSchema)` to create a new message.
 */
export const GetIamPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_google_iam_v1_iam_policy, 1);

/**
 * Describes the message google.iam.v1.TestIamPermissionsRequest.
 * Use `create(TestIamPermissionsRequestSchema)` to create a new message.
 */
export const TestIamPermissionsRequestSchema = /*@__PURE__*/
  messageDesc(file_google_iam_v1_iam_policy, 2);

/**
 * Describes the message google.iam.v1.TestIamPermissionsResponse.
 * Use `create(TestIamPermissionsResponseSchema)` to create a new message.
 */
export const TestIamPermissionsResponseSchema = /*@__PURE__*/
  messageDesc(file_google_iam_v1_iam_policy, 3);

/**
 * API Overview
 *
 *
 * Manages Identity and Access Management (IAM) policies.
 *
 * Any implementation of an API that offers access control features
 * implements the google.iam.v1.IAMPolicy interface.
 *
 * ## Data model
 *
 * Access control is applied when a principal (user or service account), takes
 * some action on a resource exposed by a service. Resources, identified by
 * URI-like names, are the unit of access control specification. Service
 * implementations can choose the granularity of access control and the
 * supported permissions for their resources.
 * For example one database service may allow access control to be
 * specified only at the Table level, whereas another might allow access control
 * to also be specified at the Column level.
 *
 * ## Policy Structure
 *
 * See google.iam.v1.Policy
 *
 * This is intentionally not a CRUD style API because access control policies
 * are created and deleted implicitly with the resources to which they are
 * attached.
 *
 * @generated from service google.iam.v1.IAMPolicy
 */
export const IAMPolicy = /*@__PURE__*/
  serviceDesc(file_google_iam_v1_iam_policy, 0);
