// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file alis/open/support/v1/attachments.proto (package alis.open.support.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file alis/open/support/v1/attachments.proto.
 */
export declare const file_alis_open_support_v1_attachments: GenFile;

/**
 * The request message for the `UploadImage` method.
 *
 * @generated from message alis.open.support.v1.UploadImageRequest
 */
export declare type UploadImageRequest = Message<"alis.open.support.v1.UploadImageRequest"> & {
  /**
   * The image data as bytes.
   *
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;

  /**
   * The image mime type.
   *
   * The current types supported are:
   * - image/jpeg,
   * - image/jpg
   * - image/x-png,
   * - image/png,
   * - image/gif
   *
   * @generated from field: string mime_type = 2;
   */
  mimeType: string;
};

/**
 * Describes the message alis.open.support.v1.UploadImageRequest.
 * Use `create(UploadImageRequestSchema)` to create a new message.
 */
export declare const UploadImageRequestSchema: GenMessage<UploadImageRequest>;

/**
 * The response message for the `UploadImage` method.
 *
 * @generated from message alis.open.support.v1.UploadImageResponse
 */
export declare type UploadImageResponse = Message<"alis.open.support.v1.UploadImageResponse"> & {
  /**
   * The uri link to the original image.
   *
   * @generated from field: string public_uri = 1;
   */
  publicUri: string;
};

/**
 * Describes the message alis.open.support.v1.UploadImageResponse.
 * Use `create(UploadImageResponseSchema)` to create a new message.
 */
export declare const UploadImageResponseSchema: GenMessage<UploadImageResponse>;

/**
 * The service that manages uploading public attachments for use
 * in the context of Support resources.
 *
 * @generated from service alis.open.support.v1.PublicAttachmentsService
 */
export declare const PublicAttachmentsService: GenService<{
  /**
   * Upload an image attachment of a maximum 4mb.
   *
   * @generated from rpc alis.open.support.v1.PublicAttachmentsService.UploadImage
   */
  uploadImage: {
    methodKind: "unary";
    input: typeof UploadImageRequestSchema;
    output: typeof UploadImageResponseSchema;
  },
}>;

