// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file alis/open/support/v1/events.proto (package alis.open.support.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PubSubMessage } from "../../pubsub/v1/pubsub_pb.js";
import { Empty } from "../../../../google/protobuf/empty_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service for handling events.
 *
 * @generated from service alis.open.support.v1.EventsService
 */
export declare const EventsService: {
  readonly typeName: "alis.open.support.v1.EventsService",
  readonly methods: {
    /**
     * Handles an event from pubsub.
     *
     * @generated from rpc alis.open.support.v1.EventsService.HandleEvent
     */
    readonly handleEvent: {
      readonly name: "HandleEvent",
      readonly I: typeof PubSubMessage,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

