// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file alis/open/support/v1/guide.proto (package alis.open.support.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@alis-build/google-common-protos/google/protobuf/timestamp_pb";
import type { FieldMask } from "@alis-build/google-common-protos/google/protobuf/field_mask_pb";
import type { RetrieveRulesRequestSchema, RetrieveRulesResponseSchema, ValidateMessageRequestSchema, ValidateMessageResponseSchema } from "../../validation/v1/validation_pb";

/**
 * Describes the file alis/open/support/v1/guide.proto.
 */
export declare const file_alis_open_support_v1_guide: GenFile;

/**
 * A Guide represents preemptive support that is provided
 * by the Product team to aid users in their usage of the Product.
 *
 * @generated from message alis.open.support.v1.Guide
 */
export declare type Guide = Message<"alis.open.support.v1.Guide"> & {
  /**
   * The name of the guide
   * Format: guides/*
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Title of the Guide
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * The subtitle of the Guide
   *
   * @generated from field: string subtitle = 3;
   */
  subtitle: string;

  /**
   * The Guide contents
   *
   * @generated from field: repeated alis.open.support.v1.Guide.ContentBlock contents = 5;
   */
  contents: Guide_ContentBlock[];

  /**
   * Time the page was created
   *
   * @generated from field: google.protobuf.Timestamp create_time = 98;
   */
  createTime?: Timestamp;

  /**
   * Time the page was updated
   *
   * @generated from field: google.protobuf.Timestamp update_time = 99;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message alis.open.support.v1.Guide.
 * Use `create(GuideSchema)` to create a new message.
 */
export declare const GuideSchema: GenMessage<Guide>;

/**
 * A ContentBlock defines various content types
 * that may be used as part of the Guides.
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock
 */
export declare type Guide_ContentBlock = Message<"alis.open.support.v1.Guide.ContentBlock"> & {
  /**
   * The type of the content block
   *
   * @generated from field: alis.open.support.v1.Guide.ContentBlock.Type type = 1;
   */
  type: Guide_ContentBlock_Type;

  /**
   * The block containing the content
   *
   * @generated from oneof alis.open.support.v1.Guide.ContentBlock.block
   */
  block: {
    /**
     * A title
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Title title = 2;
     */
    value: Guide_ContentBlock_Title;
    case: "title";
  } | {
    /**
     * A Subtitle
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Subtitle subtitle = 3;
     */
    value: Guide_ContentBlock_Subtitle;
    case: "subtitle";
  } | {
    /**
     * A heading
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Heading heading = 4;
     */
    value: Guide_ContentBlock_Heading;
    case: "heading";
  } | {
    /**
     * Body text
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.TextBody text_body = 5;
     */
    value: Guide_ContentBlock_TextBody;
    case: "textBody";
  } | {
    /**
     * A standalone image
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Image image = 6;
     */
    value: Guide_ContentBlock_Image;
    case: "image";
  } | {
    /**
     * A standalone video
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Video video = 7;
     */
    value: Guide_ContentBlock_Video;
    case: "video";
  } | {
    /**
     * A divider which can be used to seperate elements of the page.
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Divider divider = 8;
     */
    value: Guide_ContentBlock_Divider;
    case: "divider";
  } | {
    /**
     * Provides a user-specified preview of a URL
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.LinkPreview link_preview = 9;
     */
    value: Guide_ContentBlock_LinkPreview;
    case: "linkPreview";
  } | {
    /**
     * Footnote that can be placed at the end of a section
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Footnote footnote = 10;
     */
    value: Guide_ContentBlock_Footnote;
    case: "footnote";
  } | {
    /**
     * A diagram, specified using valid syntax
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.Diagram diagram = 11;
     */
    value: Guide_ContentBlock_Diagram;
    case: "diagram";
  } | {
    /**
     * A syntax-highlighted code block for the set of supported languages
     *
     * @generated from field: alis.open.support.v1.Guide.ContentBlock.CodeBlock code_block = 12;
     */
    value: Guide_ContentBlock_CodeBlock;
    case: "codeBlock";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.
 * Use `create(Guide_ContentBlockSchema)` to create a new message.
 */
export declare const Guide_ContentBlockSchema: GenMessage<Guide_ContentBlock>;

/**
 * A title
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Title
 */
export declare type Guide_ContentBlock_Title = Message<"alis.open.support.v1.Guide.ContentBlock.Title"> & {
  /**
   * The title text content
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Title.
 * Use `create(Guide_ContentBlock_TitleSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_TitleSchema: GenMessage<Guide_ContentBlock_Title>;

/**
 * A Subtitle
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Subtitle
 */
export declare type Guide_ContentBlock_Subtitle = Message<"alis.open.support.v1.Guide.ContentBlock.Subtitle"> & {
  /**
   * The subtitle text content
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Subtitle.
 * Use `create(Guide_ContentBlock_SubtitleSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_SubtitleSchema: GenMessage<Guide_ContentBlock_Subtitle>;

/**
 * A Heading
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Heading
 */
export declare type Guide_ContentBlock_Heading = Message<"alis.open.support.v1.Guide.ContentBlock.Heading"> & {
  /**
   * The heading text content
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Heading.
 * Use `create(Guide_ContentBlock_HeadingSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_HeadingSchema: GenMessage<Guide_ContentBlock_Heading>;

/**
 * Body text
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.TextBody
 */
export declare type Guide_ContentBlock_TextBody = Message<"alis.open.support.v1.Guide.ContentBlock.TextBody"> & {
  /**
   * The text body content
   * Supports standard markdown format.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.TextBody.
 * Use `create(Guide_ContentBlock_TextBodySchema)` to create a new message.
 */
export declare const Guide_ContentBlock_TextBodySchema: GenMessage<Guide_ContentBlock_TextBody>;

/**
 * A standalone image
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Image
 */
export declare type Guide_ContentBlock_Image = Message<"alis.open.support.v1.Guide.ContentBlock.Image"> & {
  /**
   * The image source url
   *
   * @generated from field: string source_uri = 1;
   */
  sourceUri: string;

  /**
   * An optional caption to the image
   *
   * @generated from field: string caption = 2;
   */
  caption: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Image.
 * Use `create(Guide_ContentBlock_ImageSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_ImageSchema: GenMessage<Guide_ContentBlock_Image>;

/**
 * A standalone video
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Video
 */
export declare type Guide_ContentBlock_Video = Message<"alis.open.support.v1.Guide.ContentBlock.Video"> & {
  /**
   * The video source url.
   *
   * Currently only support Youtube links
   *
   * @generated from field: string source_uri = 1;
   */
  sourceUri: string;

  /**
   * An optional caption to the video
   *
   * @generated from field: string caption = 2;
   */
  caption: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Video.
 * Use `create(Guide_ContentBlock_VideoSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_VideoSchema: GenMessage<Guide_ContentBlock_Video>;

/**
 * A divider which can be used to seperate elements of the page.
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Divider
 */
export declare type Guide_ContentBlock_Divider = Message<"alis.open.support.v1.Guide.ContentBlock.Divider"> & {
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Divider.
 * Use `create(Guide_ContentBlock_DividerSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_DividerSchema: GenMessage<Guide_ContentBlock_Divider>;

/**
 * Provides a user-specified preview of a URL
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.LinkPreview
 */
export declare type Guide_ContentBlock_LinkPreview = Message<"alis.open.support.v1.Guide.ContentBlock.LinkPreview"> & {
  /**
   * The URI that will be directed to on open
   *
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * An avatar to use, if not specified, will default to the Alis dots
   *
   * @generated from field: string avatar_uri = 2;
   */
  avatarUri: string;

  /**
   * A title to use
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * A blurb of body text that can be used to give a description to the link.
   *
   * @generated from field: string body = 4;
   */
  body: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.LinkPreview.
 * Use `create(Guide_ContentBlock_LinkPreviewSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_LinkPreviewSchema: GenMessage<Guide_ContentBlock_LinkPreview>;

/**
 * Footnote that can be placed at the end of a section
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Footnote
 */
export declare type Guide_ContentBlock_Footnote = Message<"alis.open.support.v1.Guide.ContentBlock.Footnote"> & {
  /**
   * The footnote content
   * Supports standard markdown format.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Footnote.
 * Use `create(Guide_ContentBlock_FootnoteSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_FootnoteSchema: GenMessage<Guide_ContentBlock_Footnote>;

/**
 * A diagram, specified using valid syntax
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.Diagram
 */
export declare type Guide_ContentBlock_Diagram = Message<"alis.open.support.v1.Guide.ContentBlock.Diagram"> & {
  /**
   * Valid Mermaid Syntax (https://mermaid.js.org/intro/syntax-reference.html)
   * that will be used to render the diagram.
   *
   * @generated from field: string mermaid_diagram_code = 1;
   */
  mermaidDiagramCode: string;

  /**
   * A string version of the rendered diagram as valid html or SVG.
   *
   * This is stored such that client-side usage does not need to
   * install Mermaid and render the code themselves.
   *
   * @generated from field: string mermaid_rendered_diagram = 2;
   */
  mermaidRenderedDiagram: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.Diagram.
 * Use `create(Guide_ContentBlock_DiagramSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_DiagramSchema: GenMessage<Guide_ContentBlock_Diagram>;

/**
 * A syntax-highlighted code block for the set of supported languages
 *
 * @generated from message alis.open.support.v1.Guide.ContentBlock.CodeBlock
 */
export declare type Guide_ContentBlock_CodeBlock = Message<"alis.open.support.v1.Guide.ContentBlock.CodeBlock"> & {
  /**
   * The language of the code
   *
   * @generated from field: alis.open.support.v1.Guide.ContentBlock.CodeBlock.Language language = 1;
   */
  language: Guide_ContentBlock_CodeBlock_Language;

  /**
   * The code to that will be displayed in the code block.
   *
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * A string version of the syntax-highlighted code rendered as valid html.
   *
   * This is stored such that client-side usage does not need to
   * install a syntax highlighter and render the html themselves.
   *
   * @generated from field: string syntax_highlighted_code = 3;
   */
  syntaxHighlightedCode: string;
};

/**
 * Describes the message alis.open.support.v1.Guide.ContentBlock.CodeBlock.
 * Use `create(Guide_ContentBlock_CodeBlockSchema)` to create a new message.
 */
export declare const Guide_ContentBlock_CodeBlockSchema: GenMessage<Guide_ContentBlock_CodeBlock>;

/**
 * The set of available languages
 *
 * @generated from enum alis.open.support.v1.Guide.ContentBlock.CodeBlock.Language
 */
export enum Guide_ContentBlock_CodeBlock_Language {
  /**
   * Unspecified
   *
   * @generated from enum value: LANGUAGE_UNSPECIFIED = 0;
   */
  LANGUAGE_UNSPECIFIED = 0,

  /**
   * Go
   *
   * @generated from enum value: GO = 1;
   */
  GO = 1,

  /**
   * Protocol buffer 3
   *
   * @generated from enum value: PROTO = 2;
   */
  PROTO = 2,

  /**
   * Python
   *
   * @generated from enum value: PYTHON = 3;
   */
  PYTHON = 3,

  /**
   * Vue
   *
   * @generated from enum value: VUE = 4;
   */
  VUE = 4,

  /**
   * Typescript
   *
   * @generated from enum value: TYPESCRIPT = 5;
   */
  TYPESCRIPT = 5,

  /**
   * LATEX
   *
   * @generated from enum value: LATEX = 6;
   */
  LATEX = 6,

  /**
   * Hashicorp HCL
   *
   * @generated from enum value: HCL = 7;
   */
  HCL = 7,

  /**
   * JSON
   *
   * @generated from enum value: JSON = 8;
   */
  JSON = 8,

  /**
   * YAML
   *
   * @generated from enum value: YAML = 9;
   */
  YAML = 9,

  /**
   * Plain text
   *
   * @generated from enum value: TEXT = 10;
   */
  TEXT = 10,
}

/**
 * Describes the enum alis.open.support.v1.Guide.ContentBlock.CodeBlock.Language.
 */
export declare const Guide_ContentBlock_CodeBlock_LanguageSchema: GenEnum<Guide_ContentBlock_CodeBlock_Language>;

/**
 * The potential types of content blocks
 *
 * @generated from enum alis.open.support.v1.Guide.ContentBlock.Type
 */
export enum Guide_ContentBlock_Type {
  /**
   * TYPE_UNSPECIFIED
   *
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * A title
   *
   * @generated from enum value: TITLE = 1;
   */
  TITLE = 1,

  /**
   * A subtitle
   *
   * @generated from enum value: SUBTITLE = 2;
   */
  SUBTITLE = 2,

  /**
   * A heading
   *
   * @generated from enum value: HEADING = 3;
   */
  HEADING = 3,

  /**
   * Body text
   *
   * @generated from enum value: TEXT_BODY = 4;
   */
  TEXT_BODY = 4,

  /**
   * A standalone image
   *
   * @generated from enum value: IMAGE = 5;
   */
  IMAGE = 5,

  /**
   * A standalone video
   *
   * @generated from enum value: VIDEO = 6;
   */
  VIDEO = 6,

  /**
   * A divider which can be used to seperate elements of the page.
   *
   * @generated from enum value: DIVIDER = 7;
   */
  DIVIDER = 7,

  /**
   * Provides a user-specified preview of a URL
   *
   * @generated from enum value: LINK_PREVIEW = 8;
   */
  LINK_PREVIEW = 8,

  /**
   * Footnote that can be placed at the end of a section
   *
   * @generated from enum value: FOOTNOTE = 9;
   */
  FOOTNOTE = 9,

  /**
   * A diagram, specified using valid syntax
   *
   * @generated from enum value: DIAGRAM = 10;
   */
  DIAGRAM = 10,

  /**
   * A syntax-highlighted code block for the set of supported languages
   *
   * @generated from enum value: CODE_BLOCK = 11;
   */
  CODE_BLOCK = 11,
}

/**
 * Describes the enum alis.open.support.v1.Guide.ContentBlock.Type.
 */
export declare const Guide_ContentBlock_TypeSchema: GenEnum<Guide_ContentBlock_Type>;

/**
 * The request message for the GetGuide method.
 *
 * @generated from message alis.open.support.v1.GetGuideRequest
 */
export declare type GetGuideRequest = Message<"alis.open.support.v1.GetGuideRequest"> & {
  /**
   * The unique name of the Guide.
   * Format: guides/*
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The fields to return in snake_case.
   * All fields are returned if not set.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 2;
   */
  readMask?: FieldMask;
};

/**
 * Describes the message alis.open.support.v1.GetGuideRequest.
 * Use `create(GetGuideRequestSchema)` to create a new message.
 */
export declare const GetGuideRequestSchema: GenMessage<GetGuideRequest>;

/**
 * The request message for the ListGuides method.
 *
 * Reserved for the parent resource of the Guide if ever needed.
 *
 * @generated from message alis.open.support.v1.ListGuidesRequest
 */
export declare type ListGuidesRequest = Message<"alis.open.support.v1.ListGuidesRequest"> & {
  /**
   * The maximum number of Guides to return.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token, received from a previous ListGuides call.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * The fields to return in snake_case.
   * All fields are returned if not set.
   *
   * @generated from field: google.protobuf.FieldMask read_mask = 4;
   */
  readMask?: FieldMask;

  /**
   * The filter to apply
   *
   * @generated from field: string filter = 5;
   */
  filter: string;

  /**
   * The order to sort the results by
   * Default is descending
   *
   * Format: "field_name {asc|desc}"
   *
   * Only update_time is supported at the moment.
   *
   * @generated from field: string order_by = 6;
   */
  orderBy: string;
};

/**
 * Describes the message alis.open.support.v1.ListGuidesRequest.
 * Use `create(ListGuidesRequestSchema)` to create a new message.
 */
export declare const ListGuidesRequestSchema: GenMessage<ListGuidesRequest>;

/**
 * The response message for the ListGuides method.
 *
 * @generated from message alis.open.support.v1.ListGuidesResponse
 */
export declare type ListGuidesResponse = Message<"alis.open.support.v1.ListGuidesResponse"> & {
  /**
   * The Guides.
   *
   * @generated from field: repeated alis.open.support.v1.Guide guides = 1;
   */
  guides: Guide[];

  /**
   * A token to retrieve the next page of results.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message alis.open.support.v1.ListGuidesResponse.
 * Use `create(ListGuidesResponseSchema)` to create a new message.
 */
export declare const ListGuidesResponseSchema: GenMessage<ListGuidesResponse>;

/**
 * The request message for the SyncGuide method.
 *
 * @generated from message alis.open.support.v1.SyncGuideRequest
 */
export declare type SyncGuideRequest = Message<"alis.open.support.v1.SyncGuideRequest"> & {
  /**
   * The name of the guide to sync
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The new values of the guide.
   * If empty, the guide is removed.
   *
   * @generated from field: alis.open.support.v1.Guide guide = 2;
   */
  guide?: Guide;
};

/**
 * Describes the message alis.open.support.v1.SyncGuideRequest.
 * Use `create(SyncGuideRequestSchema)` to create a new message.
 */
export declare const SyncGuideRequestSchema: GenMessage<SyncGuideRequest>;

/**
 * GuidesService provides RPCs for managing Guide resources.
 *
 * @generated from service alis.open.support.v1.GuidesService
 */
export declare const GuidesService: GenService<{
  /**
   * Validates any proto message that is used directly or indirectly by this service.
   * Most common use case is to validate request messages from a client-side application.
   *
   * @generated from rpc alis.open.support.v1.GuidesService.ValidateMessage
   */
  validateMessage: {
    methodKind: "unary";
    input: typeof ValidateMessageRequestSchema;
    output: typeof ValidateMessageResponseSchema;
  },
  /**
   * Retrieves the validation rules for any proto message that is used directly or indirectly by this service.
   * Serves as live auto-documentation of the validation rules in this service.
   *
   * @generated from rpc alis.open.support.v1.GuidesService.RetrieveRules
   */
  retrieveRules: {
    methodKind: "unary";
    input: typeof RetrieveRulesRequestSchema;
    output: typeof RetrieveRulesResponseSchema;
  },
  /**
   * Gets information about a Guide.
   *
   * @generated from rpc alis.open.support.v1.GuidesService.GetGuide
   */
  getGuide: {
    methodKind: "unary";
    input: typeof GetGuideRequestSchema;
    output: typeof GuideSchema;
  },
  /**
   * Lists Guides. Results are sorted by name, ascending.
   *
   * @generated from rpc alis.open.support.v1.GuidesService.ListGuides
   */
  listGuides: {
    methodKind: "unary";
    input: typeof ListGuidesRequestSchema;
    output: typeof ListGuidesResponseSchema;
  },
  /**
   * SyncGuide synchronizes the published guide from alis-build so its available in this deployment.
   *
   * @generated from rpc alis.open.support.v1.GuidesService.SyncGuide
   */
  syncGuide: {
    methodKind: "unary";
    input: typeof SyncGuideRequestSchema;
    output: typeof GuideSchema;
  },
}>;
