// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file standards/open/fundholdings/v1/prescient_pv.proto (package standards.open.fundholdings.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../../../google/type/date_pb";

/**
 * Describes the file standards/open/fundholdings/v1/prescient_pv.proto.
 */
export declare const file_standards_open_fundholdings_v1_prescient_pv: GenFile;

/**
 * Portfolio Valuation report format generated by Prescient.
 *
 * @generated from message standards.open.fundholdings.v1.PRESCIENT_PV
 */
export declare type PRESCIENT_PV = Message<"standards.open.fundholdings.v1.PRESCIENT_PV"> & {
  /**
   * The effective date that this valuation data pertains to
   *
   * @generated from field: google.type.Date effective_date = 1;
   */
  effectiveDate?: Date | undefined;

  /**
   * A list of valuation records, each representing one row from the source data file
   *
   * @generated from field: repeated standards.open.fundholdings.v1.PRESCIENT_PV.Record records = 2;
   */
  records: PRESCIENT_PV_Record[];
};

/**
 * Describes the message standards.open.fundholdings.v1.PRESCIENT_PV.
 * Use `create(PRESCIENT_PVSchema)` to create a new message.
 */
export declare const PRESCIENT_PVSchema: GenMessage<PRESCIENT_PV>;

/**
 * A row in the Prescient PV file
 *
 * @generated from message standards.open.fundholdings.v1.PRESCIENT_PV.Record
 */
export declare type PRESCIENT_PV_Record = Message<"standards.open.fundholdings.v1.PRESCIENT_PV.Record"> & {
  /**
   * Name of the fund or entity
   *
   * @generated from field: string entity_name = 1;
   */
  entityName: string;

  /**
   * First-level classification (e.g. CASH, EQUITIES)
   *
   * @generated from field: string first_level_backup = 2;
   */
  firstLevelBackup: string;

  /**
   * Second-level classification within the first (e.g. Traded Cash, CONSUMER STAPLES)
   *
   * @generated from field: string second_level_backup = 3;
   */
  secondLevelBackup: string;

  /**
   * Name of the issue/security
   *
   * @generated from field: string issue_name = 4;
   */
  issueName: string;

  /**
   * Internal or primary asset ID (instrument identifier)
   *
   * @generated from field: string primary_asset_id = 5;
   */
  primaryAssetId: string;

  /**
   * Nominal quantity or number of units held
   *
   * @generated from field: google.protobuf.DoubleValue original_nominal = 6;
   */
  originalNominal?: number | undefined;

  /**
   * Book value of the position, excluding accrued interest
   *
   * @generated from field: google.protobuf.DoubleValue clean_book_value = 7;
   */
  cleanBookValue?: number | undefined;

  /**
   * Market value of the position, excluding accrued interest
   *
   * @generated from field: google.protobuf.DoubleValue clean_market_value = 8;
   */
  cleanMarketValue?: number | undefined;

  /**
   * Cash held in the account related to this position
   *
   * @generated from field: google.protobuf.DoubleValue settled_cash_position = 9;
   */
  settledCashPosition?: number | undefined;

  /**
   * Interest or income accrued but not yet received
   *
   * @generated from field: google.protobuf.DoubleValue accrued_income = 10;
   */
  accruedIncome?: number | undefined;

  /**
   * Dividend receivable amount
   *
   * @generated from field: google.protobuf.DoubleValue dividend_receivable = 11;
   */
  dividendReceivable?: number | undefined;

  /**
   * Total income based on market value
   *
   * @generated from field: google.protobuf.DoubleValue sum_of_market_value_income = 12;
   */
  sumOfMarketValueIncome?: number | undefined;

  /**
   * Market price or yield
   *
   * @generated from field: google.protobuf.DoubleValue market_price_yield = 13;
   */
  marketPriceYield?: number | undefined;

  /**
   * Percentage share of this position relative to total market value
   *
   * @generated from field: google.protobuf.DoubleValue percent_of_total_market_value = 14;
   */
  percentOfTotalMarketValue?: number | undefined;

  /**
   * Effective date of the report
   *
   * @generated from field: google.type.Date report_effective_date = 15;
   */
  reportEffectiveDate?: Date | undefined;

  /**
   * Ticker symbol (e.g. stock exchange symbol)
   *
   * @generated from field: string ticker = 16;
   */
  ticker: string;

  /**
   * Name of the issuer of the instrument
   *
   * @generated from field: string issuer = 17;
   */
  issuer: string;

  /**
   * Currency code (e.g. ZAR, USD)
   *
   * @generated from field: string currency = 18;
   */
  currency: string;

  /**
   * Coupon interest due to be received
   *
   * @generated from field: google.protobuf.DoubleValue coupon_receivable = 19;
   */
  couponReceivable?: number | undefined;

  /**
   * Maturity date of the instrument (if applicable)
   *
   * @generated from field: google.type.Date maturity_date = 20;
   */
  maturityDate?: Date | undefined;

  /**
   * ISIN (International Securities Identification Number)
   *
   * @generated from field: string isin_code = 21;
   */
  isinCode: string;

  /**
   * Internal entity ID (e.g. fund code)
   *
   * @generated from field: string entity_id = 22;
   */
  entityId: string;

  /**
   * Alternate asset ID (e.g. Bloomberg ID)
   *
   * @generated from field: string alt_asset_id = 23;
   */
  altAssetId: string;

  /**
   * Next coupon payment date (if applicable)
   *
   * @generated from field: google.type.Date next_coupon_date = 24;
   */
  nextCouponDate?: Date | undefined;

  /**
   * Coupon rate or value
   *
   * @generated from field: google.protobuf.DoubleValue coupon = 25;
   */
  coupon?: number | undefined;
};

/**
 * Describes the message standards.open.fundholdings.v1.PRESCIENT_PV.Record.
 * Use `create(PRESCIENT_PV_RecordSchema)` to create a new message.
 */
export declare const PRESCIENT_PV_RecordSchema: GenMessage<PRESCIENT_PV_Record>;

