// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file google/api/servicecontrol/v1/distribution.proto (package google.api.servicecontrol.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_distribution } from "../../distribution_pb";

/**
 * Describes the file google/api/servicecontrol/v1/distribution.proto.
 */
export const file_google_api_servicecontrol_v1_distribution = /*@__PURE__*/
  fileDesc("Ci9nb29nbGUvYXBpL3NlcnZpY2Vjb250cm9sL3YxL2Rpc3RyaWJ1dGlvbi5wcm90bxIcZ29vZ2xlLmFwaS5zZXJ2aWNlY29udHJvbC52MSKeBQoMRGlzdHJpYnV0aW9uEg0KBWNvdW50GAEgASgDEgwKBG1lYW4YAiABKAESDwoHbWluaW11bRgDIAEoARIPCgdtYXhpbXVtGAQgASgBEiAKGHN1bV9vZl9zcXVhcmVkX2RldmlhdGlvbhgFIAEoARIVCg1idWNrZXRfY291bnRzGAYgAygDElIKDmxpbmVhcl9idWNrZXRzGAcgASgLMjguZ29vZ2xlLmFwaS5zZXJ2aWNlY29udHJvbC52MS5EaXN0cmlidXRpb24uTGluZWFyQnVja2V0c0gAElwKE2V4cG9uZW50aWFsX2J1Y2tldHMYCCABKAsyPS5nb29nbGUuYXBpLnNlcnZpY2Vjb250cm9sLnYxLkRpc3RyaWJ1dGlvbi5FeHBvbmVudGlhbEJ1Y2tldHNIABJWChBleHBsaWNpdF9idWNrZXRzGAkgASgLMjouZ29vZ2xlLmFwaS5zZXJ2aWNlY29udHJvbC52MS5EaXN0cmlidXRpb24uRXhwbGljaXRCdWNrZXRzSAASNAoJZXhlbXBsYXJzGAogAygLMiEuZ29vZ2xlLmFwaS5EaXN0cmlidXRpb24uRXhlbXBsYXIaSgoNTGluZWFyQnVja2V0cxIaChJudW1fZmluaXRlX2J1Y2tldHMYASABKAUSDQoFd2lkdGgYAiABKAESDgoGb2Zmc2V0GAMgASgBGlYKEkV4cG9uZW50aWFsQnVja2V0cxIaChJudW1fZmluaXRlX2J1Y2tldHMYASABKAUSFQoNZ3Jvd3RoX2ZhY3RvchgCIAEoARINCgVzY2FsZRgDIAEoARohCg9FeHBsaWNpdEJ1Y2tldHMSDgoGYm91bmRzGAEgAygBQg8KDWJ1Y2tldF9vcHRpb25C7AEKIGNvbS5nb29nbGUuYXBpLnNlcnZpY2Vjb250cm9sLnYxQhFEaXN0cmlidXRpb25Qcm90b1ABWkpnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL2FwaS9zZXJ2aWNlY29udHJvbC92MTtzZXJ2aWNlY29udHJvbPgBAaoCHkdvb2dsZS5DbG91ZC5TZXJ2aWNlQ29udHJvbC5WMcoCHkdvb2dsZVxDbG91ZFxTZXJ2aWNlQ29udHJvbFxWMeoCIUdvb2dsZTo6Q2xvdWQ6OlNlcnZpY2VDb250cm9sOjpWMWIGcHJvdG8z", [file_google_api_distribution]);

/**
 * Describes the message google.api.servicecontrol.v1.Distribution.
 * Use `create(DistributionSchema)` to create a new message.
 */
export const DistributionSchema = /*@__PURE__*/
  messageDesc(file_google_api_servicecontrol_v1_distribution, 0);

/**
 * Describes the message google.api.servicecontrol.v1.Distribution.LinearBuckets.
 * Use `create(Distribution_LinearBucketsSchema)` to create a new message.
 */
export const Distribution_LinearBucketsSchema = /*@__PURE__*/
  messageDesc(file_google_api_servicecontrol_v1_distribution, 0, 0);

/**
 * Describes the message google.api.servicecontrol.v1.Distribution.ExponentialBuckets.
 * Use `create(Distribution_ExponentialBucketsSchema)` to create a new message.
 */
export const Distribution_ExponentialBucketsSchema = /*@__PURE__*/
  messageDesc(file_google_api_servicecontrol_v1_distribution, 0, 1);

/**
 * Describes the message google.api.servicecontrol.v1.Distribution.ExplicitBuckets.
 * Use `create(Distribution_ExplicitBucketsSchema)` to create a new message.
 */
export const Distribution_ExplicitBucketsSchema = /*@__PURE__*/
  messageDesc(file_google_api_servicecontrol_v1_distribution, 0, 2);
