// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file google/iam/admin/v1/audit_data.proto (package google.iam.admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file google/iam/admin/v1/audit_data.proto.
 */
export const file_google_iam_admin_v1_audit_data = /*@__PURE__*/
  fileDesc("CiRnb29nbGUvaWFtL2FkbWluL3YxL2F1ZGl0X2RhdGEucHJvdG8SE2dvb2dsZS5pYW0uYWRtaW4udjEioAEKCUF1ZGl0RGF0YRJIChBwZXJtaXNzaW9uX2RlbHRhGAEgASgLMi4uZ29vZ2xlLmlhbS5hZG1pbi52MS5BdWRpdERhdGEuUGVybWlzc2lvbkRlbHRhGkkKD1Blcm1pc3Npb25EZWx0YRIZChFhZGRlZF9wZXJtaXNzaW9ucxgBIAMoCRIbChNyZW1vdmVkX3Blcm1pc3Npb25zGAIgAygJQp0BChdjb20uZ29vZ2xlLmlhbS5hZG1pbi52MUIOQXVkaXREYXRhUHJvdG9QAVo4Z29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy9pYW0vYWRtaW4vdjE7YWRtaW6qAhlHb29nbGUuQ2xvdWQuSWFtLkFkbWluLlYxygIZR29vZ2xlXENsb3VkXElhbVxBZG1pblxWMWIGcHJvdG8z");

/**
 * Describes the message google.iam.admin.v1.AuditData.
 * Use `create(AuditDataSchema)` to create a new message.
 */
export const AuditDataSchema = /*@__PURE__*/
  messageDesc(file_google_iam_admin_v1_audit_data, 0);

/**
 * Describes the message google.iam.admin.v1.AuditData.PermissionDelta.
 * Use `create(AuditData_PermissionDeltaSchema)` to create a new message.
 */
export const AuditData_PermissionDeltaSchema = /*@__PURE__*/
  messageDesc(file_google_iam_admin_v1_audit_data, 0, 0);

