// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file alis/adk/sessions/v1/sessions.proto (package alis.adk.sessions.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "../../../../google/protobuf/timestamp_pb";
import type { Duration } from "../../../../google/protobuf/duration_pb";
import type { FieldMask } from "../../../../google/protobuf/field_mask_pb";
import type { Date } from "../../../../google/type/date_pb";
import type { Value } from "../../../../google/protobuf/struct_pb";
import type { EmptySchema } from "../../../../google/protobuf/empty_pb";

/**
 * Describes the file alis/adk/sessions/v1/sessions.proto.
 */
export declare const file_alis_adk_sessions_v1_sessions: GenFile;

/**
 * Session represents a conversation session between a user and an agent.
 *
 * A session contains a set of actions between users and agents, including
 * the session state, events, and metadata.
 *
 * @generated from message alis.adk.sessions.v1.Session
 */
export declare type Session = Message<"alis.adk.sessions.v1.Session"> & {
  /**
   * Identifier. The ID of the session.
   * Format: `{session}`
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Required. The name of the application associated with this session.
   *
   * @generated from field: string app_name = 2;
   */
  appName: string;

  /**
   * Required. Immutable. The user ID who owns this session.
   *
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * Optional. The display name of the session.
   *
   * @generated from field: optional string display_name = 4;
   */
  displayName?: string | undefined;

  /**
   * Optional. Session-specific state which stores key conversation points.
   * This is a key-value store that persists across events in the session.
   *
   * @generated from field: google.protobuf.Struct state = 10;
   */
  state?: JsonObject | undefined;

  /**
   * The expiration configuration for the session.
   *
   * @generated from oneof alis.adk.sessions.v1.Session.expiration
   */
  expiration: {
    /**
     * Optional. Timestamp of when this session is considered expired.
     * This is always provided on output, regardless of what was sent on input.
     *
     * @generated from field: google.protobuf.Timestamp expire_time = 96;
     */
    value: Timestamp;
    case: "expireTime";
  } | {
    /**
     * Optional. Input only. The TTL (time-to-live) for this session.
     * When provided on input, the service will calculate expire_time.
     *
     * @generated from field: google.protobuf.Duration ttl = 97;
     */
    value: Duration;
    case: "ttl";
  } | { case: undefined; value?: undefined };

  /**
   * Output only. Timestamp when the session was created.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 98;
   */
  createTime?: Timestamp | undefined;

  /**
   * Output only. Timestamp when the session was last updated.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 99;
   */
  updateTime?: Timestamp | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

/**
 * AppState represents application-level state shared across all users and
 * sessions within an application.
 *
 * Keys use the "app:" prefix in the merged session state view. Stored in
 * a separate table keyed by app_name.
 *
 * @generated from message alis.adk.sessions.v1.AppState
 */
export declare type AppState = Message<"alis.adk.sessions.v1.AppState"> & {
  /**
   * Required. The name of the application.
   *
   * @generated from field: string app_name = 1;
   */
  appName: string;

  /**
   * Optional. Key-value state shared across all users and sessions of the app.
   *
   * @generated from field: google.protobuf.Struct state = 2;
   */
  state?: JsonObject | undefined;

  /**
   * Output only. Timestamp when this app state was last updated.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 99;
   */
  updateTime?: Timestamp | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.AppState.
 * Use `create(AppStateSchema)` to create a new message.
 */
export declare const AppStateSchema: GenMessage<AppState>;

/**
 * UserState represents user-level state shared across all sessions of a user
 * within an application.
 *
 * Keys use the "user:" prefix in the merged session state view. Stored in
 * a separate table keyed by (app_name, user_id).
 *
 * @generated from message alis.adk.sessions.v1.UserState
 */
export declare type UserState = Message<"alis.adk.sessions.v1.UserState"> & {
  /**
   * Required. The name of the application.
   *
   * @generated from field: string app_name = 1;
   */
  appName: string;

  /**
   * Required. The user ID who owns this state.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * Optional. Key-value state shared across all sessions of this user in the
   * app.
   *
   * @generated from field: google.protobuf.Struct state = 3;
   */
  state?: JsonObject | undefined;

  /**
   * Output only. Timestamp when this user state was last updated.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 99;
   */
  updateTime?: Timestamp | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.UserState.
 * Use `create(UserStateSchema)` to create a new message.
 */
export declare const UserStateSchema: GenMessage<UserState>;

/**
 * SessionEvent represents a message from either the user or agent.
 *
 * Events are the fundamental unit of interaction in a session, containing
 * content, metadata, and actions taken by the agent.
 *
 * @generated from message alis.adk.sessions.v1.SessionEvent
 */
export declare type SessionEvent = Message<"alis.adk.sessions.v1.SessionEvent"> & {
  /**
   * Identifier. The ID of the event.
   * Format: `{event}`
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Required. The name of the application associated with this event.
   *
   * @generated from field: string app_name = 2;
   */
  appName: string;

  /**
   * Required. The user ID who owns the session this event belongs to.
   *
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * Required. The ID of the session this event belongs to.
   *
   * @generated from field: string session_id = 4;
   */
  sessionId: string;

  /**
   * Required. The invocation ID of the event.
   * Multiple events can have the same invocation ID, representing events
   * that are part of the same agent invocation.
   *
   * @generated from field: string invocation_id = 5;
   */
  invocationId: string;

  /**
   * Required. The name of the agent that sent the event, or the user
   * identifier.
   *
   * @generated from field: string author = 6;
   */
  author: string;

  /**
   * Optional. Actions executed by the agent as part of this event.
   *
   * @generated from field: alis.adk.sessions.v1.EventActions actions = 7;
   */
  actions?: EventActions | undefined;

  /**
   * Optional. IDs of long-running function calls. Used for function call
   * events.
   *
   * @generated from field: repeated string long_running_tool_ids = 8;
   */
  longRunningToolIds: string[];

  /**
   * Optional. The branch of the event. Format: `agent_1.agent_2.agent_3` for
   * nested agent hierarchies. Used when child agents should not see siblings'
   * history.
   *
   * @generated from field: optional string branch = 9;
   */
  branch?: string | undefined;

  /**
   * Optional. Content of the event provided by the author.
   *
   * @generated from field: alis.adk.sessions.v1.Content content = 10;
   */
  content?: Content | undefined;

  /**
   * Optional. Metadata returned when grounding is enabled (e.g. web search,
   * RAG).
   *
   * @generated from field: alis.adk.sessions.v1.GroundingMetadata grounding_metadata = 11;
   */
  groundingMetadata?: GroundingMetadata | undefined;

  /**
   * Optional. Custom metadata of the LLM response.
   *
   * @generated from field: google.protobuf.Struct custom_metadata = 12;
   */
  customMetadata?: JsonObject | undefined;

  /**
   * Optional. Token usage metadata from the model.
   *
   * @generated from field: alis.adk.sessions.v1.UsageMetadata usage_metadata = 13;
   */
  usageMetadata?: UsageMetadata | undefined;

  /**
   * Optional. Citation metadata for sourced content.
   *
   * @generated from field: alis.adk.sessions.v1.CitationMetadata citation_metadata = 14;
   */
  citationMetadata?: CitationMetadata | undefined;

  /**
   * Optional. Indicates whether the content is part of an unfinished text
   * stream.
   *
   * @generated from field: optional bool partial = 15;
   */
  partial?: boolean | undefined;

  /**
   * Optional. Indicates whether the response from the model is complete.
   *
   * @generated from field: optional bool turn_complete = 16;
   */
  turnComplete?: boolean | undefined;

  /**
   * Optional. Error code if the response is an error. Code varies by model.
   *
   * @generated from field: optional string error_code = 17;
   */
  errorCode?: string | undefined;

  /**
   * Optional. Error message if the response is an error.
   *
   * @generated from field: optional string error_message = 18;
   */
  errorMessage?: string | undefined;

  /**
   * Optional. Indicates the LLM was interrupted when generating (e.g. user
   * stop).
   *
   * @generated from field: optional bool interrupted = 19;
   */
  interrupted?: boolean | undefined;

  /**
   * Optional. The reason the LLM stopped generating.
   *
   * @generated from field: alis.adk.sessions.v1.FinishReason finish_reason = 20;
   */
  finishReason: FinishReason;

  /**
   * Optional. The average log probability of the tokens in the response.
   *
   * @generated from field: optional double avg_logprobs = 21;
   */
  avgLogprobs?: number | undefined;

  /**
   * Optional. The version of the model that generated the response.
   *
   * @generated from field: optional string model_version = 22;
   */
  modelVersion?: string | undefined;

  /**
   * Optional. The logprobs result of the response.
   *
   * @generated from field: alis.adk.sessions.v1.LogprobsResult logprobs_result = 23;
   */
  logprobsResult?: LogprobsResult | undefined;

  /**
   * Required. Timestamp when the event was created on the client side.
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 98;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.SessionEvent.
 * Use `create(SessionEventSchema)` to create a new message.
 */
export declare const SessionEventSchema: GenMessage<SessionEvent>;

/**
 * Request message for SessionService.CreateSession.
 *
 * @generated from message alis.adk.sessions.v1.CreateSessionRequest
 */
export declare type CreateSessionRequest = Message<"alis.adk.sessions.v1.CreateSessionRequest"> & {
  /**
   * Required. The session to create.
   *
   * @generated from field: alis.adk.sessions.v1.Session session = 1;
   */
  session?: Session | undefined;

  /**
   * Optional. The session ID to create.
   * If not provided, a new session ID will be generated.
   *
   * @generated from field: string session_id = 2;
   */
  sessionId: string;
};

/**
 * Describes the message alis.adk.sessions.v1.CreateSessionRequest.
 * Use `create(CreateSessionRequestSchema)` to create a new message.
 */
export declare const CreateSessionRequestSchema: GenMessage<CreateSessionRequest>;

/**
 * Request message for SessionService.GetSession.
 *
 * @generated from message alis.adk.sessions.v1.GetSessionRequest
 */
export declare type GetSessionRequest = Message<"alis.adk.sessions.v1.GetSessionRequest"> & {
  /**
   * Required. The resource name of the session.
   * Format: `sessions/{session}`
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GetSessionRequest.
 * Use `create(GetSessionRequestSchema)` to create a new message.
 */
export declare const GetSessionRequestSchema: GenMessage<GetSessionRequest>;

/**
 * Request message for SessionService.ListSessions.
 *
 * @generated from message alis.adk.sessions.v1.ListSessionsRequest
 */
export declare type ListSessionsRequest = Message<"alis.adk.sessions.v1.ListSessionsRequest"> & {
  /**
   * Optional. The maximum number of sessions to return.
   * The service may return fewer than this value.
   * If unspecified, at most 100 sessions will be returned.
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * Optional. A page token, received from a previous ListSessions call.
   * Provide this to retrieve the next page of results.
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * Optional. The standard list filter.
   * Supported fields:
   *   - `display_name`
   *   - `user_id`
   *   - `app_name`
   *
   * @generated from field: string filter = 3;
   */
  filter: string;

  /**
   * Optional. A comma-separated list of fields to order by, sorted in ascending
   * order. Use "desc" after a field name for descending.
   * Supported fields:
   *   - `create_time`
   *   - `update_time`
   *
   * @generated from field: string order_by = 4;
   */
  orderBy: string;
};

/**
 * Describes the message alis.adk.sessions.v1.ListSessionsRequest.
 * Use `create(ListSessionsRequestSchema)` to create a new message.
 */
export declare const ListSessionsRequestSchema: GenMessage<ListSessionsRequest>;

/**
 * Response message for SessionService.ListSessions.
 *
 * @generated from message alis.adk.sessions.v1.ListSessionsResponse
 */
export declare type ListSessionsResponse = Message<"alis.adk.sessions.v1.ListSessionsResponse"> & {
  /**
   * A list of sessions matching the request.
   *
   * @generated from field: repeated alis.adk.sessions.v1.Session sessions = 1;
   */
  sessions: Session[];

  /**
   * A token, which can be sent as ListSessionsRequest.page_token to retrieve
   * the next page. Absence of this field indicates there are no subsequent
   * pages.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message alis.adk.sessions.v1.ListSessionsResponse.
 * Use `create(ListSessionsResponseSchema)` to create a new message.
 */
export declare const ListSessionsResponseSchema: GenMessage<ListSessionsResponse>;

/**
 * Request message for SessionService.UpdateSession.
 *
 * @generated from message alis.adk.sessions.v1.UpdateSessionRequest
 */
export declare type UpdateSessionRequest = Message<"alis.adk.sessions.v1.UpdateSessionRequest"> & {
  /**
   * Required. The session to update.
   *
   * @generated from field: alis.adk.sessions.v1.Session session = 1;
   */
  session?: Session | undefined;

  /**
   * Required. The list of fields to update.
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.UpdateSessionRequest.
 * Use `create(UpdateSessionRequestSchema)` to create a new message.
 */
export declare const UpdateSessionRequestSchema: GenMessage<UpdateSessionRequest>;

/**
 * Request message for SessionService.DeleteSession.
 *
 * @generated from message alis.adk.sessions.v1.DeleteSessionRequest
 */
export declare type DeleteSessionRequest = Message<"alis.adk.sessions.v1.DeleteSessionRequest"> & {
  /**
   * Required. The resource name of the session.
   * Format: `sessions/{session}`
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message alis.adk.sessions.v1.DeleteSessionRequest.
 * Use `create(DeleteSessionRequestSchema)` to create a new message.
 */
export declare const DeleteSessionRequestSchema: GenMessage<DeleteSessionRequest>;

/**
 * Request message for SessionService.GetEvent.
 *
 * @generated from message alis.adk.sessions.v1.GetEventRequest
 */
export declare type GetEventRequest = Message<"alis.adk.sessions.v1.GetEventRequest"> & {
  /**
   * Required. The resource name of the event.
   * Format: `sessions/{session}/events/{event}`
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GetEventRequest.
 * Use `create(GetEventRequestSchema)` to create a new message.
 */
export declare const GetEventRequestSchema: GenMessage<GetEventRequest>;

/**
 * Request message for SessionService.ListEvents.
 *
 * @generated from message alis.adk.sessions.v1.ListEventsRequest
 */
export declare type ListEventsRequest = Message<"alis.adk.sessions.v1.ListEventsRequest"> & {
  /**
   * Required. The resource name of the session to list events from.
   * Format: `sessions/{session}`
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * Optional. The maximum number of events to return.
   * The service may return fewer than this value.
   * If unspecified, at most 100 events will be returned.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * Optional. A page token, received from a previous ListEvents call.
   * Provide this to retrieve the next page of results.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * Optional. The standard list filter.
   * Supported fields:
   *   - `timestamp` range in RFC 3339 format.
   *
   * @generated from field: string filter = 4;
   */
  filter: string;

  /**
   * Optional. A comma-separated list of fields to order by, sorted in ascending
   * order. Use "desc" after a field name for descending.
   * Supported fields:
   *   - `timestamp`
   *
   * @generated from field: string order_by = 5;
   */
  orderBy: string;
};

/**
 * Describes the message alis.adk.sessions.v1.ListEventsRequest.
 * Use `create(ListEventsRequestSchema)` to create a new message.
 */
export declare const ListEventsRequestSchema: GenMessage<ListEventsRequest>;

/**
 * Response message for SessionService.ListEvents.
 *
 * @generated from message alis.adk.sessions.v1.ListEventsResponse
 */
export declare type ListEventsResponse = Message<"alis.adk.sessions.v1.ListEventsResponse"> & {
  /**
   * A list of events matching the request.
   *
   * @generated from field: repeated alis.adk.sessions.v1.SessionEvent session_events = 1;
   */
  sessionEvents: SessionEvent[];

  /**
   * A token, which can be sent as ListEventsRequest.page_token to retrieve
   * the next page. Absence of this field indicates there are no subsequent
   * pages.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message alis.adk.sessions.v1.ListEventsResponse.
 * Use `create(ListEventsResponseSchema)` to create a new message.
 */
export declare const ListEventsResponseSchema: GenMessage<ListEventsResponse>;

/**
 * Request message for SessionService.AppendEvent.
 *
 * @generated from message alis.adk.sessions.v1.AppendEventRequest
 */
export declare type AppendEventRequest = Message<"alis.adk.sessions.v1.AppendEventRequest"> & {
  /**
   * Required. The resource name of the session to append the event to.
   * Format: `sessions/{session}`
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Required. The event to append.
   *
   * @generated from field: alis.adk.sessions.v1.SessionEvent event = 2;
   */
  event?: SessionEvent | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.AppendEventRequest.
 * Use `create(AppendEventRequestSchema)` to create a new message.
 */
export declare const AppendEventRequestSchema: GenMessage<AppendEventRequest>;

/**
 * Response message for SessionService.AppendEvent.
 *
 * @generated from message alis.adk.sessions.v1.AppendEventResponse
 */
export declare type AppendEventResponse = Message<"alis.adk.sessions.v1.AppendEventResponse"> & {
};

/**
 * Describes the message alis.adk.sessions.v1.AppendEventResponse.
 * Use `create(AppendEventResponseSchema)` to create a new message.
 */
export declare const AppendEventResponseSchema: GenMessage<AppendEventResponse>;

/**
 * EventMetadata contains metadata relating to an LLM response event.
 *
 * @generated from message alis.adk.sessions.v1.EventMetadata
 */
export declare type EventMetadata = Message<"alis.adk.sessions.v1.EventMetadata"> & {
  /**
   * Optional. Metadata returned to client when grounding is enabled.
   *
   * @generated from field: alis.adk.sessions.v1.GroundingMetadata grounding_metadata = 1;
   */
  groundingMetadata?: GroundingMetadata | undefined;

  /**
   * Optional. Indicates whether the text content is part of an unfinished text
   * stream. Only used for streaming mode and when the content is plain text.
   *
   * @generated from field: bool partial = 2;
   */
  partial: boolean;

  /**
   * Optional. Indicates whether the response from the model is complete.
   * Only used for streaming mode.
   *
   * @generated from field: bool turn_complete = 3;
   */
  turnComplete: boolean;

  /**
   * Optional. Flag indicating that LLM was interrupted when generating the
   * content. Usually due to user interruption during bidirectional streaming.
   *
   * @generated from field: bool interrupted = 4;
   */
  interrupted: boolean;

  /**
   * Optional. Set of IDs of the long-running function calls.
   * Agent client will know from this field which function call is long-running.
   * Only valid for function call events.
   *
   * @generated from field: repeated string long_running_tool_ids = 5;
   */
  longRunningToolIds: string[];

  /**
   * Optional. The branch of the event.
   * The format is like `agent_1.agent_2.agent_3`, where agent_1 is the parent
   * of agent_2, and agent_2 is the parent of agent_3.
   * Branch is used when multiple child agents shouldn't see their siblings'
   * conversation history.
   *
   * @generated from field: string branch = 6;
   */
  branch: string;

  /**
   * Optional. Custom metadata of the LLM response.
   *
   * @generated from field: google.protobuf.Struct custom_metadata = 7;
   */
  customMetadata?: JsonObject | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.EventMetadata.
 * Use `create(EventMetadataSchema)` to create a new message.
 */
export declare const EventMetadataSchema: GenMessage<EventMetadata>;

/**
 * EventActions represent actions executed by the agent as part of an event.
 *
 * @generated from message alis.adk.sessions.v1.EventActions
 */
export declare type EventActions = Message<"alis.adk.sessions.v1.EventActions"> & {
  /**
   * Optional. If true, the model will not summarize the function response.
   * Only used for function_response events.
   *
   * @generated from field: bool skip_summarization = 1;
   */
  skipSummarization: boolean;

  /**
   * Optional. Indicates that the event is updating the state with the given
   * delta. The delta contains key-value pairs representing state changes.
   *
   * @generated from field: google.protobuf.Struct state_delta = 2;
   */
  stateDelta?: JsonObject | undefined;

  /**
   * Optional. Indicates that the event is updating artifacts.
   * Key is the filename, value is the version number.
   *
   * @generated from field: map<string, int64> artifact_delta = 3;
   */
  artifactDelta: { [key: string]: bigint };

  /**
   * Optional. The agent is escalating to a higher level agent.
   *
   * @generated from field: bool escalate = 6;
   */
  escalate: boolean;

  /**
   * Optional. Will only be set by a tool response indicating tool request
   * authentication configuration.
   * Map key is the function call ID since one function call response (from
   * model) could correspond to multiple function calls.
   * Map value is the required auth config, which can be another struct.
   *
   * @generated from field: map<string, alis.adk.sessions.v1.ToolConfirmation> requested_tool_confirmations = 7;
   */
  requestedToolConfirmations: { [key: string]: ToolConfirmation };

  /**
   * Optional. If set, the event transfers control to the specified agent.
   *
   * @generated from field: string transfer_agent = 8;
   */
  transferAgent: string;
};

/**
 * Describes the message alis.adk.sessions.v1.EventActions.
 * Use `create(EventActionsSchema)` to create a new message.
 */
export declare const EventActionsSchema: GenMessage<EventActions>;

/**
 * Content represents the base structured datatype containing multi-part content
 * of a message.
 *
 * A Content includes a role field designating the producer of the Content
 * and a parts field containing multi-part data that contains the content of
 * the message turn.
 *
 * @generated from message alis.adk.sessions.v1.Content
 */
export declare type Content = Message<"alis.adk.sessions.v1.Content"> & {
  /**
   * Optional. The producer of the content. Must be either 'user' or 'model'.
   *
   * Useful to set for multi-turn conversations, otherwise can be left blank
   * or unset.
   *
   * @generated from field: string role = 1;
   */
  role: string;

  /**
   * Required. Ordered Parts that constitute a single message.
   * Parts may have different IANA MIME types.
   *
   * @generated from field: repeated alis.adk.sessions.v1.Part parts = 2;
   */
  parts: Part[];
};

/**
 * Describes the message alis.adk.sessions.v1.Content.
 * Use `create(ContentSchema)` to create a new message.
 */
export declare const ContentSchema: GenMessage<Content>;

/**
 * Part represents a datatype containing media that is part of a multi-part
 * Content message.
 *
 * A Part consists of data which has an associated datatype. A Part can only
 * contain one of the accepted types in Part.data.
 *
 * A Part must have a fixed IANA MIME type identifying the type and subtype
 * of the media if inline_data or file_data field is filled with raw bytes.
 *
 * @generated from message alis.adk.sessions.v1.Part
 */
export declare type Part = Message<"alis.adk.sessions.v1.Part"> & {
  /**
   * @generated from oneof alis.adk.sessions.v1.Part.data
   */
  data: {
    /**
     * Optional. Text part (can be code).
     *
     * @generated from field: string text = 1;
     */
    value: string;
    case: "text";
  } | {
    /**
     * Optional. Inlined bytes data.
     *
     * @generated from field: alis.adk.sessions.v1.Blob inline_data = 2;
     */
    value: Blob;
    case: "inlineData";
  } | {
    /**
     * Optional. URI-based data.
     *
     * @generated from field: alis.adk.sessions.v1.FileData file_data = 3;
     */
    value: FileData;
    case: "fileData";
  } | {
    /**
     * Optional. A predicted FunctionCall returned from the model that
     * contains a string representing the FunctionDeclaration.name with the
     * parameters and their values.
     *
     * @generated from field: alis.adk.sessions.v1.FunctionCall function_call = 5;
     */
    value: FunctionCall;
    case: "functionCall";
  } | {
    /**
     * Optional. The result output of a FunctionCall that contains a string
     * representing the FunctionDeclaration.name and a structured JSON object
     * containing any output from the function call. It is used as context to
     * the model.
     *
     * @generated from field: alis.adk.sessions.v1.FunctionResponse function_response = 6;
     */
    value: FunctionResponse;
    case: "functionResponse";
  } | {
    /**
     * Optional. Code generated by the model that is meant to be executed.
     *
     * @generated from field: alis.adk.sessions.v1.ExecutableCode executable_code = 8;
     */
    value: ExecutableCode;
    case: "executableCode";
  } | {
    /**
     * Optional. Result of executing the ExecutableCode.
     *
     * @generated from field: alis.adk.sessions.v1.CodeExecutionResult code_execution_result = 9;
     */
    value: CodeExecutionResult;
    case: "codeExecutionResult";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from oneof alis.adk.sessions.v1.Part.metadata
   */
  metadata: {
    /**
     * Optional. Video metadata. The metadata should only be specified while the
     * video data is presented in inline_data or file_data.
     *
     * @generated from field: alis.adk.sessions.v1.VideoMetadata video_metadata = 4;
     */
    value: VideoMetadata;
    case: "videoMetadata";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. Indicates if the part is a thought from the model.
   *
   * @generated from field: bool thought = 10;
   */
  thought: boolean;

  /**
   * Optional. An opaque signature for the thought so it can be reused in
   * subsequent requests.
   *
   * @generated from field: bytes thought_signature = 11;
   */
  thoughtSignature: Uint8Array;
};

/**
 * Describes the message alis.adk.sessions.v1.Part.
 * Use `create(PartSchema)` to create a new message.
 */
export declare const PartSchema: GenMessage<Part>;

/**
 * Blob represents inline binary data.
 *
 * It's preferred to send text directly rather than raw bytes.
 *
 * @generated from message alis.adk.sessions.v1.Blob
 */
export declare type Blob = Message<"alis.adk.sessions.v1.Blob"> & {
  /**
   * Required. The IANA standard MIME type of the source data.
   *
   * @generated from field: string mime_type = 1;
   */
  mimeType: string;

  /**
   * Required. Raw bytes.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message alis.adk.sessions.v1.Blob.
 * Use `create(BlobSchema)` to create a new message.
 */
export declare const BlobSchema: GenMessage<Blob>;

/**
 * FileData represents URI-based data.
 *
 * @generated from message alis.adk.sessions.v1.FileData
 */
export declare type FileData = Message<"alis.adk.sessions.v1.FileData"> & {
  /**
   * Required. The IANA standard MIME type of the source data.
   *
   * @generated from field: string mime_type = 1;
   */
  mimeType: string;

  /**
   * Required. URI.
   *
   * @generated from field: string file_uri = 2;
   */
  fileUri: string;
};

/**
 * Describes the message alis.adk.sessions.v1.FileData.
 * Use `create(FileDataSchema)` to create a new message.
 */
export declare const FileDataSchema: GenMessage<FileData>;

/**
 * VideoMetadata describes the input video content.
 *
 * @generated from message alis.adk.sessions.v1.VideoMetadata
 */
export declare type VideoMetadata = Message<"alis.adk.sessions.v1.VideoMetadata"> & {
  /**
   * Optional. The start offset of the video.
   *
   * @generated from field: google.protobuf.Duration start_offset = 1;
   */
  startOffset?: Duration | undefined;

  /**
   * Optional. The end offset of the video.
   *
   * @generated from field: google.protobuf.Duration end_offset = 2;
   */
  endOffset?: Duration | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.VideoMetadata.
 * Use `create(VideoMetadataSchema)` to create a new message.
 */
export declare const VideoMetadataSchema: GenMessage<VideoMetadata>;

/**
 * FunctionCall represents a predicted function call returned from the model
 * that contains a string representing the FunctionDeclaration.name and a
 * structured JSON object containing the parameters and their values.
 *
 * @generated from message alis.adk.sessions.v1.FunctionCall
 */
export declare type FunctionCall = Message<"alis.adk.sessions.v1.FunctionCall"> & {
  /**
   * Required. The name of the function to call.
   * Matches FunctionDeclaration.name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Required. The function parameters and values in JSON object format.
   * See FunctionDeclaration.parameters for parameter details.
   *
   * @generated from field: google.protobuf.Struct args = 2;
   */
  args?: JsonObject | undefined;

  /**
   * Optional. The unique ID of the function call. If populated, the client
   * should execute the function_call and return the response with the matching
   * id.
   *
   * @generated from field: string id = 3;
   */
  id: string;
};

/**
 * Describes the message alis.adk.sessions.v1.FunctionCall.
 * Use `create(FunctionCallSchema)` to create a new message.
 */
export declare const FunctionCallSchema: GenMessage<FunctionCall>;

/**
 * FunctionResponse represents the result output from a FunctionCall that
 * contains a string representing the FunctionDeclaration.name and a structured
 * JSON object containing any output from the function. This is used as context
 * to the model.
 *
 * This should contain the result of a FunctionCall made based on model
 * prediction.
 *
 * @generated from message alis.adk.sessions.v1.FunctionResponse
 */
export declare type FunctionResponse = Message<"alis.adk.sessions.v1.FunctionResponse"> & {
  /**
   * Required. The name of the function that was called.
   * Matches FunctionDeclaration.name and FunctionCall.name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Required. The function response in JSON object format.
   * Use "output" key to specify function output and "error" key to specify
   * error details (if any). If "output" and "error" keys are not specified,
   * then the whole "response" is treated as function output.
   *
   * @generated from field: google.protobuf.Struct response = 2;
   */
  response?: JsonObject | undefined;

  /**
   * Optional. The ID of the function call this response is for. Populated by
   * the client to match the corresponding function call id.
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * Optional. Ordered Parts that constitute a function response.
   * Parts may have different IANA MIME types.
   *
   * @generated from field: repeated alis.adk.sessions.v1.FunctionResponsePart parts = 4;
   */
  parts: FunctionResponsePart[];
};

/**
 * Describes the message alis.adk.sessions.v1.FunctionResponse.
 * Use `create(FunctionResponseSchema)` to create a new message.
 */
export declare const FunctionResponseSchema: GenMessage<FunctionResponse>;

/**
 * FunctionResponsePart represents a datatype containing media that is part of
 * a FunctionResponse message.
 *
 * A FunctionResponsePart consists of data which has an associated datatype.
 * A FunctionResponsePart can only contain one of the accepted types in
 * FunctionResponsePart.data.
 *
 * A FunctionResponsePart must have a fixed IANA MIME type identifying the
 * type and subtype of the media if the inline_data field is filled with raw
 * bytes.
 *
 * @generated from message alis.adk.sessions.v1.FunctionResponsePart
 */
export declare type FunctionResponsePart = Message<"alis.adk.sessions.v1.FunctionResponsePart"> & {
  /**
   * @generated from oneof alis.adk.sessions.v1.FunctionResponsePart.data
   */
  data: {
    /**
     * Inline media bytes.
     *
     * @generated from field: alis.adk.sessions.v1.FunctionResponseBlob inline_data = 1;
     */
    value: FunctionResponseBlob;
    case: "inlineData";
  } | {
    /**
     * URI-based data.
     *
     * @generated from field: alis.adk.sessions.v1.FunctionResponseFileData file_data = 2;
     */
    value: FunctionResponseFileData;
    case: "fileData";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message alis.adk.sessions.v1.FunctionResponsePart.
 * Use `create(FunctionResponsePartSchema)` to create a new message.
 */
export declare const FunctionResponsePartSchema: GenMessage<FunctionResponsePart>;

/**
 * FunctionResponseBlob represents raw media bytes for function response.
 *
 * Text should not be sent as raw bytes; use the 'text' field instead.
 *
 * @generated from message alis.adk.sessions.v1.FunctionResponseBlob
 */
export declare type FunctionResponseBlob = Message<"alis.adk.sessions.v1.FunctionResponseBlob"> & {
  /**
   * Required. The IANA standard MIME type of the source data.
   *
   * @generated from field: string mime_type = 1;
   */
  mimeType: string;

  /**
   * Required. Raw bytes.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * Optional. Display name of the blob.
   *
   * Used to provide a label or filename to distinguish blobs.
   *
   * This field is only returned in PromptMessage for prompt management.
   * It is currently used in the Gemini GenerateContent calls only when server
   * side tools (code_execution, google_search, and url_context) are enabled.
   *
   * @generated from field: string display_name = 4;
   */
  displayName: string;
};

/**
 * Describes the message alis.adk.sessions.v1.FunctionResponseBlob.
 * Use `create(FunctionResponseBlobSchema)` to create a new message.
 */
export declare const FunctionResponseBlobSchema: GenMessage<FunctionResponseBlob>;

/**
 * FunctionResponseFileData represents URI-based data for function response.
 *
 * @generated from message alis.adk.sessions.v1.FunctionResponseFileData
 */
export declare type FunctionResponseFileData = Message<"alis.adk.sessions.v1.FunctionResponseFileData"> & {
  /**
   * Required. The IANA standard MIME type of the source data.
   *
   * @generated from field: string mime_type = 1;
   */
  mimeType: string;

  /**
   * Required. URI.
   *
   * @generated from field: string file_uri = 2;
   */
  fileUri: string;

  /**
   * Optional. Display name of the file data.
   *
   * Used to provide a label or filename to distinguish file data.
   *
   * This field is only returned in PromptMessage for prompt management.
   * It is currently used in the Gemini GenerateContent calls only when server
   * side tools (code_execution, google_search, and url_context) are enabled.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;
};

/**
 * Describes the message alis.adk.sessions.v1.FunctionResponseFileData.
 * Use `create(FunctionResponseFileDataSchema)` to create a new message.
 */
export declare const FunctionResponseFileDataSchema: GenMessage<FunctionResponseFileData>;

/**
 * ExecutableCode represents code generated by the model that is meant to be
 * executed, and the result returned to the model.
 *
 * Generated when using the FunctionDeclaration tool and FunctionCallingConfig
 * mode is set to Mode.CODE.
 *
 * @generated from message alis.adk.sessions.v1.ExecutableCode
 */
export declare type ExecutableCode = Message<"alis.adk.sessions.v1.ExecutableCode"> & {
  /**
   * Required. Programming language of the code.
   *
   * @generated from field: alis.adk.sessions.v1.ExecutableCode.Language language = 1;
   */
  language: ExecutableCode_Language;

  /**
   * Required. The code to be executed.
   *
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message alis.adk.sessions.v1.ExecutableCode.
 * Use `create(ExecutableCodeSchema)` to create a new message.
 */
export declare const ExecutableCodeSchema: GenMessage<ExecutableCode>;

/**
 * Supported programming languages for the generated code.
 *
 * @generated from enum alis.adk.sessions.v1.ExecutableCode.Language
 */
export enum ExecutableCode_Language {
  /**
   * Unspecified language. This value should not be used.
   *
   * @generated from enum value: LANGUAGE_UNSPECIFIED = 0;
   */
  LANGUAGE_UNSPECIFIED = 0,

  /**
   * Python >= 3.10, with numpy and simpy available.
   *
   * @generated from enum value: PYTHON = 1;
   */
  PYTHON = 1,
}

/**
 * Describes the enum alis.adk.sessions.v1.ExecutableCode.Language.
 */
export declare const ExecutableCode_LanguageSchema: GenEnum<ExecutableCode_Language>;

/**
 * CodeExecutionResult represents the result of executing ExecutableCode.
 *
 * Always follows a part containing the ExecutableCode.
 *
 * @generated from message alis.adk.sessions.v1.CodeExecutionResult
 */
export declare type CodeExecutionResult = Message<"alis.adk.sessions.v1.CodeExecutionResult"> & {
  /**
   * Required. Outcome of the code execution.
   *
   * @generated from field: alis.adk.sessions.v1.CodeExecutionResult.Outcome outcome = 1;
   */
  outcome: CodeExecutionResult_Outcome;

  /**
   * Optional. Contains stdout when code execution is successful, stderr or
   * other description otherwise.
   *
   * @generated from field: string output = 2;
   */
  output: string;
};

/**
 * Describes the message alis.adk.sessions.v1.CodeExecutionResult.
 * Use `create(CodeExecutionResultSchema)` to create a new message.
 */
export declare const CodeExecutionResultSchema: GenMessage<CodeExecutionResult>;

/**
 * Enumeration of possible outcomes of the code execution.
 *
 * @generated from enum alis.adk.sessions.v1.CodeExecutionResult.Outcome
 */
export enum CodeExecutionResult_Outcome {
  /**
   * Unspecified status. This value should not be used.
   *
   * @generated from enum value: OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Code execution completed successfully.
   *
   * @generated from enum value: OUTCOME_OK = 1;
   */
  OK = 1,

  /**
   * Code execution finished but with a failure. stderr should contain the
   * reason.
   *
   * @generated from enum value: OUTCOME_FAILED = 2;
   */
  FAILED = 2,

  /**
   * Code execution ran for too long, and was cancelled. There may or may not
   * be a partial output present.
   *
   * @generated from enum value: OUTCOME_DEADLINE_EXCEEDED = 3;
   */
  DEADLINE_EXCEEDED = 3,
}

/**
 * Describes the enum alis.adk.sessions.v1.CodeExecutionResult.Outcome.
 */
export declare const CodeExecutionResult_OutcomeSchema: GenEnum<CodeExecutionResult_Outcome>;

/**
 * GroundingMetadata contains metadata returned to client when grounding is
 * enabled.
 *
 * @generated from message alis.adk.sessions.v1.GroundingMetadata
 */
export declare type GroundingMetadata = Message<"alis.adk.sessions.v1.GroundingMetadata"> & {
  /**
   * Optional. Web search queries for the following-up web search.
   *
   * @generated from field: repeated string web_search_queries = 1;
   */
  webSearchQueries: string[];

  /**
   * Optional. Queries executed by the retrieval tools.
   *
   * @generated from field: repeated string retrieval_queries = 3;
   */
  retrievalQueries: string[];

  /**
   * Optional. Google search entry for the following-up web searches.
   *
   * @generated from field: alis.adk.sessions.v1.SearchEntryPoint search_entry_point = 4;
   */
  searchEntryPoint?: SearchEntryPoint | undefined;

  /**
   * List of supporting references retrieved from specified grounding source.
   *
   * @generated from field: repeated alis.adk.sessions.v1.GroundingChunk grounding_chunks = 5;
   */
  groundingChunks: GroundingChunk[];

  /**
   * Optional. List of grounding support.
   *
   * @generated from field: repeated alis.adk.sessions.v1.GroundingSupport grounding_supports = 6;
   */
  groundingSupports: GroundingSupport[];

  /**
   * Optional. Output only. Retrieval metadata.
   *
   * @generated from field: alis.adk.sessions.v1.RetrievalMetadata retrieval_metadata = 7;
   */
  retrievalMetadata?: RetrievalMetadata | undefined;

  /**
   * Optional. Output only. Resource name of the Google Maps widget context
   * token to be used with the PlacesContextElement widget to render contextual
   * data. This is populated only for Google Maps grounding.
   *
   * @generated from field: string google_maps_widget_context_token = 8;
   */
  googleMapsWidgetContextToken: string;

  /**
   * List of source flagging URIs. This is currently populated only for Google
   * Maps grounding.
   *
   * @generated from field: repeated alis.adk.sessions.v1.GroundingMetadata.SourceFlaggingUri source_flagging_uris = 9;
   */
  sourceFlaggingUris: GroundingMetadata_SourceFlaggingUri[];
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingMetadata.
 * Use `create(GroundingMetadataSchema)` to create a new message.
 */
export declare const GroundingMetadataSchema: GenMessage<GroundingMetadata>;

/**
 * SourceFlaggingUri represents a source content flagging URI for a place or
 * review. This is currently populated only for Google Maps grounding.
 *
 * @generated from message alis.adk.sessions.v1.GroundingMetadata.SourceFlaggingUri
 */
export declare type GroundingMetadata_SourceFlaggingUri = Message<"alis.adk.sessions.v1.GroundingMetadata.SourceFlaggingUri"> & {
  /**
   * ID of the place or review.
   *
   * @generated from field: string source_id = 1;
   */
  sourceId: string;

  /**
   * A link where users can flag a problem with the source (place or review).
   * The link is generated by Google and it does not contain information from
   * the user query. It may contain information of the content it is flagging,
   * which can be used to identify places.
   *
   * @generated from field: string flag_content_uri = 2;
   */
  flagContentUri: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingMetadata.SourceFlaggingUri.
 * Use `create(GroundingMetadata_SourceFlaggingUriSchema)` to create a new message.
 */
export declare const GroundingMetadata_SourceFlaggingUriSchema: GenMessage<GroundingMetadata_SourceFlaggingUri>;

/**
 * GroundingChunk represents a chunk of grounding information from various
 * sources.
 *
 * @generated from message alis.adk.sessions.v1.GroundingChunk
 */
export declare type GroundingChunk = Message<"alis.adk.sessions.v1.GroundingChunk"> & {
  /**
   * Chunk type.
   *
   * @generated from oneof alis.adk.sessions.v1.GroundingChunk.chunk_type
   */
  chunkType: {
    /**
     * Grounding chunk from the web.
     *
     * @generated from field: alis.adk.sessions.v1.GroundingChunk.Web web = 1;
     */
    value: GroundingChunk_Web;
    case: "web";
  } | {
    /**
     * Grounding chunk from context retrieved by the retrieval tools.
     *
     * @generated from field: alis.adk.sessions.v1.GroundingChunk.RetrievedContext retrieved_context = 2;
     */
    value: GroundingChunk_RetrievedContext;
    case: "retrievedContext";
  } | {
    /**
     * Grounding chunk from Google Maps.
     *
     * @generated from field: alis.adk.sessions.v1.GroundingChunk.Maps maps = 3;
     */
    value: GroundingChunk_Maps;
    case: "maps";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingChunk.
 * Use `create(GroundingChunkSchema)` to create a new message.
 */
export declare const GroundingChunkSchema: GenMessage<GroundingChunk>;

/**
 * Web represents a chunk from the web.
 *
 * @generated from message alis.adk.sessions.v1.GroundingChunk.Web
 */
export declare type GroundingChunk_Web = Message<"alis.adk.sessions.v1.GroundingChunk.Web"> & {
  /**
   * Optional. Domain of the chunk.
   *
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * Optional. URI reference of the chunk.
   *
   * @generated from field: string uri = 2;
   */
  uri: string;

  /**
   * Optional. Title of the chunk.
   *
   * @generated from field: string title = 3;
   */
  title: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingChunk.Web.
 * Use `create(GroundingChunk_WebSchema)` to create a new message.
 */
export declare const GroundingChunk_WebSchema: GenMessage<GroundingChunk_Web>;

/**
 * RetrievedContext represents a chunk from context retrieved by the retrieval
 * tools.
 *
 * @generated from message alis.adk.sessions.v1.GroundingChunk.RetrievedContext
 */
export declare type GroundingChunk_RetrievedContext = Message<"alis.adk.sessions.v1.GroundingChunk.RetrievedContext"> & {
  /**
   * Optional. URI reference of the attribution.
   *
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * Optional. Title of the attribution.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Optional. Text of the attribution.
   *
   * @generated from field: string text = 3;
   */
  text: string;

  /**
   * Tool-specific details about the retrieved context.
   *
   * @generated from oneof alis.adk.sessions.v1.GroundingChunk.RetrievedContext.context_details
   */
  contextDetails: {
    /**
     * Additional context for the RAG retrieval result. This is only populated
     * when using the RAG retrieval tool.
     *
     * @generated from field: alis.adk.sessions.v1.RagChunk rag_chunk = 4;
     */
    value: RagChunk;
    case: "ragChunk";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. Output only. The full document name for the referenced Vertex
   * AI Search document.
   *
   * @generated from field: string document_name = 6;
   */
  documentName: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingChunk.RetrievedContext.
 * Use `create(GroundingChunk_RetrievedContextSchema)` to create a new message.
 */
export declare const GroundingChunk_RetrievedContextSchema: GenMessage<GroundingChunk_RetrievedContext>;

/**
 * Maps represents a chunk from Google Maps.
 *
 * @generated from message alis.adk.sessions.v1.GroundingChunk.Maps
 */
export declare type GroundingChunk_Maps = Message<"alis.adk.sessions.v1.GroundingChunk.Maps"> & {
  /**
   * Optional. URI reference of the chunk.
   *
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * Optional. Title of the chunk.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Optional. Text of the chunk.
   *
   * @generated from field: string text = 3;
   */
  text: string;

  /**
   * Optional. This Place's resource name, in `places/{place_id}` format.
   * Can be used to look up the Place.
   *
   * @generated from field: string place_id = 4;
   */
  placeId: string;

  /**
   * Sources used to generate the place answer.
   * This includes review snippets and photos that were used to generate the
   * answer, as well as URIs to flag content.
   *
   * @generated from field: alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources place_answer_sources = 5;
   */
  placeAnswerSources?: GroundingChunk_Maps_PlaceAnswerSources | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingChunk.Maps.
 * Use `create(GroundingChunk_MapsSchema)` to create a new message.
 */
export declare const GroundingChunk_MapsSchema: GenMessage<GroundingChunk_Maps>;

/**
 * PlaceAnswerSources contains sources used to generate the place answer.
 *
 * @generated from message alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources
 */
export declare type GroundingChunk_Maps_PlaceAnswerSources = Message<"alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources"> & {
  /**
   * Snippets of reviews that are used to generate the answer.
   *
   * @generated from field: repeated alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet review_snippets = 1;
   */
  reviewSnippets: GroundingChunk_Maps_PlaceAnswerSources_ReviewSnippet[];

  /**
   * A link where users can flag a problem with the generated answer.
   *
   * @generated from field: string flag_content_uri = 2;
   */
  flagContentUri: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources.
 * Use `create(GroundingChunk_Maps_PlaceAnswerSourcesSchema)` to create a new message.
 */
export declare const GroundingChunk_Maps_PlaceAnswerSourcesSchema: GenMessage<GroundingChunk_Maps_PlaceAnswerSources>;

/**
 * ReviewSnippet encapsulates a review snippet.
 *
 * @generated from message alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet
 */
export declare type GroundingChunk_Maps_PlaceAnswerSources_ReviewSnippet = Message<"alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet"> & {
  /**
   * ID of the review referencing the place.
   *
   * @generated from field: string review_id = 1;
   */
  reviewId: string;

  /**
   * A link to show the review on Google Maps.
   *
   * @generated from field: string google_maps_uri = 2;
   */
  googleMapsUri: string;

  /**
   * Title of the review.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * A reference representing this place review which may be used to look
   * up this place review again.
   *
   * @generated from field: string review = 4;
   */
  review: string;

  /**
   * A link where users can flag a problem with the generated answer.
   *
   * @generated from field: string flag_content_uri = 5;
   */
  flagContentUri: string;

  /**
   * A string of formatted recent time, expressing the review time
   * relative to the current time in a form appropriate for the language
   * and country.
   *
   * @generated from field: string relative_publish_time_description = 6;
   */
  relativePublishTimeDescription: string;
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingChunk.Maps.PlaceAnswerSources.ReviewSnippet.
 * Use `create(GroundingChunk_Maps_PlaceAnswerSources_ReviewSnippetSchema)` to create a new message.
 */
export declare const GroundingChunk_Maps_PlaceAnswerSources_ReviewSnippetSchema: GenMessage<GroundingChunk_Maps_PlaceAnswerSources_ReviewSnippet>;

/**
 * GroundingSupport represents grounding support for a claim in the content.
 *
 * @generated from message alis.adk.sessions.v1.GroundingSupport
 */
export declare type GroundingSupport = Message<"alis.adk.sessions.v1.GroundingSupport"> & {
  /**
   * Optional. Segment of the content this support belongs to.
   *
   * @generated from field: alis.adk.sessions.v1.Segment segment = 1;
   */
  segment?: Segment | undefined;

  /**
   * A list of indices (into 'grounding_chunk') specifying the citations
   * associated with the claim. For instance [1,3,4] means that
   * grounding_chunk[1], grounding_chunk[3], grounding_chunk[4] are the
   * retrieved content attributed to the claim.
   *
   * @generated from field: repeated int32 grounding_chunk_indices = 2;
   */
  groundingChunkIndices: number[];

  /**
   * Confidence score of the support references. Ranges from 0 to 1. 1 is the
   * most confident. This list must have the same size as the
   * grounding_chunk_indices.
   *
   * @generated from field: repeated float confidence_scores = 3;
   */
  confidenceScores: number[];
};

/**
 * Describes the message alis.adk.sessions.v1.GroundingSupport.
 * Use `create(GroundingSupportSchema)` to create a new message.
 */
export declare const GroundingSupportSchema: GenMessage<GroundingSupport>;

/**
 * Segment represents a segment of the content.
 *
 * @generated from message alis.adk.sessions.v1.Segment
 */
export declare type Segment = Message<"alis.adk.sessions.v1.Segment"> & {
  /**
   * Output only. The index of a Part object within its parent Content object.
   *
   * @generated from field: int32 part_index = 1;
   */
  partIndex: number;

  /**
   * Output only. Start index in the given Part, measured in bytes. Offset from
   * the start of the Part, inclusive, starting at zero.
   *
   * @generated from field: int32 start_index = 2;
   */
  startIndex: number;

  /**
   * Output only. End index in the given Part, measured in bytes. Offset from
   * the start of the Part, exclusive, starting at zero.
   *
   * @generated from field: int32 end_index = 3;
   */
  endIndex: number;

  /**
   * Output only. The text corresponding to the segment from the response.
   *
   * @generated from field: string text = 4;
   */
  text: string;
};

/**
 * Describes the message alis.adk.sessions.v1.Segment.
 * Use `create(SegmentSchema)` to create a new message.
 */
export declare const SegmentSchema: GenMessage<Segment>;

/**
 * SearchEntryPoint represents a Google search entry point.
 *
 * @generated from message alis.adk.sessions.v1.SearchEntryPoint
 */
export declare type SearchEntryPoint = Message<"alis.adk.sessions.v1.SearchEntryPoint"> & {
  /**
   * Optional. Web content snippet that can be embedded in a web page or an app
   * webview.
   *
   * @generated from field: string rendered_content = 1;
   */
  renderedContent: string;

  /**
   * Optional. Base64 encoded JSON representing array of <search term, search
   * url> tuple.
   *
   * @generated from field: bytes sdk_blob = 2;
   */
  sdkBlob: Uint8Array;
};

/**
 * Describes the message alis.adk.sessions.v1.SearchEntryPoint.
 * Use `create(SearchEntryPointSchema)` to create a new message.
 */
export declare const SearchEntryPointSchema: GenMessage<SearchEntryPoint>;

/**
 * RetrievalMetadata contains metadata related to retrieval in the grounding
 * flow.
 *
 * @generated from message alis.adk.sessions.v1.RetrievalMetadata
 */
export declare type RetrievalMetadata = Message<"alis.adk.sessions.v1.RetrievalMetadata"> & {
  /**
   * Optional. Score indicating how likely information from Google Search could
   * help answer the prompt. The score is in the range [0, 1], where 0 is the
   * least likely and 1 is the most likely. This score is only populated when
   * Google Search grounding and dynamic retrieval is enabled. It will be
   * compared to the threshold to determine whether to trigger Google Search.
   *
   * @generated from field: float google_search_dynamic_retrieval_score = 2;
   */
  googleSearchDynamicRetrievalScore: number;
};

/**
 * Describes the message alis.adk.sessions.v1.RetrievalMetadata.
 * Use `create(RetrievalMetadataSchema)` to create a new message.
 */
export declare const RetrievalMetadataSchema: GenMessage<RetrievalMetadata>;

/**
 * RagChunk includes the content of a chunk of a RagFile, and associated
 * metadata.
 *
 * @generated from message alis.adk.sessions.v1.RagChunk
 */
export declare type RagChunk = Message<"alis.adk.sessions.v1.RagChunk"> & {
  /**
   * The content of the chunk.
   *
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * Optional. If populated, represents where the chunk starts and ends in the
   * document.
   *
   * @generated from field: alis.adk.sessions.v1.RagChunk.PageSpan page_span = 2;
   */
  pageSpan?: RagChunk_PageSpan | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.RagChunk.
 * Use `create(RagChunkSchema)` to create a new message.
 */
export declare const RagChunkSchema: GenMessage<RagChunk>;

/**
 * PageSpan represents where the chunk starts and ends in the document.
 *
 * @generated from message alis.adk.sessions.v1.RagChunk.PageSpan
 */
export declare type RagChunk_PageSpan = Message<"alis.adk.sessions.v1.RagChunk.PageSpan"> & {
  /**
   * Page where chunk starts in the document. Inclusive. 1-indexed.
   *
   * @generated from field: int32 first_page = 1;
   */
  firstPage: number;

  /**
   * Page where chunk ends in the document. Inclusive. 1-indexed.
   *
   * @generated from field: int32 last_page = 2;
   */
  lastPage: number;
};

/**
 * Describes the message alis.adk.sessions.v1.RagChunk.PageSpan.
 * Use `create(RagChunk_PageSpanSchema)` to create a new message.
 */
export declare const RagChunk_PageSpanSchema: GenMessage<RagChunk_PageSpan>;

/**
 * UsageMetadata contains token accounting details for a model request and
 * response.
 *
 * @generated from message alis.adk.sessions.v1.UsageMetadata
 */
export declare type UsageMetadata = Message<"alis.adk.sessions.v1.UsageMetadata"> & {
  /**
   * Output only. A detailed breakdown of the token count for each modality in
   * the cached content.
   *
   * @generated from field: repeated alis.adk.sessions.v1.ModalityTokenCount cache_tokens_details = 1;
   */
  cacheTokensDetails: ModalityTokenCount[];

  /**
   * Output only. The number of tokens in the cached content that was used for
   * this request.
   *
   * @generated from field: int32 cached_content_token_count = 2;
   */
  cachedContentTokenCount: number;

  /**
   * The total number of tokens in the generated candidates. This includes all
   * the generated response candidates.
   *
   * @generated from field: int32 candidates_token_count = 3;
   */
  candidatesTokenCount: number;

  /**
   * Output only. A detailed breakdown of the token count for each modality in
   * the generated candidates.
   *
   * @generated from field: repeated alis.adk.sessions.v1.ModalityTokenCount candidates_tokens_details = 4;
   */
  candidatesTokensDetails: ModalityTokenCount[];

  /**
   * Number of tokens in the prompt. When cached_content is set, this is still
   * the total effective prompt size meaning this includes the number of tokens
   * in the cached content.
   *
   * @generated from field: int32 prompt_token_count = 5;
   */
  promptTokenCount: number;

  /**
   * Output only. A detailed breakdown of the token count for each modality in
   * the prompt.
   *
   * @generated from field: repeated alis.adk.sessions.v1.ModalityTokenCount prompt_tokens_details = 6;
   */
  promptTokensDetails: ModalityTokenCount[];

  /**
   * Output only. The number of tokens that were part of the model's generated
   * "thoughts" output, if applicable.
   *
   * @generated from field: int32 thoughts_token_count = 7;
   */
  thoughtsTokenCount: number;

  /**
   * Output only. The number of tokens in the results from tool executions,
   * which are provided back to the model as input, if applicable.
   *
   * @generated from field: int32 tool_use_prompt_token_count = 8;
   */
  toolUsePromptTokenCount: number;

  /**
   * Output only. A detailed breakdown by modality of the token counts from the
   * results of tool executions, which are provided back to the model as input.
   *
   * @generated from field: repeated alis.adk.sessions.v1.ModalityTokenCount tool_use_prompt_tokens_details = 9;
   */
  toolUsePromptTokensDetails: ModalityTokenCount[];

  /**
   * The total number of tokens for the entire request. This is the sum of
   * `prompt_token_count`, `candidates_token_count`,
   * `tool_use_prompt_token_count`, and `thoughts_token_count`.
   *
   * @generated from field: int32 total_token_count = 10;
   */
  totalTokenCount: number;

  /**
   * Output only. The traffic type for this request.
   *
   * @generated from field: alis.adk.sessions.v1.TrafficType traffic_type = 11;
   */
  trafficType: TrafficType;
};

/**
 * Describes the message alis.adk.sessions.v1.UsageMetadata.
 * Use `create(UsageMetadataSchema)` to create a new message.
 */
export declare const UsageMetadataSchema: GenMessage<UsageMetadata>;

/**
 * Represents token counting info for a single modality.
 *
 * @generated from message alis.adk.sessions.v1.ModalityTokenCount
 */
export declare type ModalityTokenCount = Message<"alis.adk.sessions.v1.ModalityTokenCount"> & {
  /**
   * Optional. The modality associated with this token count.
   *
   * @generated from field: alis.adk.sessions.v1.MediaModality modality = 1;
   */
  modality: MediaModality;

  /**
   * Number of tokens.
   *
   * @generated from field: int32 token_count = 2;
   */
  tokenCount: number;
};

/**
 * Describes the message alis.adk.sessions.v1.ModalityTokenCount.
 * Use `create(ModalityTokenCountSchema)` to create a new message.
 */
export declare const ModalityTokenCountSchema: GenMessage<ModalityTokenCount>;

/**
 * CitationMetadata contains citation details for sourced or quoted content in
 * a model response.
 *
 * @generated from message alis.adk.sessions.v1.CitationMetadata
 */
export declare type CitationMetadata = Message<"alis.adk.sessions.v1.CitationMetadata"> & {
  /**
   * Optional. Contains citation information when the model directly quotes, at
   * length, from another source. Can include traditional websites and code
   * repositories.
   *
   * @generated from field: repeated alis.adk.sessions.v1.CitationMetadata.Citation citations = 1;
   */
  citations: CitationMetadata_Citation[];
};

/**
 * Describes the message alis.adk.sessions.v1.CitationMetadata.
 * Use `create(CitationMetadataSchema)` to create a new message.
 */
export declare const CitationMetadataSchema: GenMessage<CitationMetadata>;

/**
 * Citation information when the model quotes another source.
 *
 * @generated from message alis.adk.sessions.v1.CitationMetadata.Citation
 */
export declare type CitationMetadata_Citation = Message<"alis.adk.sessions.v1.CitationMetadata.Citation"> & {
  /**
   * Output only. End index into the content.
   *
   * @generated from field: int32 end_index = 1;
   */
  endIndex: number;

  /**
   * Output only. License of the attribution.
   *
   * @generated from field: string license = 2;
   */
  license: string;

  /**
   * Output only. Publication date of the attribution.
   *
   * @generated from field: google.type.Date publication_date = 3;
   */
  publicationDate?: Date | undefined;

  /**
   * Output only. Start index into the content.
   *
   * @generated from field: int32 start_index = 4;
   */
  startIndex: number;

  /**
   * Output only. Title of the attribution.
   *
   * @generated from field: string title = 5;
   */
  title: string;

  /**
   * Output only. URL reference of the attribution.
   *
   * @generated from field: string uri = 6;
   */
  uri: string;
};

/**
 * Describes the message alis.adk.sessions.v1.CitationMetadata.Citation.
 * Use `create(CitationMetadata_CitationSchema)` to create a new message.
 */
export declare const CitationMetadata_CitationSchema: GenMessage<CitationMetadata_Citation>;

/**
 * ToolConfirmation represents a confirmation request for a tool execution.
 *
 * @generated from message alis.adk.sessions.v1.ToolConfirmation
 */
export declare type ToolConfirmation = Message<"alis.adk.sessions.v1.ToolConfirmation"> & {
  /**
   * Hint is the message provided to the user to explain why the confirmation
   * is needed and what action is being confirmed.
   *
   * @generated from field: string hint = 1;
   */
  hint: string;

  /**
   * Confirmed indicates the user's decision.
   * true if the user approved the action, false if they denied it.
   * The state before the user has responded is typically handled outside
   * this struct (e.g., by the absence of a result or a pending status).
   *
   * @generated from field: bool confirmed = 2;
   */
  confirmed: boolean;

  /**
   * Payload contains any additional data or context related to the confirmation
   * request. The structure of the Payload is application-specific.
   *
   * @generated from field: google.protobuf.Value payload = 3;
   */
  payload?: Value | undefined;
};

/**
 * Describes the message alis.adk.sessions.v1.ToolConfirmation.
 * Use `create(ToolConfirmationSchema)` to create a new message.
 */
export declare const ToolConfirmationSchema: GenMessage<ToolConfirmation>;

/**
 * LogprobsResultCandidate represents a candidate for a logprobs result.
 *
 * @generated from message alis.adk.sessions.v1.LogprobsResultCandidate
 */
export declare type LogprobsResultCandidate = Message<"alis.adk.sessions.v1.LogprobsResultCandidate"> & {
  /**
   * The candidate's log probability.
   *
   * @generated from field: float log_probability = 1;
   */
  logProbability: number;

  /**
   * The candidate's token string value.
   *
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * The candidate's token ID value.
   *
   * @generated from field: int32 token_id = 3;
   */
  tokenId: number;
};

/**
 * Describes the message alis.adk.sessions.v1.LogprobsResultCandidate.
 * Use `create(LogprobsResultCandidateSchema)` to create a new message.
 */
export declare const LogprobsResultCandidateSchema: GenMessage<LogprobsResultCandidate>;

/**
 * LogprobsResultTopCandidates represents the top candidates for a logprobs result.
 *
 * @generated from message alis.adk.sessions.v1.LogprobsResultTopCandidates
 */
export declare type LogprobsResultTopCandidates = Message<"alis.adk.sessions.v1.LogprobsResultTopCandidates"> & {
  /**
   * Sorted by log probability in descending order.
   *
   * @generated from field: repeated alis.adk.sessions.v1.LogprobsResultCandidate candidates = 1;
   */
  candidates: LogprobsResultCandidate[];
};

/**
 * Describes the message alis.adk.sessions.v1.LogprobsResultTopCandidates.
 * Use `create(LogprobsResultTopCandidatesSchema)` to create a new message.
 */
export declare const LogprobsResultTopCandidatesSchema: GenMessage<LogprobsResultTopCandidates>;

/**
 * LogprobsResult represents the logprobs result for a model response.
 *
 * @generated from message alis.adk.sessions.v1.LogprobsResult
 */
export declare type LogprobsResult = Message<"alis.adk.sessions.v1.LogprobsResult"> & {
  /**
   * Length = total number of decoding steps. The chosen candidates may or may
   * not be in top_candidates.
   *
   * @generated from field: repeated alis.adk.sessions.v1.LogprobsResultCandidate chosen_candidates = 1;
   */
  chosenCandidates: LogprobsResultCandidate[];

  /**
   * Length = total number of decoding steps.
   *
   * @generated from field: repeated alis.adk.sessions.v1.LogprobsResultTopCandidates top_candidates = 2;
   */
  topCandidates: LogprobsResultTopCandidates[];
};

/**
 * Describes the message alis.adk.sessions.v1.LogprobsResult.
 * Use `create(LogprobsResultSchema)` to create a new message.
 */
export declare const LogprobsResultSchema: GenMessage<LogprobsResult>;

/**
 * Enumeration of possible media modalities.
 *
 * @generated from enum alis.adk.sessions.v1.MediaModality
 */
export enum MediaModality {
  /**
   * The modality is unspecified.
   *
   * @generated from enum value: MEDIA_MODALITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Plain text.
   *
   * @generated from enum value: MEDIA_MODALITY_TEXT = 1;
   */
  TEXT = 1,

  /**
   * Images.
   *
   * @generated from enum value: MEDIA_MODALITY_IMAGE = 2;
   */
  IMAGE = 2,

  /**
   * Video.
   *
   * @generated from enum value: MEDIA_MODALITY_VIDEO = 3;
   */
  VIDEO = 3,

  /**
   * Audio.
   *
   * @generated from enum value: MEDIA_MODALITY_AUDIO = 4;
   */
  AUDIO = 4,

  /**
   * Document, e.g. PDF.
   *
   * @generated from enum value: MEDIA_MODALITY_DOCUMENT = 5;
   */
  DOCUMENT = 5,
}

/**
 * Describes the enum alis.adk.sessions.v1.MediaModality.
 */
export declare const MediaModalitySchema: GenEnum<MediaModality>;

/**
 * Enumeration of possible traffic types.
 *
 * @generated from enum alis.adk.sessions.v1.TrafficType
 */
export enum TrafficType {
  /**
   * The traffic type is unspecified.
   *
   * @generated from enum value: TRAFFIC_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The request was processed using Pay-As-You-Go quota.
   *
   * @generated from enum value: TRAFFIC_TYPE_ON_DEMAND = 1;
   */
  ON_DEMAND = 1,

  /**
   * Type for Provisioned Throughput traffic.
   *
   * @generated from enum value: TRAFFIC_TYPE_PROVISIONED_THROUGHPUT = 2;
   */
  PROVISIONED_THROUGHPUT = 2,
}

/**
 * Describes the enum alis.adk.sessions.v1.TrafficType.
 */
export declare const TrafficTypeSchema: GenEnum<TrafficType>;

/**
 * FinishReason describes why the model stopped generating a response.
 *
 * @generated from enum alis.adk.sessions.v1.FinishReason
 */
export enum FinishReason {
  /**
   * The finish reason is unspecified.
   *
   * @generated from enum value: FINISH_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Token generation reached a natural stopping point or a configured stop
   * sequence.
   *
   * @generated from enum value: FINISH_REASON_STOP = 1;
   */
  STOP = 1,

  /**
   * Token generation reached the configured maximum output tokens.
   *
   * @generated from enum value: FINISH_REASON_MAX_TOKENS = 2;
   */
  MAX_TOKENS = 2,

  /**
   * Token generation stopped because the content potentially contains safety
   * violations. NOTE: When streaming, [content][] is empty if content filters
   * blocks the output.
   *
   * @generated from enum value: FINISH_REASON_SAFETY = 3;
   */
  SAFETY = 3,

  /**
   * The token generation stopped because of potential recitation.
   *
   * @generated from enum value: FINISH_REASON_RECITATION = 4;
   */
  RECITATION = 4,

  /**
   * The token generation stopped because of using an unsupported language.
   *
   * @generated from enum value: FINISH_REASON_LANGUAGE = 5;
   */
  LANGUAGE = 5,

  /**
   * All other reasons that stopped the token generation.
   *
   * @generated from enum value: FINISH_REASON_OTHER = 6;
   */
  OTHER = 6,

  /**
   * Token generation stopped because the content contains forbidden terms.
   *
   * @generated from enum value: FINISH_REASON_BLOCKLIST = 7;
   */
  BLOCKLIST = 7,

  /**
   * Token generation stopped for potentially containing prohibited content.
   *
   * @generated from enum value: FINISH_REASON_PROHIBITED_CONTENT = 8;
   */
  PROHIBITED_CONTENT = 8,

  /**
   * Token generation stopped because the content potentially contains Sensitive
   * Personally Identifiable Information (SPII).
   *
   * @generated from enum value: FINISH_REASON_SPII = 9;
   */
  SPII = 9,

  /**
   * The function call generated by the model is invalid.
   *
   * @generated from enum value: FINISH_REASON_MALFORMED_FUNCTION_CALL = 10;
   */
  MALFORMED_FUNCTION_CALL = 10,

  /**
   * Token generation stopped because generated images have safety violations.
   *
   * @generated from enum value: FINISH_REASON_IMAGE_SAFETY = 11;
   */
  IMAGE_SAFETY = 11,

  /**
   * The tool call generated by the model is invalid.
   *
   * @generated from enum value: FINISH_REASON_UNEXPECTED_TOOL_CALL = 12;
   */
  UNEXPECTED_TOOL_CALL = 12,

  /**
   * Image generation stopped because the generated images have prohibited
   * content.
   *
   * @generated from enum value: FINISH_REASON_IMAGE_PROHIBITED_CONTENT = 13;
   */
  IMAGE_PROHIBITED_CONTENT = 13,

  /**
   * The model was expected to generate an image, but none was generated.
   *
   * @generated from enum value: FINISH_REASON_NO_IMAGE = 14;
   */
  NO_IMAGE = 14,

  /**
   * Image generation stopped because the generated image may be a recitation
   * from a source.
   *
   * @generated from enum value: FINISH_REASON_IMAGE_RECITATION = 15;
   */
  IMAGE_RECITATION = 15,

  /**
   * Image generation stopped for a reason not otherwise specified.
   *
   * @generated from enum value: FINISH_REASON_IMAGE_OTHER = 16;
   */
  IMAGE_OTHER = 16,
}

/**
 * Describes the enum alis.adk.sessions.v1.FinishReason.
 */
export declare const FinishReasonSchema: GenEnum<FinishReason>;

/**
 * SessionService manages agent sessions and session events.
 *
 * @generated from service alis.adk.sessions.v1.SessionService
 */
export declare const SessionService: GenService<{
  /**
   * Creates a new session.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.CreateSession
   */
  createSession: {
    methodKind: "unary";
    input: typeof CreateSessionRequestSchema;
    output: typeof SessionSchema;
  },
  /**
   * Gets details of a specific session.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.GetSession
   */
  getSession: {
    methodKind: "unary";
    input: typeof GetSessionRequestSchema;
    output: typeof SessionSchema;
  },
  /**
   * Lists sessions with optional filtering and ordering.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.ListSessions
   */
  listSessions: {
    methodKind: "unary";
    input: typeof ListSessionsRequestSchema;
    output: typeof ListSessionsResponseSchema;
  },
  /**
   * Updates a specific session.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.UpdateSession
   */
  updateSession: {
    methodKind: "unary";
    input: typeof UpdateSessionRequestSchema;
    output: typeof SessionSchema;
  },
  /**
   * Deletes a specific session.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.DeleteSession
   */
  deleteSession: {
    methodKind: "unary";
    input: typeof DeleteSessionRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Gets a specific event from a session.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.GetEvent
   */
  getEvent: {
    methodKind: "unary";
    input: typeof GetEventRequestSchema;
    output: typeof SessionEventSchema;
  },
  /**
   * Lists events in a given session with optional filtering and ordering.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.ListEvents
   */
  listEvents: {
    methodKind: "unary";
    input: typeof ListEventsRequestSchema;
    output: typeof ListEventsResponseSchema;
  },
  /**
   * Appends an event to a given session.
   *
   * @generated from rpc alis.adk.sessions.v1.SessionService.AppendEvent
   */
  appendEvent: {
    methodKind: "unary";
    input: typeof AppendEventRequestSchema;
    output: typeof AppendEventResponseSchema;
  },
}>;

