// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file alis/a2a/extension/scheduler/v1/scheduler.proto (package alis.a2a.extension.scheduler.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetIamPolicyRequest, SetIamPolicyRequest } from "../../../../../google/iam/v1/iam_policy_pb.js";
import { Policy } from "../../../../../google/iam/v1/policy_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { AddIamBindingsRequest, RemoveIamBindingsRequest } from "../../../../open/iam/v1/iam_pb.js";
import { CreateCronRequest, Cron, DeleteCronRequest, GetCronRequest, ListCronsRequest, ListCronsResponse, RunCronRequest, RunCronResponse, UpdateCronRequest } from "./scheduler_pb.js";
import { Empty } from "../../../../../google/protobuf/empty_pb.js";

/**
 * Manages scheduled invocations of an A2A agent via Cron Jobs
 *
 * @generated from service alis.a2a.extension.scheduler.v1.SchedulerService
 */
export const SchedulerService = {
  typeName: "alis.a2a.extension.scheduler.v1.SchedulerService",
  methods: {
    /**
     * Gets the IAM policy for a resource implemented in this service.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.GetIamPolicy
     */
    getIamPolicy: {
      name: "GetIamPolicy",
      I: GetIamPolicyRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Sets the IAM policy for a resource implemented in this service.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.SetIamPolicy
     */
    setIamPolicy: {
      name: "SetIamPolicy",
      I: SetIamPolicyRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Adds principals or updates the roles existing principals have on an IAM Policy protected resource.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.AddIamBindings
     */
    addIamBindings: {
      name: "AddIamBindings",
      I: AddIamBindingsRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Removes principals or some of the roles they have on an IAM Policy protected resource.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.RemoveIamBindings
     */
    removeIamBindings: {
      name: "RemoveIamBindings",
      I: RemoveIamBindingsRequest,
      O: Policy,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a Cron.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.CreateCron
     */
    createCron: {
      name: "CreateCron",
      I: CreateCronRequest,
      O: Cron,
      kind: MethodKind.Unary,
    },
    /**
     * Lists all Crons.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.ListCrons
     */
    listCrons: {
      name: "ListCrons",
      I: ListCronsRequest,
      O: ListCronsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets a Cron.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.GetCron
     */
    getCron: {
      name: "GetCron",
      I: GetCronRequest,
      O: Cron,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a Cron.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.UpdateCron
     */
    updateCron: {
      name: "UpdateCron",
      I: UpdateCronRequest,
      O: Cron,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a Cron.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.DeleteCron
     */
    deleteCron: {
      name: "DeleteCron",
      I: DeleteCronRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Runs a Cron. This ignores any schedule details and runs the Cron immediately.
     *
     * @generated from rpc alis.a2a.extension.scheduler.v1.SchedulerService.RunCron
     */
    runCron: {
      name: "RunCron",
      I: RunCronRequest,
      O: RunCronResponse,
      kind: MethodKind.Unary,
    },
  }
};

