// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file google/logging/type/http_request.proto (package google.logging.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration } from "../../protobuf/duration_pb";

/**
 * Describes the file google/logging/type/http_request.proto.
 */
export declare const file_google_logging_type_http_request: GenFile;

/**
 * A common proto for logging HTTP requests. Only contains semantics
 * defined by the HTTP specification. Product-specific logging
 * information MUST be defined in a separate message.
 *
 * @generated from message google.logging.type.HttpRequest
 */
export declare type HttpRequest = Message<"google.logging.type.HttpRequest"> & {
  /**
   * The request method. Examples: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`.
   *
   * @generated from field: string request_method = 1;
   */
  requestMethod: string;

  /**
   * The scheme (http, https), the host name, the path and the query
   * portion of the URL that was requested.
   * Example: `"http://example.com/some/info?color=red"`.
   *
   * @generated from field: string request_url = 2;
   */
  requestUrl: string;

  /**
   * The size of the HTTP request message in bytes, including the request
   * headers and the request body.
   *
   * @generated from field: int64 request_size = 3;
   */
  requestSize: bigint;

  /**
   * The response code indicating the status of response.
   * Examples: 200, 404.
   *
   * @generated from field: int32 status = 4;
   */
  status: number;

  /**
   * The size of the HTTP response message sent back to the client, in bytes,
   * including the response headers and the response body.
   *
   * @generated from field: int64 response_size = 5;
   */
  responseSize: bigint;

  /**
   * The user agent sent by the client. Example:
   * `"Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Q312461; .NET
   * CLR 1.0.3705)"`.
   *
   * @generated from field: string user_agent = 6;
   */
  userAgent: string;

  /**
   * The IP address (IPv4 or IPv6) of the client that issued the HTTP
   * request. This field can include port information. Examples:
   * `"192.168.1.1"`, `"10.0.0.1:80"`, `"FE80::0202:B3FF:FE1E:8329"`.
   *
   * @generated from field: string remote_ip = 7;
   */
  remoteIp: string;

  /**
   * The IP address (IPv4 or IPv6) of the origin server that the request was
   * sent to. This field can include port information. Examples:
   * `"192.168.1.1"`, `"10.0.0.1:80"`, `"FE80::0202:B3FF:FE1E:8329"`.
   *
   * @generated from field: string server_ip = 13;
   */
  serverIp: string;

  /**
   * The referer URL of the request, as defined in
   * [HTTP/1.1 Header Field
   * Definitions](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).
   *
   * @generated from field: string referer = 8;
   */
  referer: string;

  /**
   * The request processing latency on the server, from the time the request was
   * received until the response was sent.
   *
   * @generated from field: google.protobuf.Duration latency = 14;
   */
  latency?: Duration;

  /**
   * Whether or not a cache lookup was attempted.
   *
   * @generated from field: bool cache_lookup = 11;
   */
  cacheLookup: boolean;

  /**
   * Whether or not an entity was served from cache
   * (with or without validation).
   *
   * @generated from field: bool cache_hit = 9;
   */
  cacheHit: boolean;

  /**
   * Whether or not the response was validated with the origin server before
   * being served from cache. This field is only meaningful if `cache_hit` is
   * True.
   *
   * @generated from field: bool cache_validated_with_origin_server = 10;
   */
  cacheValidatedWithOriginServer: boolean;

  /**
   * The number of HTTP response bytes inserted into cache. Set only when a
   * cache fill was attempted.
   *
   * @generated from field: int64 cache_fill_bytes = 12;
   */
  cacheFillBytes: bigint;

  /**
   * Protocol used for the request. Examples: "HTTP/1.1", "HTTP/2", "websocket"
   *
   * @generated from field: string protocol = 15;
   */
  protocol: string;
};

/**
 * Describes the message google.logging.type.HttpRequest.
 * Use `create(HttpRequestSchema)` to create a new message.
 */
export declare const HttpRequestSchema: GenMessage<HttpRequest>;

