// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file google/iam/v2beta/policy.proto (package google.iam.v2beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePolicyRequest, DeletePolicyRequest, GetPolicyRequest, ListPoliciesRequest, ListPoliciesResponse, Policy, UpdatePolicyRequest } from "./policy_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Operation } from "../../longrunning/operations_pb.js";

/**
 * An interface for managing Identity and Access Management (IAM) policies.
 *
 * @generated from service google.iam.v2beta.Policies
 */
export declare const Policies: {
  readonly typeName: "google.iam.v2beta.Policies",
  readonly methods: {
    /**
     * Retrieves the policies of the specified kind that are attached to a
     * resource.
     *
     * The response lists only policy metadata. In particular, policy rules are
     * omitted.
     *
     * @generated from rpc google.iam.v2beta.Policies.ListPolicies
     */
    readonly listPolicies: {
      readonly name: "ListPolicies",
      readonly I: typeof ListPoliciesRequest,
      readonly O: typeof ListPoliciesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Gets a policy.
     *
     * @generated from rpc google.iam.v2beta.Policies.GetPolicy
     */
    readonly getPolicy: {
      readonly name: "GetPolicy",
      readonly I: typeof GetPolicyRequest,
      readonly O: typeof Policy,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Creates a policy.
     *
     * @generated from rpc google.iam.v2beta.Policies.CreatePolicy
     */
    readonly createPolicy: {
      readonly name: "CreatePolicy",
      readonly I: typeof CreatePolicyRequest,
      readonly O: typeof Operation,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Updates the specified policy.
     *
     * You can update only the rules and the display name for the policy.
     *
     * To update a policy, you should use a read-modify-write loop:
     *
     * 1. Use [GetPolicy][google.iam.v2beta.Policies.GetPolicy] to read the current version of the policy.
     * 2. Modify the policy as needed.
     * 3. Use `UpdatePolicy` to write the updated policy.
     *
     * This pattern helps prevent conflicts between concurrent updates.
     *
     * @generated from rpc google.iam.v2beta.Policies.UpdatePolicy
     */
    readonly updatePolicy: {
      readonly name: "UpdatePolicy",
      readonly I: typeof UpdatePolicyRequest,
      readonly O: typeof Operation,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Deletes a policy. This action is permanent.
     *
     * @generated from rpc google.iam.v2beta.Policies.DeletePolicy
     */
    readonly deletePolicy: {
      readonly name: "DeletePolicy",
      readonly I: typeof DeletePolicyRequest,
      readonly O: typeof Operation,
      readonly kind: MethodKind.Unary,
    },
  }
};

